### ISSUE TITLE
Occasional AccessViolation in sqlite3_prepare_v2

### ISSUE THREAD

**Issue by jvbeck** [ericsink/SQLitePCL.raw#108]
If the SQL string passed to sqlite3_prepare_v2 is large and contains many statements you may get an occasional Access Violation.  This occurs because the UTF8 byte array created from the SQL string is not marked as "fixed".  The byte array can therefore be moved by the NET Framework: if this happens then the creation of the "tail" string can fail with an Access Violation.

An example of one large SQL string containing many statements would be a single string containing around 100 or so CREATE TABLE statements.

The problem can easily be avoided by ensuring the SQL string only contains one statement.  This would also be more efficient (no tail string creation).

**Comment by ericsink** [comment]
I thought I posted a comment on this already.  :-(

Anyway, yeah, I do see the problem.  I'm thinking the fix looks like this:

        int ISQLite3Provider.sqlite3_prepare_v2(IntPtr db, string sql, out IntPtr stm, out string remain)
        {
            var ba_sql = util.to_utf8(sql);
            GCHandle pinned_sql = GCHandle.Alloc(ba_sql, GCHandleType.Pinned);
            IntPtr ptr_sql = pinned.AddrOfPinnedObject();
            IntPtr tail;
            int rc = NativeMethods.sqlite3_prepare_v2(db, ptr_sql, -1, out stm, out tail);
            pinned_sql.Free();

And something similar in the cppinterop version as well.

**Comment by ericsink** [comment]
(Hmmm.  It turns out the cppinterop version already had the byte array pinned.)

**Comment by ericsink** [comment]
The pre-release of 1.1.1 (now on nuget.org) addresses this issue.

**Comment by jvbeck** [comment]
Thanks for addressing this issue.  Obviously, I switched my code to one statement per string to solve the problem without waiting for a fix.

I may be wrong but I think the pinned_sql.Free() call is too early.  I haven't looked at the SQLite source but I would imagine the returned tail pointer points to a byte in the ba_sql array and therefore the array should be pinned until after the remain string has been created.

Before switching to SQLitePCL.raw, I had an alternate approach to the multiple statements in a single string problem.  Names and types will not match what already exists in SQLitePCL.raw but I'm sure you'll get the idea.

        public static IntPtr[] PrepareCommand(IntPtr db, string sql)
        {
            // a SQL command may contain many statements
            IList<IntPtr> result = new List<IntPtr>();
            byte[] sqlBytes = GetNullTerminatedUtf8(sql);
            int nBytes = sqlBytes.Length;
            SQLiteResult r;
            unsafe
            {
                fixed (byte* bSql = sqlBytes)
                {
                    byte *start = bSql;
                    IntPtr zSql = new IntPtr(start);
                    IntPtr statement;
                    IntPtr zTail;
                    for (; ; )
                    {
                        r = SafeNativeMethods.SQLitePrepare(db, zSql, nBytes, out statement, out zTail);
                        if (r != SQLiteResult.OK)
                        {
                            break;
                        }
                        if (statement != IntPtr.Zero)
                        {
                            result.Add(statement);
                        }
                        if (System.Runtime.InteropServices.Marshal.ReadByte(zTail) == 0)
                        {
                            break;
                        }
                        // loop back for the next statement
                        byte* tail = (byte*)zTail.ToPointer();
                        int usedBytes = (int)(tail - start);
                        nBytes -= usedBytes;
                        zSql = zTail;
                        start = tail;
                    }
                }
            }
            if (r != SQLiteResult.OK)
            {
                string errMsg = GetErrmsg(db);
                FinalizeStatements(result);
                throw new SQLiteException(r, errMsg);
            }
            if (!result.Any()) throw new SQLiteException("No statements in command");
            return result.ToArray();
        }

**Comment by ericsink** [comment]
Addressed in 6e940ce.  Thanks!

**Comment by ericsink** [comment]
Fixed in 1.1.1, now on nuget.org
