### ISSUE TITLE
How to register Logging Callback?

### ISSUE THREAD

**Issue by MKuckert** [ericsink/SQLitePCL.raw#110]
SQLite allows setting up an [error logging callback](http://www.sqlite.org/errlog.html):
```c
void errorLogCallback(void *pArg, int iErrCode, const char *zMsg){
  fprintf(stderr, "(%d) %s\n", iErrCode, zMsg);
}
sqlite3_config(SQLITE_CONFIG_LOG, errorLogCallback, pData);
```

The documentation states
> Application developers are encouraged to take advantage of the error logging facility of SQLite in their products, as it is very low CPU and memory cost but can be a huge aid for debugging.

It looks like the [`sqlite3_config_log` method and `callback_log` delegate type](https://github.com/ericsink/SQLitePCL.raw/blob/master/src/cs/isqlite3.cs#L266) are intended for this purpose. But both are wrapped by an `#if not` conditional and are not included in public builds.

Is this feature intentionally disabled? If so for what reason? Are there alternatives?

**Comment by ericsink** [comment]
I wouldn't call it "intentionally disabled". It's just not implemented (yet). 

That said, everything about sqlite3_config has been a bit tricky. 

I'm currently working on another round of changes. I'll take a look at this one.

**Comment by ericsink** [comment]
The pre-release of 1.1.1 (now on nuget.org) addresses this issue.

**Comment by ericsink** [comment]
1.1.1 has now been released to nuget
