### ISSUE TITLE
Assembly version conflict in v.0.9.3 when used in a UWP app

### ISSUE THREAD

**Issue by corliss** [ericsink/SQLitePCL.raw#112]
I have a UWP app that hadn't been building for a while. Not sure at what point the build broke, so I updated all the nuget assemblies, but the same error, described below, continues to occur.

The error in Visual Studio is:

> Multiple assemblies with equivalent identity have been imported: 'C:\Users\me\\.nuget\packages\System.Threading.Tasks\4.0.0\ref\netcore50\System.Threading.Tasks.dll' and 'C:\Users\me\\.nuget\packages\System.Threading.Tasks\4.0.11\ref\netcore50\System.Threading.Tasks.dll'. Remove one of the duplicate references.

On further investigation, `project.lock.json` reveals these chains of reference:

> System.Threading.Tasks.dll, v4.0.11
> + Referenced by Microsoft.Csharp/4.0.1
>   + Referenced by UAP, Version=10.0
> 
> System.Threading.Tasks.dll, v4.0.0
> +  Referenced by System.Collections/4.0.10
>    + Referenced by SqlitePCL.raw/0.9.3
> 

All other assembles that reference System.Collections reference version 4.0.11, which does not explicitly reference any version of System.Threading.Tasks.dll.

**Summary**
From what I can tell, SqlitePcl.raw seems to be referencing the wrong version of System.Collections, 4.0.10, instead of the correct version System.Collections, 4.0.11.

I'm surprised that such a small difference in the version numbers has broken the build, but then again nuget always confounds me.

What do you think?

Thanks!

**Comment by ericsink** [comment]
Which version of Microsoft.NETCore.UniversalWindowsPlatform are you referencing?  Does this problem go away if you are referencing 5.2.2 ?

**Comment by corliss** [comment]
It was at 5.1.0. I just updated it to 5.2.2 and the same error occurs,

I've also tried building a brand new empty UWP app with SQLitePCL.raw 0.9.3, and it builds fine with both 5.1.0 and 5.2.2.

Appreciate any ideas.

**Comment by ericsink** [comment]
Hmmm.  That's weird.

The 5.2.2 idea was a stab in the dark.  

Here's another suggestion:  Upgrade to SQLitePCL.raw 1.x ?

The package ids changed, so if you're on 0.93, you won't see them as an upgrade from nuget.  

First remove all the SQLitePCL.raw packages.

All the new packages have ids that begin with SQLitePCLRaw.*

Depending on your situation, you probably want one of the bundle packages, such as SQLitePCLRaw.bundle_e_sqlite3.

In general, UWP and netstandard issues got a lot of attention between 0.9.x and 1.1, so let's hope.

**Comment by corliss** [comment]
I will try that and get back to you. Thanks.

**Comment by corliss** [comment]
I notice that there are a plethora of packages with the new names.
Just to make sure I get this right, could you please specify a package I can reference from a library assembly and a package I can reference from the main app assembly? Thanks!

**Comment by ericsink** [comment]
Assuming your app is calling SQLitePCL.raw stuff directly, then:

For a portable library assembly, you probably just need:

    SQLitePCLRaw.Core

For the main app assembly:

    SQLitePCLRaw.bundle_e_sqlite3

**Comment by corliss** [comment]
Thanks - that worked! The project is building nicely. A couple of questions:

1. Previously, with some platforms (notably winforms), I had to manually create x86 and x64 subdirectories and drop builds of sqlite3.dll into them. Is this no longer needed?
1. Is it possible to subsume Batteries.Init() into the bundle? There is also a Batteries_v2 - should I use that instead?

Cheers.

**Comment by ericsink** [comment]
1.  I doubt it will be necessary to manually drop in sqlite builds like you did before.  bundle_e_sqlite3 should handle all that.

2a.   I'm not sure what you mean by "subsume Batteries.Init() into the bundle".  If you elaborate some more, I can probably answer that.  :-)

2b.  In most situations, it doesn't matter whether you call Batteries_V2.Init() or the original Batteries.Init().  Batteries_V2 exists primarily to support an arcane situation where someone wants to distribute a PCL that references SQLitePCL.raw, AND they want to call Batteries.Init() from their PCL, AND they want to allow their users to bait-and-switch from one bundle type to another.

**Comment by corliss** [comment]
1. That's great to hear.
2. I meant, can you avoid exposing Batteries.Init() altogether? Since you are using bait and switch, all calls are going to the platform-specific assembly directly, correct? In which case can't the assembly call Batteries.Init() instead of throwing an exception?

**Comment by ericsink** [comment]
2.  Next time I'm making a round of major changes, I'll think that over.  :-)  For now, I want to continue stabilizing, refining, and polishing things as they are.

**Comment by corliss** [comment]
Sounds good :)
