### ISSUE TITLE
Linux 32-bit support

### ISSUE THREAD

**Issue by lubos** [ericsink/SQLitePCL.raw#113]
I like how Windows package contains both 32-bit and 64-bit binaries of SQLite. I wonder why Linux package contains only 64-bit binary. Any particular reason for that?

**Comment by ericsink** [comment]
There is *probably* no good reason, but I don't recall whether I might have encountered an obstacle.  I'll investigate.

**Comment by ericsink** [comment]
So how does this want to work?  :-)

Currently, the nuget package has a .targets file that copies libe_sqlite3.so to the build output directory.  Right now it always copies the x64 version.

I'm guessing the right answer is to use the msbuild Platform property and see whether it is x86 or x64.

**Comment by lubos** [comment]
For me, the biggest issue is that 32-bit and 64-bit binary for Linux has the same filename. This means you can't distribute .NET app which would work on 32-bit Linux and 64-bit Linux at the same time. You can't deploy "libe_sqlite3.so" for both architectures side-by-side.

On Windows this is solved by having two folders "x64" and "x86" and placing SQLite binaries into these folders.

So why not do this on Linux too? Place "libe_sqlite3.so" into "x64" folder if it's 64-bit binary and "x86" folder for 32-bit binary like on Windows.

Thoughts?

**Comment by ericsink** [comment]
From what I am seeing in testing so far, the technique that works for Windows will not work for Linux.  :-(

On Windows, if you LoadLibraryEx(foo) before you do any DllImport(foo), then the DllImports will get resolved from the library you loaded.  On Linux, this doesn't seem to work.

That means fixing this issue would probably involve switching everything over to some kind of a fully dynamic pinvoke approach, where I don't use DllImport at all, but instead do dlsym() and GetProcAddress() for every symbol.  That's a big change.

**Comment by lubos** [comment]
Thanks for solid research. It's really appreciated even if conclusion is unfavorable.

At least now I know if I want 32-bit Linux support, I will simply need to distribute separate binary packages - one for each architecture which seems to be quite common in Linux world anyway. I was hoping it could be as elegant as it is on Windows but this is not end of the world. Once again, thanks for your time you've put into this.
