### ISSUE TITLE
custom build

### ISSUE THREAD

**Issue by tofutim** [ericsink/SQLitePCL.raw#114]
Hi Eric. I have a custom build of sqlite3 I call xsqlite3 (libxsqlite3, etc.) which contains some custom code, ICU, etc. I would like to make a bundle from your code. It would be nice if there was an option to create a custom bundle with a custom name. (rather than using "custom_sqlite3")

**Comment by ericsink** [comment]
Snarky reply:  Well, it's open source, so there *is* an option.

:-)

Sorry about that, couldn't resist.

But seriously, what kind of support for this are you looking for?

I'm assuming that you are aware of the (admittedly somewhat limited) support for a custom_sqlite3 provider, and that you are saying that you do not want to change the name of your library to custom_sqlite3.

I am further assuming that you are being literal when you say you want to create a bundle, which means that you want to compile and build a nuget package similar to my SQLitePCLRaw.bundle_e_sqlite3.

**Comment by tofutim** [comment]
Thanks for the snarky reply. I like you already. All the xsqlite3.dll/libsqlite3.dylib/libsqlite3.so have already been generated. I just don't want to change my library name to custom_sqlite3. However, there are 'details'. I am using CEROD and SEE so I need additional DllImport for the activate functions.

I see that I can modify gen_build.cs. Maybe something as simple as running ```gen_build.exe --custom xsqlite3``` would be sufficient. With xsqlite3 for everything except for iOS which would be internal. Still exploring your code though.

**Comment by ericsink** [comment]
Your goal here is to make it easy to create a bundle which uses a different name instead of "custom_sqlite3".  I would encourage you to stay focused on that goal and not send me pull requests for things you notice along the way that you wish were different.  

I'm not going to be motivated to accept any pull request which simply changes the way this repo works without adding functionality or fixes.  I'd rather give consideration to the pull request you will have when you are done implementing the feature.  

And if I can answer questions or provide information to help you figure out the best way to do that, please feel free to ask here.

**Comment by tofutim** [comment]
Should I be minimizing changes to the repo enroute to the goal?

**Comment by ericsink** [comment]
If your goal includes eventually convincing me to incorporate changes in my repo, yes, you should definitely minimize changes.

You're working on a feature that I may not want at all.  Like I said in a comment on another issue, if the implementation of that feature is minimal and low-risk, I might take it anyway.

**Comment by tofutim** [comment]
I'll keep that in mind.

**Comment by tofutim** [comment]
what are the v2 batteries, is that for the future?

**Comment by ericsink** [comment]
Batteries v2 is the same as the original except that the assembly name is
always the same. For example, the name of the assembly for batteries v1 in
bundle_green is different from its counterpart in bundle_e_sqlite3. I
consider this a design mistake, but fixing it would be a breaking change.
So I added v2 which is identical except its assembly has the same name in
every bundle. This allows bait and switch of the Init call to work across
bundle types.

E

**Comment by tofutim** [comment]
looks like the various flavors are hard coded into batteries_v2.cs. Too bad C# defines are boolean!

**Comment by tofutim** [comment]
I thought about your low-risk comment. If my version of gen_build creates a bld folder that is SHA-256 identical to yours, would that be a good measure of low-risk changes?

**Comment by ericsink** [comment]
There are guids in the output of gen_build, so an exact match will be, er, difficult. 

It is also the case that generating exactly the same output is not the only factor. I also care about the intent of the code change and how it was done and what was gained.

**Comment by tofutim** [comment]
Good point, and the GUIDs are different every time. Thanks for the notice.

**Comment by ericsink** [comment]
Closing old/stale issue.
