### ISSUE TITLE
Xamarin Mac setup

### ISSUE THREAD

**Issue by tofutim** [ericsink/SQLitePCL.raw#121]
Hi Eric, do you copy the Xamarin.Mac stuff from OSX into Windows? Trying to figure out why this gives me an error

![image](https://cloud.githubusercontent.com/assets/157766/21149902/03618230-c112-11e6-833a-7c6d472274e9.png)

**Comment by ericsink** [comment]
That builds on my machine.  Do you have Xamarin.Mac installed?

**Comment by tofutim** [comment]
Are you building on a Mac or PC? I didn't know I could install Xamarin.Mac
on the PC but I'll look for it.

**Comment by ericsink** [comment]
I'm building on Windows.  I don't remember how I installed stuff, but on my machine, \Program Files (x86)\MSBuild\Xamarin\Mac\ contains stuff.

**Comment by tofutim** [comment]
I remember ages ago I copied stuff from Xamarin Studio on OSX to my PC.
Maybe you did that.

**Comment by ericsink** [comment]
No, I'm reasonably certain I didn't do that.

**Comment by tofutim** [comment]
maybe installed this?

https://github.com/xamarin/xamarin-macios

**Comment by ericsink** [comment]
Not from Github I didn't.  I'm pretty sure I just ran the regular Xamarin Visual Studio installer.

I do have my system paired with a Mac for builds.  It's possible that Xamarin copied the files from my Mac as part of the pairing process.

**Comment by tofutim** [comment]
Interesting, I do have it paired also, but I think it only does anything for iOS. I'll try installing XVS again.

**Comment by tofutim** [comment]
I just updated Xamarin for VS and it looks like they have it as an option
now... will try it


[image: Inline image 1]
