### ISSUE TITLE
two copies of sqlite for custom_sqlite3?

### ISSUE THREAD

**Issue by tofutim** [ericsink/SQLitePCL.raw#122]
Hi Eric, thanks for your patience and feedback. I'm still trying to figure out how it all works. It looks like the provider.custom_sqlite3.net45.csproj (for example) includes core.net45.csproj as a reference, which in turn compiles in .cs code. So would having the SQLitePCL.raw for net45 for a custom_sqlite3 mean that you had both the custom sqlite3 and the core sqlite3? Am I understanding this correctly?

Perhaps that is the same for e_sqlite3? that you have both e_sqlite3 and the sqlite3?

**Comment by ericsink** [comment]
The core library only defines the provider interface and provides code that goes around it.  It contains no implementations of the the provider interface, which is the thing that actually calls sqlite native code.  The core library can't do anything unless somebody calls raw.SetProvider().

**Comment by tofutim** [comment]
I'm probably reading it wrong. Will look some more.
