### ISSUE TITLE
Xamarin Mac Agent connection?

### ISSUE THREAD

**Issue by tofutim** [ericsink/SQLitePCL.raw#123]
Hi Eric, any tips on keeping the Mac Agent alive? I can "connect" from Visual Studio but from the command line it seems to not working.

![image](https://cloud.githubusercontent.com/assets/157766/21156110/7c77f462-c129-11e6-814b-857b82c57130.png)

**Comment by tofutim** [comment]
Maybe that isn't really an issue since there is no application in this case.

**Comment by tofutim** [comment]
Can you clarify if you just ignore this warning?

**Comment by ericsink** [comment]
Those warnings are normal.  Yes, I just ignore them.  You don't actually need the Mac build agent for SQLitePCL.raw, since it's just a library.
