### ISSUE TITLE
SQLitePCLRaw.bundle_green 1.1.1 shows SQLite 3.15.1 instead of 3.15.2 on Xamarin Android

### ISSUE THREAD

**Issue by alemarko** [ericsink/SQLitePCL.raw#132]
Hi Eric,

first, I'd like to thank you for your great effort.

Here is the issue: I'm using **SQLitePCLRaw.bundle_green 1.1.1** on Xamarin for Android and release info on [Nuget page](http://www.nuget.org/packages/SQLitePCLRaw.bundle_green/) says it should be using SQLite 3.15.2 (excerpt from the link, release info for version 1.1.1):

> 1.1.1:  add support for config_log.  **update e_sqlite3 builds to 3.15.2.**  
fix possible memory corruption when using prepare_v2() with multiple statements.  
better errmsg from ugly.step().  add win8 dep groups in bundles.  
fix batteries_v2.Init() to be 'last call wins' like the v1 version is.  
chg raw.SetProvider() to avoid calling sqlite3_initialize() so that sqlite3_config() can be used.  better support for Xamarin.Mac.  

But when I execute following sql command in my app:

> select sqlite_version()

I'm getting result "3.15.1". Is Android really using "3.15.2" or my way of checking the SQLite version is wrong?

Here is the screenshot of the installed packages from Visual Studio, they are all at version 1.1.1:

![sqlite_nuget](https://cloud.githubusercontent.com/assets/1172022/21431834/3613d44a-c869-11e6-97b9-4768ca3dd7de.png)

**Comment by ericsink** [comment]
Oops.  It looks like you're right, the android e_sqlite3 lib didn't get rebuilt with 3.15.2.

**Comment by alemarko** [comment]
OK, thanks for the quick reply

**Comment by ericsink** [comment]
The latest release of SQLitePCL.raw includes SQLite 3.16.1, and I'm pretty sure I got *all* the builds this time. :-)

**Comment by alemarko** [comment]
Thanks  :-))
