### ISSUE TITLE
Windows App Certification Kit

### ISSUE THREAD

**Issue by jabelcs** [ericsink/SQLitePCL.raw#133]
I'm developing a Cordova App using VS2015.
I'm able to build in debug and release modes but when I try to create app packeges for windows I get the following errors:

Error Found: The binary analyzer test detected the following errors:
File c:\program files\windowsapps\38c6d89a.dietmedprofissional_1.0.4.0_x86__3bezmf8a4wq6j\SQLite3.UWP.dll has failed the SafeSEHCheck check.
File c:\program files\windowsapps\38c6d89a.dietmedprofissional_1.0.4.0_x86__3bezmf8a4wq6j\SQLite3.UWP.dll has failed the WXCheck check.

and:

Error Found: The supported APIs test detected the following errors:
API _CrtDbgReport in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
API _CrtDbgReportW in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
API __stdio_common_vsprintf_s in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
API _cexit in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
API _configure_narrow_argv in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
API _crt_at_quick_exit in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
API _crt_atexit in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
API _except1 in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
API _execute_onexit_table in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
API _free_dbg in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.

Please help.

Thanks in advance.

**Comment by ericsink** [comment]
I don't ship an assembly called SQLite3.UWP.dll

Are you also using sqlite-net-pcl ?  See praeclarum/sqlite-net

My guess is that maybe the UWP assembly in sqlite-net-pcl is perhaps not built with release mode.  That guess is partly based on a vague recollection of seeing this problem before, but if there is a github issue for it, I can't find it right now.
