### ISSUE TITLE
AppDomain.CurrentDomain.BaseDirectory is unreliable for Dll discovery

### ISSUE THREAD

**Issue by borrrden** [ericsink/SQLitePCL.raw#134]
A few users have reported this to me, but on web applications the layout of things is different and `AppDomain.CurrentDomain.BaseDirectory` is not where things will live.  They all get put one level down inside the `bin` folder (Seen with both ASP.NET and Nancy) and so [this line](https://github.com/ericsink/SQLitePCL.raw/blob/master/src/cs/sqlite3_pinvoke.cs#L1227) will give a bad result.  However, the subsequent `CodeBase` check seems to be always correct.  The reference you have listed in the comments above this section no longer exists by the way.

**Comment by borrrden** [comment]
Of course the workaround is to manually (or via script) move the native DLLs out of the `bin` folder to where they are expected.

**Comment by ericsink** [comment]
Thanks for the heads-up.  I'll give this a closer look.

**Comment by ericsink** [comment]
Closing old/stale issue.
