### ISSUE TITLE
allocation free sqlite3_column_blob

### ISSUE THREAD

**Issue by prollin** [ericsink/SQLitePCL.raw#135]
`sqlite3_column_blob` allocates a new `byte[]` each time it is called in order to return the corresponding blob content. In the context of a realtime application (game) any managed allocation can result in significant and unpredictable frame drops due to GC pauses.
It seems that it would be fairly simple to offer a version  of `sqlite3_column_blob` that could take a `byte[]` and `offset` provided by the user to copy the blob data into; here is an example implementation for one of the providers:

```
int ISQLite3Provider.sqlite3_column_blob(IntPtr stm, int columnIndex, byte[] result, int offset)
{
  if (result == null || offset >= result.Length)
  {
    return raw.SQLITE_ERROR;
  }
  IntPtr blobPointer = NativeMethods.sqlite3_column_blob(stm, columnIndex);
  if (blobPointer == IntPtr.Zero)
  {
    return raw.SQLITE_ERROR;
  }

  var length = NativeMethods.sqlite3_column_bytes(stm, columnIndex);
  if (offset + length >= result.length)
  {
    return raw.SQLITE_ERROR;
  }
  Marshal.Copy(blobPointer, (byte[])result, offset, length);
  return raw.SQLITE_OK;
}
```

For now the `sqlite3_blob_read` seems to be an alternative, but i am not sure about the performance implications. Also, it stills requires to allocate a `sqlite_blob` object each time; it is lightweight but in a realtime application, streaming a lot of content in and out of a local sqlite db, any small object can quickly add up (not all platforms have a good GC). Going a bit further, wrapping each sqlite data ptr (sqlite_stmt, sqlite_blob, etc) in a simple struct instead of a class could be a better choice to ensure nothing is ever allocated on the managed heap.

This might be a very unique use case though.

**Comment by ericsink** [comment]
I will give this a deeper look as soon as I can.  Thanks.

**Comment by prollin** [comment]
I just thought of a more flexible way to expose blob related methods: what about directly returning the pointer (`IntPtr`) to the unmanaged memory? The advantage would be that the caller can marshal the data to his own data structure instead of having to go through an extra `byte[]` copy.
The existing `byte[]` version can remain for compatibility and convenience.

`sqlite3_bind_blob` could also have a version that take an `IntPtr`. This could greatly improve performance when dealing with array of blittable types (primitive types): the caller can simply use the `fixed` keyword to pin his managed array and send it to sqlite instead of having to allocate an intermediary `byte[]` each call.

I think this could be a better solution than what I proposed above to deal with blobs with minimum extra copy/allocations; It also seems in line with the "raw" spirit of the api!

**Comment by ericsink** [comment]
Hmmm.  I had sort of convinced myself that your original idea was probably sufficiently low-risk.  I suppose this one is interesting as well.  I don't want to just start returning IntPtr throughout the API though.  :-)  This would simply be a special case where we give lower-level access for performance reasons.

**Comment by prollin** [comment]
> I don't want to just start returning IntPtr throughout the API though

If that is an issue, you could take the original proposal and change the signature to: 
`int ISQLite3Provider.sqlite3_column_blob<T>(IntPtr stm, int columnIndex, T[] result, int startIndex) where T: struct`

You'll have to do the marshalling yourself and I am not sure if there are not some corner cases that would not work; this is why I suggested returning a simple IntPtr and trust the caller to do the right thing with it.

**Comment by CyrusNajmabadi** [comment]
FWIW, Roslyn would like this as well.

**Comment by ericsink** [comment]
Well, two requests for this feature.  Perhaps I oughta get it done.

@CyrusNajmabadi Do you have a preferred shape for the new API?  Do any of the suggestions above sound better or worse to you?

**Comment by CyrusNajmabadi** [comment]
My ideal would be a Stream that we could copy out of.  The issue for us is that we don't want to put this in a large byte[] (due to large object heap allocatoins).  We have our own 'chunky streams' in roslyn that break things up into smaller allocations.  If we could give a stream and ask the API to write the data into that stream that would be nice.  

If this doesn't feel right to you, that's fine :)    We can make due without this.  But it would jsut be nice to have!

**Comment by prollin** [comment]
@ericsink a stream is another good way to implement this; in our case, byte[] are already allocated in advance but I do understand @CyrusNajmabadi use case and wrapping things in MemoryStream would be a no brainer on our end. I would be ok with a Stream based implementation.

**Comment by CyrusNajmabadi** [comment]
Also, as part of this, we'd like it if sqlite3_bind_blob exposed the parameter that was the blob length.  Right now we have to make a copy of our data into a fresh byte[] to call sqlite3_bind_blob.   Internally, this is implemented as:

```c#
            return NativeMethods.sqlite3_bind_blob(stm, paramIndex, blob, blob.Length, new IntPtr(-1));
```

We'd like an overload that allows us to pass a length so that we can copy data into pooled byte[]'s to prevent excess allocations.  It seems like it would be as easy as having:

```c#
        int ISQLite3Provider.sqlite3_bind_blob(IntPtr stm, int paramIndex, byte[] blob, int length)
        {
            return NativeMethods.sqlite3_bind_blob(stm, paramIndex, blob, length, new IntPtr(-1));
        }
```

In the meantime though, i can probably work around this by directly getting at: 

```c#
            [DllImport(SQLITE_DLL, ExactSpelling=true, CallingConvention = CallingConvention.Cdecl)]
            public static extern int sqlite3_bind_blob(IntPtr stmt, int index, byte[] val, int nSize, IntPtr nTransient);
```

And calling that directly.

**Comment by CyrusNajmabadi** [comment]
I'm also happy to provide PRs here if you'd like us to go that route.

**Comment by CyrusNajmabadi** [comment]
Note: I've worked around this on the Roslyn side by just calling into the underlying APIs whne necessary.  It's not great having to bypass your library, but it does work.  as such, the demand is less pressing for us.  However, it would still be nice to get something like this from the core library :)

**Comment by ericsink** [comment]
@CyrusNajmabadi Well since you offered a PR, I'd be foolish to decline that.  :-)  At the very least, a PR is great way to communicate very specifically what you are looking for.

To be clear, I do agree that we need a change to SQLitePCL.raw here.  No active resistance from me to the concept in general.

**Comment by ericsink** [comment]
I have pushed 1.1.3 to nuget.  It contains the sqlite3_column_blob overload from @prollin as well as the PR from @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Awesome.  Thanks much!
