### ISSUE TITLE
Crash with sqlite3 logger registered via sqlite3_config_log on 64 bit devices

### ISSUE THREAD

**Issue by slarti-zak** [ericsink/SQLitePCL.raw#136]
I see that you have enabled sqlite logging in #110 but the call into the log callback crashes on 64 bit devices. As I see it, it has something to do with varargs being used in the c native function, the C# binding, and the change of size of pointers.

I came across several bug reports mostly also regarding sqlite:

- [Xamarin bug 28673](https://bugzilla.xamarin.com/show_bug.cgi?id=28673)
- [Xamarin bug 30144](https://bugzilla.xamarin.com/show_bug.cgi?id=30144)

The first issue also links to a [gist](https://gist.github.com/rolfbjarne/cc147285de8e9734aec2#file-gistfile1-txt-L96) with an apparent fix: use the first 8 parameters as int* on 64 bit devices and fill unused ones with IntPtr.Zero.

Is it possible to fix in a similar way and separating the 32 bit and 64 bit handling of the sqlite logger?

**Comment by ericsink** [comment]
I need to dig into this.  In what environment did you observe this crash?  Is it reproducible on all 64-bit platforms you have tried?

**Comment by slarti-zak** [comment]
Firstly, sorry, I should have mentioned that I used 64 bit iPad devices (iPad mini 2, iPad air 2). Secondly,
I may have made an invalid bug report.

I have tested further and downgraded the app to run on an older 32 bit device. The 32 bit device also crashes but does log and exception before going down in contrast to the 64 bit devices where the exception is simply not displayed.

The crash happened when a second call to `sqlite3_config_log` was made. This is an error on my side, calling the function two times, with an easy fix. Still, I am not sure if it should cause a crash in the first place. (Log here: https://gist.github.com/slarti-zak/043caf9527e63b05c71b899d42627b0a ). Please take a look at it.

There was a second crash in the app, which I'm currently investigating but which is not easily testable (also a native crash without exception). I may get back to you on that.

**Comment by ericsink** [comment]
The stack trace in that gist *does* point me toward a possible bug in my code.  I'll need to investigate further to confirm.

**Comment by ericsink** [comment]
Closing old/stale issue.

**Comment by Dolfik1** [comment]
> Closing old/stale issue.

This isssue was actual about 6 mounths ago. So it probably hasn't been fixed yet.

**Comment by ericsink** [comment]
If you have trouble with this function, please open a new issue with full details.
