### ISSUE TITLE
Use App_Data folder on ASP.NET

### ISSUE THREAD

**Issue by bricelam** [ericsink/SQLitePCL.raw#139]
To work well with IIS permissions, etc. ASP.NET (non-Core) typically use the `App_Data` folder for storing data. Would it be possible to set `data_store_directory` to this on .NET Framework (similar to how it's done for UWP)?

The correct way to get the path is to use `AppDomain.CurrentDomain.GetData("DataDirectory")` when it's set.

**Comment by bricelam** [comment]
And, of course I mean call `sqlite3_win32_set_directory()` because `PRAGMA data_store_directory` is deprecated 😉

**Comment by bricelam** [comment]
...but in a Mono-friendly way. lol, this is getting messy.

**Comment by ericsink** [comment]
If I understand correctly, you are referring to the place in sqlite3_pinvoke.cs where the code does this:

    NativeMethods.sqlite3_win32_set_directory(/*data directory type*/1, Windows.Storage.ApplicationData.Current.LocalFolder.Path);

And wanting something similar to happen for ASP.NET.

(1)   As mentioned in a comment there, those lines of code have become problematic, and I kinda wish I could remove them, but it would be a breaking change.  Adding more of such things would be a (vague) concern.

(2)  Is there a way to know when the code is running on ASP.NET (non core)?  AFAIK, nuget cannot distinguish between a .NET console app and an ASP.NET app, so the decision would have to be made at runtime.  Adding a `sqlite3_win32_set_directory` for all net45 scenarios would probably be a breaking change for existing users.

(3)  And (as you point out in a comment I just saw come in), Mono would be an issue here as well.

**Comment by bricelam** [comment]
Yeah, probably best to handle in `Microsoft.Data.Sqlite`. Closing in favor of aspnet/Microsoft.Data.Sqlite#321
