### ISSUE TITLE
Missing raw.SQLITE_CHECKPOINT_TRUNCATE

### ISSUE THREAD

**Issue by prollin** [ericsink/SQLitePCL.raw#141]
Missing `SQLITE_CHECKPOINT_TRUNCATE` const definition in the `raw` class. This option was added in Sqlite 3.8.8

**Comment by ericsink** [comment]
WELL then.

That'll be easy enough to fix.

**Comment by prollin** [comment]
I should probably have sent a PR :) i just don't know sqlite history well enough to be sure there is not a good reason this option wasn't there (compatibility across platform implementations would be one).

**Comment by ericsink** [comment]
Fixed in 1.1.3
