### ISSUE TITLE
Question about how to use sqlcipher

### ISSUE THREAD

**Issue by smasherprog** [ericsink/SQLitePCL.raw#142]
I am adding   
SQLitePCL.raw.SetProvider(new SQLitePCL.SQLite3Provider_sqlcipher());
Then calling Batteries.Init()

But, how would a password be specified for the Database? I found that the Android library is compiled with the sqlite3_key  function so it can be called and used, but does this work for the other platforms as well? I am looking at the DLL created for windows and that function doesnt appear to be in the DLL.

**Comment by ericsink** [comment]
See pragma key:

https://www.zetetic.net/sqlcipher/sqlcipher-api/

**Comment by smasherprog** [comment]
Thanks for the fast response!
So just in case anyone has the same issue as me, The process is to set the cipher provider before doing ANY db access, then call Batteries_V2.Init()      The next step would be to call Open on the Database as normal, then call Execute()   of PRAGMA key ='passwordhere';


in c#, the code is generally like this . . 
ON startup
SQLitePCL.raw.SetProvider(new SQLitePCL.SQLite3Provider_sqlcipher());
SQLitePCL.Batteries_V2.Init();

Open DB and Set the Password for the encrypted DB 
SQLite3.Open(databasePath, out handle, (int)openFlags, IntPtr.Zero);
Execute("PRAGMA key = '" + password + "';");



Thanks for the help eric, and the great library!

**Comment by ericsink** [comment]
FWIW, it doesn't seem like that SetProvider() call should be needed.  That's what Batteries_V2.Init() does.  It calls SetProvider().  If you remove that call, does it still work?

**Comment by smasherprog** [comment]
Ill try that out and see.
