### ISSUE TITLE
iOS app crashing when calling GetTable<T>

### ISSUE THREAD

**Issue by pauldiston** [ericsink/SQLitePCL.raw#143]
I have a crash occurring in our iOS app, with the following stack trace taken from the Output window (truncated to show top most stack trace entries) (no exception is caught in the try/catch) :-

 11:43:58.831 [1859:2672475] critical: Stacktrace:
 11:43:58.831 [1859:2672475] critical:   at <unknown> <0xffffffff>
 11:43:58.831 [1859:2672475] critical:   at (wrapper managed-to-native) SQLitePCL.SQLite3Provider_sqlite3/NativeMethods.sqlite3_prepare_v2 (intptr,byte[],int,intptr&,intptr&) <0x00007>
 11:43:58.831 [1859:2672475] critical:   at SQLitePCL.SQLite3Provider_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_prepare_v2 (intptr,string,intptr&,string&) <IL 0x0000b, 0x000b7>
 11:43:58.831 [1859:2672475] critical:   at SQLitePCL.raw.sqlite3_prepare_v2 (SQLitePCL.sqlite3,string,SQLitePCL.sqlite3_stmt&,string&) <IL 0x0000f, 0x000f7>
 11:43:58.831 [1859:2672475] critical:   at SQLitePCL.raw.sqlite3_prepare_v2 (SQLitePCL.sqlite3,string,SQLitePCL.sqlite3_stmt&) <IL 0x00005, 0x00073>
 11:43:58.831 [1859:2672475] critical:   at SQLite.SQLite3.Prepare2 (SQLitePCL.sqlite3,string) [0x00002] in /Users/fak/Dropb
ox/Projects/sqlite-net/src/SQLite.cs:3374
 11:43:58.832 [1859:2672475] critical:   at SQLite.SQLiteCommand.Prepare () [0x00000] in /Users/fak/Dropbox/Projects/sqlite-net/src/SQLite.cs:2316
 11:43:58.832 [1859:2672475] critical:   at SQLite.SQLiteCommand/<ExecuteDeferredQuery>c__Iterator0`1<T_REF>.MoveNext () <0x00143>
 11:43:58.832 [1859:2672475] critical:   at System.Collections.Generic.List`1<T_REF>..ctor (System.Collections.Generic.IEnumerable`1<T_REF>) <0x00257>
 11:43:58.832 [1859:2672475] critical:   at System.Linq.Enumerable.ToList<TSource_REF> (System.Collections.Generic.IEnumerable`1<TSource_REF>) <0x0004b>
 11:43:58.832 [1859:2672475] critical:   at SQLite.SQLiteCommand.ExecuteQuery<T_REF> () <0x000e3>
 11:43:58.832 [1859:2672475] critical:   at SQLite.TableQuery`1<T_REF>.GetEnumerator () <0x000b3>
 11:43:58.832 [
1859:2672475] critical:   at System.Collections.Generic.List`1<T_REF>..ctor (System.Collections.Generic.IEnumerable`1<T_REF>) <0x001df>
 11:43:58.832 [1859:2672475] critical:   at System.Linq.Enumerable.ToList<TSource_REF> (System.Collections.Generic.IEnumerable`1<TSource_REF>) <0x0004b>
 11:43:58.832 [1859:2672475] critical:   at Skillweb.Sorbet.Shared.iOS.Service.SorbetSqliteDatabaseService.GetTable<T_REF> () <0x000eb>

I am not sure why this exception is occurring. I am currently using the following packages :-

package id="sqlite-net-pcl" version="1.2.1" targetFramework="xamarinios10"
package id="SQLitePCL.raw" version="0.9.3" targetFramework="xamarinios10"
package id="SQLitePCLRaw.bundle_green" version="1.1.0" targetFramework="xamarinios10"
package id="SQLitePCLRaw.core" version="1.1.0" targetFramework="xamarinios10"
package id="SQLitePCLRaw.provider.sqlite3.ios_unified" version="1.1.0" targetFramework="xamarinios10"

I have tried installing 1.3.1 of sqlite-net-pcl however not sure why all the .Net Standard 1.6.0 wants to be installed.

The method that is invoking the GetTable method is within an await Task.Run call.

Do you have any idea why this exception is being raised and how to resolve the issue?

**Comment by ericsink** [comment]
One thing is that you need to remove the SQLitePCL.raw package.  It was superseded by SQLitePCLRaw.core.  But I'm not sure if that's related to this problem.

**Comment by AndreiMisiukevich** [comment]
https://stackoverflow.com/questions/30270407/xamarin-crash-on-ios-only-on-sqlite-update-call-for-model

It helped me
