### ISSUE TITLE
How to use SQLitePCLRaw.lib.sqlcipher.windows.1.1.2 nuget package?

### ISSUE THREAD

**Issue by sinall** [ericsink/SQLitePCL.raw#144]
I'm trying to use SQLitePCL with sqlcipher in VS2015 C++ on Windows desktop.
I have installed SQLitePCLRaw.lib.sqlcipher.windows.1.1.2.
There's no header files in the package folder.
> 	./build
> 	./build/SQLitePCLRaw.lib.sqlcipher.windows.targets
> 	./runtimes
> 	./runtimes/win7-x64
> 	./runtimes/win7-x64/native
> 	./runtimes/win7-x64/native/sqlcipher.dll
> 	./runtimes/win7-x86
> 	./runtimes/win7-x86/native
> 	./runtimes/win7-x86/native/sqlcipher.dll
> 	./SQLitePCLRaw.lib.sqlcipher.windows.1.1.2.nupkg

What did I miss? What to do next?

=========================================
Just found this description on Nuget:

> To use this, you need SQLitePCLRaw.core as well as SQLitePCLRaw.provider.sqlcipher.net45 or similar. Convenience packages are named SQLitePCLRaw.bundle_*

So, is there a package for VC++ 2015?

**Comment by ericsink** [comment]
SQLitePCL.raw is designed for use with managed code, not C++. If you just need a SQLCipher build for Windows, I would go to Zetetic.  Or you could get the same build I bundle from

https://github.com/couchbaselabs/couchbase-lite-libsqlcipher
