### ISSUE TITLE
use custom sqlite3 library

### ISSUE THREAD

**Issue by MATrotski** [ericsink/SQLitePCL.raw#145]
Hi, I have an application for xamarin forms (ios). I am using your provider SqlitePCLRaw.provider.custom_sqlite3.netstandart11 and trying to connect custom static library for ios. I built my custom library like libcustom_sqlite3.a (and renamed it like "custom_sqlite3" too), but it didn't work. Than I tryed to linking library like this https://developer.xamarin.com/guides/ios/advanced_topics/native_interop/  - the same result (System.DllNotFoundException custom_sqlite3). Could you help me?
Thank's

**Comment by CyberNyanta** [comment]
@MATrotski Have you solve your problem?

**Comment by x37v** [comment]
@ericsink on this note, is there a tutorial or example project or something that shows how to use 'custom_sqlite3'? I'm curious about Android and iOS right now but eventually Windows, Linux, MacOS too.

**Comment by ericsink** [comment]
Currently, no, I don't have a tutorial like that. I need to make it easier to use a custom SQLite build, but I haven't made any progress on that.

**Comment by x37v** [comment]
@ericsink the 1.0 features in your README include: *Provide an easier way for people to use custom sqlite3 builds* 😄 

Maybe you could write a wiki entry at least that indicates the process?

**Comment by ericsink** [comment]
Maybe. 

Here's a really short version of that wiki page:

The custom_sqlite3 feature was added to make it easier to use custom SQLite builds. Insofar as running a five minute mile is easier than running a four minute mile, the feature succeeded. In other words, in practical terms, it failed.

A somewhat longer version might be more helpful than this.

**Comment by plamenkoyovchev** [comment]
I have exactly the same problem I want to force my Xamarin.Forms iOS app to use SQLite 3.26.0 instead of the embedded SQLite 3.24.0 , I wasted a lot of time for research but I am still not able to find anything useful.

**Comment by kroggen** [comment]
Any update on this?

I modified one of the providers with a different library name, then tried to upload the nuget package but the site says that the namespace is reserved...

Should we get an authorization for using the namespace?

I suppose that using another namespace is not allowed due to the Apache 2.0 license...

Any solution?

**Comment by ericsink** [comment]
Closing old/stale issue.
