### ISSUE TITLE
winsqlite3.dll should use CallingConvention.StdCall

### ISSUE THREAD

**Issue by bricelam** [ericsink/SQLitePCL.raw#149]
Still working out the details on this one, but it sounds like the P/Invokes for `winsqlite3.dll` should use `CallingConvention.StdCall` instead of `Cdecl`.

cc @vrk7bp

**Comment by ericsink** [comment]
I'm a bit short on knowledge here, so I ask your patience with a possibly dumb question:

If the C# code is using the wrong calling convention for that native DLL, why does it work?

**Comment by bricelam** [comment]
You'll only observe differences in a few corner cases. The two things that have been mentioned so far are:
* You could get a corrupt stack when SQLite invokes a managed callback
* Trying to debug crashes with a corrupt stack

**Comment by ericsink** [comment]
OK, I have just pushed 1.1.3 to nuget, with the change to StdCall for winsqlite3.  So I'm closing this as fixed.

That said, I'd be happier if I had a test case which failed with Cdecl.  My test suite, which contains a number of cases where SQLite invokes a managed callback, passes with StdCall, but it also passed with Cdecl.  So at the moment, I see no visible difference.
