### ISSUE TITLE
Error during store certification

### ISSUE THREAD

**Issue by tkohub** [ericsink/SQLitePCL.raw#150]
Hello everyone,

during UWP 10 appstore certification i get the following errors. Does anyone have an idea what is going wrong? Since i see no other reports here i assume it is working fine for other people? Also, my local certification kit passes successfully, only the app store certification goes wrong. I am using version 1.1.2.

Thanks for your help!

Tobias

`    API sqlite3_bind_blob in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_bind_double in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_bind_int in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_bind_int64 in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_bind_null in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_bind_parameter_index in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_bind_text16 in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_busy_timeout in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_changes in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_close in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_column_blob in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_column_bytes in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_column_count in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_column_double in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_column_int in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_column_int64 in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_column_name in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_column_name16 in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_column_text in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_column_text16 in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_column_type in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_config in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_errmsg16 in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_finalize in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_last_insert_rowid in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_open in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_open16 in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_open_v2 in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_prepare_v2 in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_reset in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_step in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.
    API sqlite3_win32_set_directory in sqlite3.dll is not supported for this application type. MobileClient.Win10.exe calls this API.`

**Comment by ericsink** [comment]
This issue (or something similar) has happened before, but I am having trouble remembering the details.

You built in release mode?

**Comment by tkohub** [comment]
Thanks for the quick response!

I am using the 'Create Package' option from VS 2015. There i select Release for all three architectures and trigger the packaging. (I also tried one by one) The weird thing is that the certification tool on my machine also reports that all APIs are fine, just on the store i get the messages. 

The messages also dont really make sense right? Calls like 'sqlite3_bind_double' should be availabe?

I'll investigate one more time and verify that i built in release mode now.

**Comment by tkohub** [comment]
So I checked and the app is built in release mode. The store certification tool also passes the corresponding test:
PASSED
    Debug configuration

(In this case passed means, "Make sure it is not a debug build")

**Comment by ericsink** [comment]
For reference, the previous time (something like) this came up, it was issue #85.

That issue mentions the notion that the native library bits were somehow now getting included in the package.  So I guess that would be the next thing to verify?

**Comment by tkohub** [comment]
Not sure if i understand you correctly. What i did now is i unpacked the .appx and checked the content. 

Has three dlls inside:

- MobileClient.Win10.dll
- e_sqlite3.dll
- clrcompression.dll

So the native library seems to be there, right? Is that what you meant?

Just for understanding my setup. I have a pcl project that has references SQLitePCLRaw.core, SQLitePCLRaw.batteries_v2 and SQLitePCLRaw.batteries_e_sqlite3. That project is then referenced by my Win10 project. The Win10 project also references SQLitePCLRaw.batteries_e_sqlite3.

**Comment by ericsink** [comment]
Yeah, that's what I meant.

Which means we need to dig deeper.  I'll take another look at this issue
tomorrow.

E

**Comment by tkohub** [comment]
I am sorry. It looks like i had a dangling reference to an old sqlite implementation in the project. I am still confused why it only fails on the online/store certification but it's in review for quite a while now which is promising... 

However, thanks a lot for your time and quick help! I really appreciate it.

I'll come back to close the issue when i am sure it worked out.

**Comment by ericsink** [comment]
Yay
