### ISSUE TITLE
UWP Bait and Switch not detecting SQLitePCLRaw.bundle_sqlcipher

### ISSUE THREAD

**Issue by AHumbleDevonian** [ericsink/SQLitePCL.raw#152]
This may be a configuration issue but I've yet to find a working solution.

I have SQLite-Net-PCL attached to a Xamarin Forms PCL to build and maintain an encrypted database for an App, using SQLitePCLRaw.bundle_sqlcipher for the Bait and Switch.

This works perfectly fine on iOS and Android, but on UWP no matter what I do it seems it can't detect the SQLitePCLRaw.bundle_sqlcipher. It throws the same error that would occur as if the Nuget package isn't installed.

If I install the basic SQLite-Net-PCL onto the UWP project the database can run normally but this is no good since the encryption is a requirement.

I've had a dig through the documentation and I can't see anything that needs to be specific for UWP (unless I'm being an idiot which does happen). Is there something I'm missing?

The UWP is a freshly created project in VS 2017, with nothing but Xamarin.Forms and the standard UWP Nuget Packages.

**Comment by ericsink** [comment]
Can I see your csproj file?

**Comment by AHumbleDevonian** [comment]
Here - 

[App8.UWP.zip](https://github.com/ericsink/SQLitePCL.raw/files/910149/App8.UWP.zip)

**Comment by ericsink** [comment]
Hmmm.  This is on project.json.  I sort of expected to see the shorter csproj with PackageReference.  So my initial random guess was wrong.

I'll dig into this more this afternoon.  Thanks.

**Comment by AHumbleDevonian** [comment]
Thank you.

I've just created a new VS 2017 project and the issue does persist. If I get 5 minutes I'll try it on VS 2015 too just incase its something to do with project creation/initial setup.

My initial thought it was something to do with the way UWP gets Nuget but since the SQLite-net-pcl does work it left me a bit confused.

**Comment by ericsink** [comment]
Just to be sure:  For this kind of bait-and-switch to work, you need sqlite-net-pcl to NOT be added to your UWP app csproj.  And not bundle_green either.  But you *do* need bundle_sqlcipher.

You're trying to make sure that, at the time the app itself is built,. the sqlite-net-pcl reference to bundle_green gets replaced by bundle_sqlcipher.

Does that make sense?

**Comment by AHumbleDevonian** [comment]
Yes, I double checked that.

The UWP project only has bundle_sqlcipher. 

As a test I removed the bundle_sqlcipher from the UWP and replaced it with the sqlite-net-pcl nuget package which obviously contains bundle_green. 

It was able to pick up the bundle_green inside sqlite-net-pcl but not bundle_sqlcipher on its own.

**Comment by AHumbleDevonian** [comment]
I'm getting the same issue in VS 2015 as well.

Here is a screen shot incase its any help.
![uwp-sqlcipher](https://cloud.githubusercontent.com/assets/13856887/24869535/76086b68-1e0b-11e7-999c-51bf517ab573.PNG)

**Comment by ericsink** [comment]
Oh good grief.  I can't believe I didn't realize this earlier today:

The sqlcipher bundle doesn't support UWP yet.

My sqlcipher packages are just wrappers around the sqlcipher builds maintained by Couchbase.  And they don't support UWP yet either (last time I checked, anyway).  But they are planning to do so, and sometime (shortly) after that, so will I.

**Comment by AHumbleDevonian** [comment]
Ah that's a pity. Nevermind, will just have to move forward just with iOS and Android for the time being.

Thanks for you help.
