### ISSUE TITLE
Wal mode is not working when using SQLCipher

### ISSUE THREAD

**Issue by idrish-rishabhsoft** [ericsink/SQLitePCL.raw#155]
When trying to set Wal mode on connection of encrypted database. It is giving exception that database is locked. 

Here is my code snippet, 
` var connectionFactory = Mvx.Resolve<IMvxSqliteConnectionFactory>();
            var _connection = connectionFactory.GetAsyncConnection(Helpers.GetDatatbasePath(),false);
            var resultCode = connection.ExecuteAsync(string.Format("PRAGMA key='{0}'", Constants.SqliteKey)).Result;
var journalMode = _connection.ExecuteScalarAsync<string>("PRAGMA journal_mode = wal"); // = wal"); `

I am almost done with app but this is show stopper for me. Kindly directly me

**Comment by ericsink** [comment]
I'm not sure I can be of much help with this one.

Is your code correct?  I mean, do you know for sure that calling key and journal_mode *should* work in the way you are calling them?  I'm guessing that you are doing those calls in the correct order, but I'm not sure, as I don't use sqlcipher regularly.

I don't know what version of SQLitePCL.raw you are using.  Or how.  Looks like MvvmCross is involved.

I don't know what platform you are on.

Was this working before and then it stopped working?  What changed?

You're using .Result on an async call, which could be causing all problems, but I'm not sure if it's related to what you are seeing.

**Comment by idrish-rishabhsoft** [comment]
Thanks for asking these many questions. It really open up my mind for other direction. I was getting database locked because other part of program was already accessing database(another db connection was alive). 
so, there was nothing related to library. 

Thanks for your quick help
