### ISSUE TITLE
Package authoring issue: sqlitepclraw.lib.e_sqlite3.linux 

### ISSUE THREAD

**Issue by kichalla** [ericsink/SQLitePCL.raw#157]
I am using the CLI version: `2.0.0-preview1-005899`

**Repro steps**
- dotnet new console
- Add the following package reference
```
<ItemGroup>
    <PackageReference Include="SQLitePCLRaw.bundle_green" version="1.1.4" />
  </ItemGroup>
```
- dotnet restore
- dotnet build

You should see the error:
```
/home/kiran/.dotnet/sdk/2.0.0-preview1-005899/Microsoft.Common.CurrentVersion.targets(4326,5): error MSB3030: Could not copy the file "/home/kiran/.nuget/packages/sqlitepclraw.lib.e_sqlite3.linux/1.1.4/build/runtimes/linux-x64/native/libe_sqlite3.so" because it was not found. [/home/kiran/sqlite-repro/sqlite-repro.csproj]

```
The path to the runtimes folder should look one more folder up
![image](https://cloud.githubusercontent.com/assets/6559784/25586710/6bfed12a-2e55-11e7-9dac-8e173c9d8d33.png)

**Comment by ericsink** [comment]
This works on:

    eric@DESKTOP-V91DES3:/mnt/c/Users/eric$ dotnet --version
    1.0.3

The error message indicates that something is looking for the native lib at:

    build/runtimes/linux-x64/native/libe_sqlite3.so

but actually in this package it is located at:

    runtimes/linux-x64/native/libe_sqlite3.so

What I don't know is:

1.  Why would the behavior be different for the "current" .NET Core SDK and the 2.0 preview 1?
2.  Is build/runtimes the more correct place?

**Comment by kichalla** [comment]
@ericsink I updated my original post and not sure if you got a chance to look at the updated snapshot. Please take a look again. I looked at the osx package and it does have the right runtimes folder look up, so this seems like an issue with Linux package only.

**Comment by ericsink** [comment]
Yes, it does appear that the targets file has an incorrect path.  I will fix that.

But now the question is why this error is happening for you on .NET Core.  The primary fix of the 1.1.4 release was to move that targets file down into build/net35 so that .NET Core would not see it.

**Comment by kichalla** [comment]
I am not sure, but probably @natemcmaster might have an idea.

**Comment by ericsink** [comment]
The concern here is that maybe the 1.1.4 fix was somehow insufficient to correctly fix #154, and therefore also insufficient to address aspnet/Microsoft.Data.Sqlite#360 for preview1?

**Comment by natemcmaster** [comment]
To clarify, the net35 target is being imported to netcoreapp2.0? That's likely nuget bug. I'll investigate.

**Comment by natemcmaster** [comment]
https://github.com/NuGet/Home/issues/5149

**Comment by ericsink** [comment]
OK, so the bug here in SQLitePCL.raw is just the bad path in that targets file, which only affects Mono Linux users, so I'm not going to hurry a bugfix release.

**Comment by ericsink** [comment]
@kichalla I'm surprised you are reverting to 1.1.3.  Should I push out a 1.1.5 (with the targets file path fix) today so you can use it?

**Comment by kichalla** [comment]
@ericsink yes, if you can it would be great. Thanks.

**Comment by ericsink** [comment]
SQLitePCL.raw 1.1.5 has been pushed to nuget.  The only change since 1.1.4 is the fix for the path in the linux targets file.

**Comment by natemcmaster** [comment]
FYI - you can workaround the .NET Core 2.0 issue by setting `<DisableImplicitPackageTargetFallback>true</DisableImplicitPackageTargetFallback>` in your project. This should be temporary as we work on a solution for https://github.com/dotnet/sdk/issues/1166.

**Comment by ericsink** [comment]
I believe everything in this issue that I need to address has been done.  Re-open and clarify if I am mistaken.
