### ISSUE TITLE
SQLitePCL.Batteries_V2.Init() not working in UWP with SQLitePCLRaw.bundle_sqlcipher v1.1.5

### ISSUE THREAD

**Issue by mchipeta** [ericsink/SQLitePCL.raw#158]
Hi. Is SQLCipher supported in UWP?

I tried this code

`SQLitePCL.Batteries_V2.Init();`
`sqlite3 db;`
`var rc = raw.sqlite3_open(":memory:", out db);`
`Debug.Assert(rc == raw.SQLITE_OK);`

in a blank UWP app created in VS 2017 after installing **SQLitePCLRaw.bundle_sqlcipher v1.1.5** via NuGet, but I got the exception below:

_System.Exception occurred
  HResult=0x80131500
  Message=This is the 'bait'.  You probably need to add one of the SQLitePCLRaw.bundle__* _nuget packages to your platform project.
  Source=Cannot evaluate the exception source
  StackTrace:
   at SQLitePCL.Batteries_V2.Init()
   ..._

If I replace SQLitePCLRaw.bundle_sqlcipher with **SQLitePCLRaw.bundle_green v1.1.5**, the code works as expected after replacing `SQLitePCL.Batteries_V2.Init();` with `SQLitePCL.Batteries.Init();`.

**Comment by mchipeta** [comment]
Thanks for your reply. From your experience, would it be relatively straightforward to add support for UWP? I'm considering doing the work and creating a pull request at some stage.

**Comment by ericsink** [comment]
I am currently using the sqlcipher builds managed by couchbase.  There is a sub module link to their repo in the tree.  They plan to support UWP, so sometime after they do, I will.

**Comment by mchipeta** [comment]
Many thanks. That'll be great! 👍 I'll wait patiently.

**Comment by ericsink** [comment]
FWIW, version 1.1.8 (just pushed to nuget) has a new package called `bundle_zetetic` which works with the official SQLCipher builds from Zetetic, and they do support UWP.

**Comment by ericsink** [comment]
Version 1.1.9 includes sqlcipher builds for UWP.
