### ISSUE TITLE
SQLitePCLRaw.bundle_green is not compatible with .NET Core 1.x

### ISSUE THREAD

**Issue by natemcmaster** [ericsink/SQLitePCL.raw#159]
It looks like recent changes that I suggested (oops) breaks SQLitePCLRaw.bundle_green for .NET Core 1.x. 

dotnet-restore fails:
```
error : Unable to resolve 'SQLitePCLRaw.bundle_green (>= 1.1.15)' for '.NETCoreApp,Version=v1.0'.
```

**What broke it** 
Moving $(PackageId).targets from `build/$(PackageId).targets` to `build/net35/$(PackageId).targets` in the e_libsqlite3 packages. 

Because NuGet interprets `build/$(PackageId).targets` to mean `build/any/$(PackageId).targets`, the package was compatible with "Any" framework. After the move, the package is only compatible with net35.

```
Supported Frameworks

sqlitepclraw.lib.e_sqlite3.osx.1.1.3.nupkg
Any,Version=v0.0

sqlitepclraw.lib.e_sqlite3.osx.1.1.5.nupkg
.NETFramework,Version=v3.5
```

**Ways to fix it**
Essentially, you want your package to remain compatible with "Any" framework. You can do this a few ways:

 - Move build/net35/\*.targets back to build/\*.targets. Add conditions to the .targets files to only run when the csproj/vbproj targets .NET Framework (not .NET Standard or .NET Core).
 - (my vote) add the magic "placeholder file" to the package. This is an empty file in the package named `lib/any/_._`.

**Comment by ericsink** [comment]
Trying to repro this.  In foo.csproj I have:

    <Project Sdk="Microsoft.NET.Sdk">
      <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp1.1</TargetFramework>
      </PropertyGroup>
      <ItemGroup>
        <PackageReference Include="SQLitePCLRaw.bundle_green" version="1.1.5" />
        <PackageReference Include="SQLitePCLRaw.ugly" version="1.1.5" />
      </ItemGroup>
    </Project>

In Program.cs, I have:

    using System;
    using SQLitePCL;
    using SQLitePCL.Ugly;

    namespace foo
    {
        class Program
        {
            static void Main(string[] args)
            {
                SQLitePCL.Batteries_V2.Init();
                using (var db = ugly.open(":memory:"))
                {
                    var s = db.query_scalar<string>("SELECT sqlite_version()");
                    Console.WriteLine("{0}", s);
                }
            }
        }
    }

The following commands work for me with the PackageReference lines set to either version 1.1.3 or 1.1.5:

    dotnet restore
    dotnet build
    dotnet run

`dotnet --version` tells me `1.0.3`

What am I doing differently?

**Comment by natemcmaster** [comment]
Weird. Nevermind, it appears to be a bug in pre-release bits of NuGet (2.0.0 stuff) and how it handles not being able to package feeds that don't exist. Closing for now as it seems the package works find when clearing my feeds.
