### ISSUE TITLE
SQLitePCLRaw.provider.sqlcipher.ios_unified.static is missing on Nuget

### ISSUE THREAD

**Issue by HEBOS** [ericsink/SQLitePCL.raw#163]
We can use cipher on Android, but not on iOS since "provider" library is missing on Nuget.

These two Nuget libraries are needed on Android for sqlcipher to work.
SQLitePCLRaw.lib.sqlcipher.android
SQLitePCLRaw.provider.sqlcipher.android

However, only "lib" library is found for iOS, and "provider" library is missing.
SQLitePCLRaw.lib.sqlcipher.ios_unified.static

Would you be so kind and upload iOS version of  sqlcipher "provider" library on Nuget?

**Comment by ericsink** [comment]
iOS is handled a bit differently.  The pkg you need is `SQLitePCLRaw.provider.internal.ios_unified.nuspec`.

You may wish to instead use `SQLitePCLRaw.bundle_sqlcipher`, which references the necessary dependencies on each platform.

**Comment by HEBOS** [comment]
Still not able to reference "SQLite3Provider_sqlcipher" by using this line:
SQLitePCL.raw.SetProvider(new SQLitePCL.SQLite3Provider_sqlcipher());

I'm using these packages:
SQLitePCLRaw.bundle_green
SQLitePCLRaw.bundle_sqlcipher
SQLitePCLRaw.core
SQLitePCLRaw.lib.sqlcipher.ios_unified.static
SQLitePCLRaw.provider.internal.ios_unified
SQLitePCLRaw.provider.sqlite3.ios_unified

**Comment by ericsink** [comment]
That's because iOS is handed a bit differently.

The line you need is:

    SQLitePCL.raw.SetProvider(new SQLitePCL.SQLite3Provider_internal());

which I got from `batteries_v2.cs`.

BTW, if you're using bundle_sqlcipher, you don't need to call `SetProvider`.  Instead, you should call `Batteries_V2.Init`.

Also, you should not have both bundle_sqlcipher and bundle_green.

**Comment by HEBOS** [comment]
But Xamarin.iOS and Xamarin.Android won't work without sql-net-pcl, but sql-net-pcl references bundle_green.
How do I remove bundle green, since NuGet Package Manager won't allow this.

**Comment by ericsink** [comment]
All your code that reference sqlite-net-pcl would need to be in a separate portable library.

Then, in your app projects, add bundle_sqlcipher, which should get substituted for bundle_green.

https://github.com/ericsink/SQLitePCL.raw/wiki/How-to-use-SQLCipher-with-SQLite-net

**Comment by HEBOS** [comment]
This solution is not good for me.
One that I came though, is not to use sqlite-net-pcl at all but SQLite.Net-PCL forked from praeclarum/sqlite-net.
It doesn't have dependencies such as bundle_green.
The only thing that I should do to make it work also on AndroidN is to add SQLite.Net.Platform.XamarinAndroidN package.
Cipher is now working on both Android and iOS.

**Comment by ericsink** [comment]
Sounds good.

The maintainer of sqlite-net-pcl decided to take a dependency on bundle_green, because it makes most use cases easier.  But it does make yours a bit more difficult.

Best regards.
