### ISSUE TITLE
SQLite R*Tree Module support (for geospatial systems)

### ISSUE THREAD

**Issue by oscarvarto** [ericsink/SQLitePCL.raw#165]
Hi!

Is there support for the SQLite R*Tree Module (https://sqlite.org/rtree.html) in SQLitePCL.raw?
My current use case requires mobile support for Xamarin (iOS, Android) and Windows UWP app.

If not, which steps would be needed to add support for this module?

**Comment by ericsink** [comment]
Yes, the e_sqlite3 builds which I include with SQLitePCL.raw bundles are built with `-DSQLITE_ENABLE_RTREE`.
