### ISSUE TITLE
Add finalizers or implement SafeHandle

### ISSUE THREAD

**Issue by bricelam** [ericsink/SQLitePCL.raw#166]
There are a few managed handles that, if leaked, result in a native leak:
* sqlite3
* sqlite3_backup
* sqlite3_blob
* sqlite3_stmt

Luckily, SQLite has it's own [memory management](https://sqlite.org/malloc.html) so the consequences are never severe.

This could be further mitigated, however, by adding finializers (or implementing `SafeHandle`) to the classes. This would allow the .NET garbage collector to free any native handles as soon as the managed wrappers go out of scope.

You're [original statement](https://github.com/aspnet/Microsoft.Data.Sqlite/issues/351#issuecomment-291551673) on the matter still stands, however: If an object implements `IDisposable`, you should always dispose it.

**Comment by bordoley** [comment]
I recall previous discussions, where it was agreed that in hindsight these low level wrappers should not of implemented IDisposable, but that it was too late to make that change. Finalizer support IMO really belongs in a higher level library. For instance, SQLitePCL.pretty goes to extreme lengths to guarantee proper disposal and finalization of sqlite resources.

**Comment by ericsink** [comment]
I need to take a fresh look at this issue.  If a change can be made without breaking anything, I would like to make it.  But I need to be certain.

The sqlite3 C API expects the caller to manually manage memory.  In keeping with its low-level philosophy, SQLitePCL.raw passes that expectation and responsibility upward to *its* caller.

So there are two ways to think of a possible change:

(1)  New philosophy:  Instead of the statement just above, try this:  "SQLitePCL.raw takes care of memory management such that its caller no longer needs to worry about it."

(2)  Safety net:  Keep the philosophy, but treat the symptoms.  SQLitePCL.raw still expects the caller to be responsible, but it has certain things (finalizers) to minimize the damage when the caller drops the ball.

Choice (1) has some appeal, but I'm not convinced that it *should* be done.  Every time I think of implementing (1), the first thing that comes to mind is that I would still want the lower layer to preserve the C API semantics.  So it seems like I would be changing SQLitePCL.raw to become something else, and then introducing a new even-lower-level layer to become what SQLitePCL.raw was before, etc...

In a more practical sense, I'm skeptical about whether (1) can be done reliably with just finalizers.  And `SafeHandle` would be a breaking change.

So any realistic change in the short term is probably choice (2).  But this choice makes me squirm a little bit as well.  Covering up (some of) the consequences of a developer's mistake usually just makes the mistake harder to find.

Maybe I'm seeing this as a bit more bleak than it needs to be.  Push-back or corrections are welcome.

**Comment by bricelam** [comment]
I'm fine implementing finalizers in my library to free these too. I just wanted to discuss it since adding them here would be convenient to all consumers.

**Comment by bricelam** [comment]
I agree we should go with option 2. My intention was only as a safety net. It also allow me to pass the buck along to consumers of my API: You must dispose `IDisposable` objects. But instead of every library having to add it's own safety net, there would already be one provided by SQLitePCL.raw.

**Comment by bricelam** [comment]
My motivation here is that if I'm writing a library and doing everything right (using `IDisposable` responsibly), I shouldn't have to treat the managed `sqlite3` objects as native resources and add my own finalizers to explicitly dispose them to implement best practices. `sqlite3` (and friends) are managed objects, and I should be able to assume they already implement .NET best practices with regards to freeing up unmanaged resources.

**Comment by ericsink** [comment]
That's a reasonable perspective.

But just to clarify (since I tend to let the details around finalizers and GC get swapped out of my brain's RAM onto a slow disk):  If the library is "doing everything right", what case requires finalizers?

**Comment by ericsink** [comment]
Also:

We're going to have an issue with ordering of the finalizer calls, right?  The `sqlite3` handle can't be cleaned up until its `sqlite3_stmt` handles are all done.

**Comment by bordoley** [comment]
@ericsink SQLitePCL.pretty handles the finalizing/disposing sqlite3 instances with open sqlite3_stmt handles via event handlers. It works quite well, but results in a non-threadsafe api. This isn't an issue for SQLitePCL.pretty which offers threadsafe via an async scheduling API, but I imagine would be a non-starter for raw.

**Comment by bordoley** [comment]
I'll express a preference for deprecating (in documentation) support for IDisposable (though leave the interface intact), and requiring the use raw.sqlite3_close() etc.

Afaik, most higher level libraries built on raw that I previously looked at manually close connections/stmts/etc. using the the actual sqlite apis and don't depend on dispose().

**Comment by bricelam** [comment]
> If the library is "doing everything right", what case requires finalizers?

If consumers of my library don't dispose my objects which own `sqlite3` handles.

> We're going to have an issue with ordering of the finalizer calls, right?

This is why `sqlite3_close_v2` was added.

**Comment by ericsink** [comment]
> This is why `sqlite3_close_v2` was added.

Darn.  I knew that.  But I forgot.  :-(

**Comment by bricelam** [comment]
There was also a comment about it not being available on the iOS (or was it OSX) version. So ...things might be getting a little messy.

**Comment by bricelam** [comment]
BTW, I'm deferring wholly to what you think is best here, @ericsink; I'm not pushing one way or the other. I just wanted to have the conversation one last time.

**Comment by ericsink** [comment]
Looks like all iOS versions >= 8.2 contain a SQLite new enough for `sqlite3_close_v2`.  This issue is fading away.

**Comment by ericsink** [comment]
> I just wanted to have the conversation one last time.

No worries here.  I see this kind of conversation as an opportunity to (1) learn, and (2) find the best answer.  I appreciate you bringing it up again.

**Comment by bricelam** [comment]
> most higher level libraries built on raw that I previously looked at manually close connections/stmts/etc. using the the actual sqlite apis and don't depend on dispose().

Interesting. Given that SQLite will eventually clean these things up anyway, I think deprecating IDisposable is also reasonable albeit a little unorthodox for .NET.

**Comment by ericsink** [comment]
Just to be clear, the `IDisposable` issue here is not related to the issue of whether there should be a finalizer or not, right?  You guys are just suggesting that these objects should perhaps not offer `Dispose()` as an alternate spelling for `sqlite3_close` (et al)?

**Comment by ericsink** [comment]
Current thinking:  Use `SafeHandle`, and use the opportunity to make the jump to 2.0.  I've got other stuff that has been waiting for a compatibility-breaking change, such as removing support for Windows Phone 8.0.

**Comment by bricelam** [comment]
I dig it. While I agree with @bordoley that libraries need to be very aware of these native wrappers and always dispose/close/finalize/free them (or expose a way of doing that) it is also good to take advantage of the garbage collector to free any that slip through the cracks sooner rather than waiting for SQLite to do it later.

**Comment by bricelam** [comment]
FYI, in aspnet/Microsoft.Data.Sqlite#386 I've started using `raw.sqlite3_close_v2()` explicitly instead of `sqlite3.Dispose()`, and added finalizers to explicitly free these objects whenever my library's objects go undisposed.

**Comment by ericsink** [comment]
Which answers a question I was going to ask you:  Are you okay with restricting to iOS 8.2 and above?  (Looks like yes.)

**Comment by ericsink** [comment]
@bricelam Could you take a look at commit 8e52dad?  I haven't had to do finalizers in quite a while, so I did some remedial study on the topic.  I'd love to have another pair of eyes reviewing the code.  :-)  Thanks.

**Comment by bricelam** [comment]
LGTM

**Comment by ericsink** [comment]
Fixed in version 1.1.8, which has been pushed to nuget.org.
