### ISSUE TITLE
Azure mobile app with SQLitePCLRaw.bundle_sqlcipher

### ISSUE THREAD

**Issue by kitsela** [ericsink/SQLitePCL.raw#168]
Hello,
I am working on the Xamarin.iOS project with the azure mobile app.
In the project, I use "azure-mobile-apps-net-client" with version 3.0.3
I have tried to add encryption to the SQLite. 
I loaded the source code of Microsoft.WindowsAzure.MobileServices.SQLiteStore from github repository ([https://github.com/Azure/azure-mobile-apps-net-client/tree/3.0.3/src/Microsoft.WindowsAzure.MobileServices.SQLiteStore](https://github.com/Azure/azure-mobile-apps-net-client/tree/3.0.3/src/Microsoft.WindowsAzure.MobileServices.SQLiteStore))
After that I removed `SQLitePCLRaw.bundle_green` from library and added `SQLitePCLRaw.bundle_sqlchipher` (1.1.7).
I updated `SQLitePCLRaw.core` to version 1.1.7.
I rebuilt WindowsAzure.MobileServices.SQLiteStore with those libraries.
After that, I changed my Xamarin.iOS solution by replacing `WindowsAzure.MobileServices.SQLiteStore` to custom `SQLiteStore` (which contains `bundle_sqlchipher`).
Also, In the Xamarin.iOS solution I added following libraries
```
SQLitePCLRaw.core
SQLitePCLRaw.bundle_sqlchipher
SQLitePCLRaw.lib.sqlcipher.ios_unified.static
SQLitePCLRaw.provider.internal.ios_unified
```
My solution works fine. But DB isn't encrypted.
Seems I missed some details.
I suppose I should make a request similar to: 

`var t = conn.Query<int>("PRAGMA key=xzy1921");`

But as I can see the MobileServiceSQLiteStore class contains the connection to DB declared in the following way 

`private sqlite3 connection;`

You can see it here:
(https://github.com/Azure/azure-mobile-apps-net-client/blob/3.0.3/src/Microsoft.WindowsAzure.MobileServices.SQLiteStore/MobileServiceSQLiteStore.cs)

And this connection doesn't contain a method "query".

Could you please give me a few more details how can I add encryption to the azure mobile app. 

Thanks.

**Comment by ericsink** [comment]
If you have access to the `sqlite3` object, you can use something like: `SQLitePCL.raw.sqlite3_exec(connection, "PRAGMA key=whatever")`

**Comment by kitsela** [comment]
Eric thank you so much.
Now it works.
One more question I would like to ask you. When I  use your library "SQLitePCLRaw.bundle_sqlcipher" should I buy any license for it?  Or this library based on the free cipher-library edition.

**Comment by ericsink** [comment]
These SQLCipher builds are based on the open source code.  It is my understanding that a paid license is not necessary, but I like to recommend purchasing one (from Zetetic).

**Comment by kitsela** [comment]
Thank you one more time.
Your answers were really helpful.
