### ISSUE TITLE
Problem with bundle_green for Mac

### ISSUE THREAD

**Issue by ericsink** [ericsink/SQLitePCL.raw#170]
See praeclarum/sqlite-net#593

I have reproduced this.  Fix coming soon I hope.

**Comment by corliss** [comment]
Hi, is there a workaround for this? 

I'm using 1.1.8. Have tried calling
`SQLitePCL.raw.SetProvider(new SQLitePCL.SQLite3Provider_e_sqlite3());` 
instead of 
`SQLitePCL.Batteries_V2.Init();` 
but that still throws 
`System.DllNotFoundException has been thrown: e_sqlite3`

Thanks.

**Comment by ericsink** [comment]
No, sorry, no workaround that I know of.  But I'll try to get the fix done ASAP.

**Comment by corliss** [comment]
Thanks, I'd really appreciate that!

**Comment by ericsink** [comment]
There's a new 1.1.9 prerelease of (just) the SQLitePCLRaw.lib.e_sqlite3.osx package.  This contains a fix that gets the dylib copied into the output directory.

However, something else is wrong, and I'm not sure what it is.  At runtime, it still can't load or find the dylib.

That same dylib and packaging works fine under .NET Core for Mac.

I haven't done much Mac stuff in a while, but I have vague recollections about path problems for loading dylibs.

@praeclarum Any tips here?

**Comment by corliss** [comment]
I also remember dylibs being tricky to set up. Did a web search an came up with a couple of options.

1) This [article](https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/UsingDynamicLibraries.html) has an overview of what is needed. I suspect you'll need to set one of the environment variables before attempting to load the dylib. `DYLD_LIBRARY_PATH` may be a good choice. I don't recall whether relative paths work.

2) On the other hand this [StackOverflow post](https://stackoverflow.com/a/15106738) states that setting environment variables isn't the best way, and then describes how to set `LD_RUNPATH_SEARCH_PATHS` for the application. However, the instructions are for a native Xcode app, not a managed Xamarin app; I don't know what the equivalent is in the latter case.

**Comment by corliss** [comment]
Hi Eric, 

I also came across this [Xamarin Forums](https://forums.xamarin.com/discussion/37935/native-dylib) thread on the subject. The last respondent included a python script.

Do you know of any workarounds (e.g. setting environment variables) that might work just on my machine in the meantime?

Cheers

**Comment by ericsink** [comment]
Sorry for the delay on this.  I'll try to give it another look tomorrow.

For now, I'm wondering if there are any clues in this SO post:

https://stackoverflow.com/questions/12834141/setting-path-of-the-native-library-for-dllimport-on-mono-for-mac/12840932#12840932

**Comment by ericsink** [comment]
@corliss OK, here's another attempt at a fix.  This one works for me:

SQLitePCLRaw.lib.e_sqlite3.osx.1.1.9-pre20170831090547

**Comment by corliss** [comment]
Eric, thanks - that worked!
For my own ediification, what is the right way to register this libs?

**Comment by ericsink** [comment]
In the msbuild targets file, what I needed was to change the tag to NativeReference.

The problem was that the dylib was being copied into the build directory, but not into the bundle directory.  The NativeReference tag apparently handles that.

I spent far too much time thinking the problem was related to Mono's implementation of DllImport, but that was apparently a red herring.

**Comment by CartBlanche** [comment]
@ericsink So when searching for the right Nuget on Mac, what is the correct name to be able to grab these changes, or is it only available if you build from the repo??

**Comment by ericsink** [comment]
SQLitePCLRaw.lib.e_sqlite3.osx.1.1.9-pre20170831090547

The pkg name is SQLitePCLRaw.lib.e_sqlite3.osx, the version number is 1.1.9-pre20170831090547, the specific pkg on nuget.org is

https://www.nuget.org/packages/SQLitePCLRaw.lib.e_sqlite3.osx/1.1.9-pre20170831090547

**Comment by CartBlanche** [comment]
Ooops only just seen this. Thanks that prerelease build works for me too!

**Comment by ericsink** [comment]
1.1.9 has been released, so I'm closing this issue

**Comment by praeclarum** [comment]
Yay!!!
