### ISSUE TITLE
Enable FTS5 in e_sqlite3 builds

### ISSUE THREAD

**Issue by MHHenriksen** [ericsink/SQLitePCL.raw#171]
https://sqlite.org/compile.html#enable_fts5

After the switch in https://github.com/aspnet/Microsoft.Data.Sqlite/issues/21 I was sad to discover that we lost support for fts5. We could always make our own build that includes this, but I'd wager that fts5 is used by enough apps to warrant inclusion in your official build. 

Of course, if you have a reason not to, I'll respect that.

**Comment by ericsink** [comment]
I plan to do this, unless I uncover a reason not to.  :-)

**Comment by ericsink** [comment]
SQLitePCL.raw pre-release version 1.1.10-pre20180223200113 has been pushed to nuget.  As of this release, FTS5 should be available in all e_sqlite3 builds.  Testing feedback appreciated.

**Comment by MHHenriksen** [comment]
Thanks! I'll give it a spin.

**Comment by ericsink** [comment]
Version 1.1.10 (now on nuget.org) has FTS5 in the e_sqlite3 builds.
