### ISSUE TITLE
Allow specifying SQLITE_DETERMINISTIC during sqlite3_create_function

### ISSUE THREAD

**Issue by bricelam** [ericsink/SQLitePCL.raw#174]
According to [the docs](https://www.sqlite.org/c3ref/create_function.html)...

> The SQLite query planner is able to perform additional optimizations on deterministic functions, so use of the SQLITE_DETERMINISTIC flag is recommended where possible.

**Comment by ericsink** [comment]
Hmmm.  It looks like when I originally did `sqlite3_create_function`, I kinda messed it up.  The argument necessary is not exposed through ISQLite3Provider.

I still plan to fix this issue, but I'll need to think about the best way to do it without causing breakage.  If you have a specific preference or suggestion, feel free...

**Comment by bricelam** [comment]
Oh no rush. I just noticed it when implementing UDFs in Microsoft.Data.Sqlite. I imagined either an overload with a `bool` or, in case more flags are added in the future, an `int` that ignores any string encoding flags since those are automatically handled by SQLitePCL.raw.

**Comment by ericsink** [comment]
SQLitePCL.raw pre-release version 1.1.10-pre20180223200113 has been pushed to nuget.  The support for SQLITE_DETERMINISTIC is included.

**Comment by ericsink** [comment]
Fixed in 1.1.10, now on nuget.org
