### ISSUE TITLE
ARM Sqlite DLL is missing in deployment folder - workaround

### ISSUE THREAD

**Issue by glegleme** [ericsink/SQLitePCL.raw#175]
DotnetCore2  sample application deployed to Windows 10 IOT (RaspberryPi 3) produces following error:

System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.DllNotFoundException: Unable to load DLL 'e_sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

The workaround with referencing winsqlite.dll does not work (application is self contained and has no access to GAC). However, the following workaround with copying does work:
-find winsqlite3.dll (It is located in WINDOWS/System32) on Raspberry Pi
-copy this dll into publish destination for .net core project 
-rename it to: e_sqlite3.dll

Afterwards, it all works like a charm. (Complete starter Asp.Mvc application with identity management stored in SqLite db). Is it possible to include ARM version of e_sqlite3.dll in one of nuget packages?

**Comment by ericsink** [comment]
e_sqlite3 ARM for .NET Core was added in 1.1.8 and seems to be working fine.

What version of SQLitePCL.raw are you using?

**Comment by glegleme** [comment]
My last attempt was with:

<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="2.0.0" />
 <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="1.1.8" />

I have also tried out most other packages from nuget.

**Comment by ericsink** [comment]
What happens when you run the following commands?

    mkdir t1
    cd t1
    dotnet new console
    dotnet add package SQLitePCLRaw.bundle_e_sqlite3
    dotnet publish -r win10-arm
    ls -l bin/Debug/netcoreapp2.0/win10-arm/publish/e*

I get:

    -rwxrwxrwx 1 root root 693760 Aug 23 12:33 bin/Debug/netcoreapp2.0/win10-arm/publish/e_sqlite3.dll

**Comment by glegleme** [comment]
The key seems to be
`dotnet publish -r win10-arm`
I have per example on [https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md](url)
used
`dotnet publish -r win-arm`

Funny is that other dependencies (SQLitePCLRaw.batteries, core and provider) are included in win-arm versus win10-arm. Only e_sqlite3.dll is missing.

Thanks for solving the issue.

**Comment by ericsink** [comment]
Hmmm.  Interesting.  I can't say for certain that I'm using the right RID.  It has been hard to get a definitive answer.

The main difference between e_sqlite3.dll and the others you mentioned is that e_sqlite3.dll is native code, not a CLR assembly.

Anyway, thanks for the info.

**Comment by bricelam** [comment]
@glegleme Since you're deploying to Windows 10, you should be using `win10-arm` during publish.

@ericsink If you're compiling against the [Windows 8 API Sets](https://msdn.microsoft.com/en-us/library/windows/desktop/dn505783.aspx) your current use of `win8-arm` is correct. If you never link directly to `MinCore.lib` or `MinCore_Downlevel.lib`, you probably even get away with `win7-arm`--even tough Windows 7 never ran on ARM. 😉

**Comment by bricelam** [comment]
Oh, never mind. `win7-arm` isn't defined` ...but`win-arm` is. It might make sense to update it to `win-arm`.

**Comment by ericsink** [comment]
Fixed in 1.1.10, which is now on nuget.org
