### ISSUE TITLE
FreeBSD support possible?

### ISSUE THREAD

**Issue by sec** [ericsink/SQLitePCL.raw#176]
Hi,
Would it be possible to have FreeBSD support added? Or what is needed to make that happen, I could try to add it myself, just need some instructions where/how to start with it?

**Comment by ericsink** [comment]
What kind of support?

Mono?  or .NET Core?

Using a sqlite provided by the OS?  Or bundle an e_sqlite3 build for FreeBSD?

**Comment by sec** [comment]
.NET Core (need e_sqlite3 build for FreeBSD)
sqlite3 is not in base for FreeBSD (but can be easily installed from pkg/ports).

**Comment by ericsink** [comment]
What is the status of .NET Core on FreeBSD?  Not officially supported by Microsoft, I assume...

This is probably straightforward, but I wonder about my ability to keep it maintained and tested over time.

**Comment by sec** [comment]
Well.. It's not officially supported (at least for now), but coreclr/corefx (native parts) are building under FreeBSD. Managed can be built under Windows - so the support is there, driven by community. .NET cli is not building at the moment (I was able to build 1.x version in past, at the moment trying to get 2.0.0 build to compile), but apps can be run using coreclr (there are some "hard" corners still, but WIP). Right now I'm trying to run some basic .net core asp.net app and got blocked by not having e_sqlite3 build for FreeBSD - that's why I'm asking - I can build/compile this myself (or help testing this on FreeBSD), just need some howto start with this :)

**Comment by sec** [comment]
Just a little add - copying libsqlite3.so (tested version 3.20.0 from pkg repository) as e_sqlite3.so into runtime directory "made it work"

**Comment by ericsink** [comment]
Another option that should work:

Instead of using one of my bundle packages (which currently does not include an e_sqlite3 build for FreeBSD), you could just use SQLitePCLRaw.core (the base library) and then also add SQLitePCLRaw.provider.sqlite3.netstandard11, and then add this line of code:

    SQLitePCL.raw.SetProvider(new SQLitePCL.SQLite3Provider_sqlite3());

Which should cause the sqlite library from the FreeBSD package to be found.  I think.

**Comment by ericsink** [comment]
Closing old/stale issue.
