### ISSUE TITLE
I just need to know if VCRedists are needed...

### ISSUE THREAD

**Issue by krippz** [ericsink/SQLitePCL.raw#177]
Hi and greetings!
I was wondering about dependencies. Do my target systems need to have the VisualC++ 2012 Redist installed in order for them to use SQLitePCLRaw.core? My target systems are Windows Server 2008R2 and up to Windows Server 2016.

The reason behind me asking is if I read from the readme.md and I got a bit confused. 

"On my build machine, I have Visual Studio 2012 and Visual Studio 2013 (update 2) and Visual Studio 2015 and Xamarin Android + iOS and
the relevant Android SDK(s)."

and further on: 

"(1) We need something that can call the C code. For the Xamarin implementations this is DllImport (aka P/Invoke). For Windows Phone 8, this is a C++ wrapper. For the others, it is both. In either case, this presents an extremely low-level API. C pointers become System.IntPtr. Strings are not actually .NET strings, but rather, are in utf-8 encoding, represented in C# as either an IntPtr or a byte[]."

To my understanding there is no dependency on any of the VCRedists under Windows Server OS, but I'd like to confirm this :)

Thank you in advance!
/cheers

**Comment by ericsink** [comment]
(FWIW, and to help with the confusion, neither of the snippets you quoted are related to the question of whether VCRedists are needed or not.)

I assume you are talking about using SQLitePCL.raw with its e_sqlite3 library.

No, you should not need to install VCRedists if your target is Windows Server.  Whenever possible, e_sqlite3 is built with the C runtime library statically linked in.  In one or two cases, this is not supported by the toolchain, but those cases do not involve Windows Server.

**Comment by krippz** [comment]
Yes you assumed correctly, I meant the SQLitePCL.raw bits 😀
Thank you very much for the clarification! 
/cheers
