### ISSUE TITLE
How to use in a Xamarin.ios project

### ISSUE THREAD

**Issue by mawarnes** [ericsink/SQLitePCL.raw#178]
How can I use the sqlcipher library in a shared project?
I'm not sure which references to add to my xamarin.ios project?

could you give me a heads up maybe, many thanks

**Comment by ericsink** [comment]
Part of the answer to this question is to add SQLitePCLRaw.bundle_sqlcipher.

The rest of the answer depends on what sqlite wrapper you are using?  sqlite-net?  Microsoft.Data.Sqlite?
