### ISSUE TITLE
Cannot make SQLitePCLRaw.bundle_sqlcipher work with EF Core 2

### ISSUE THREAD

**Issue by srollinet** [ericsink/SQLitePCL.raw#179]
Hi,

I try to make SQLitePCLRaw.bundle_sqlcipher (1.1.8) work with ASP.Net Core 2 / EF Core 2 but it seems the DB is never encrypted. Am I missing something?

I made a minimal repo here. [SqliteCipherTest.zip](https://github.com/ericsink/SQLitePCL.raw/files/1304649/SqliteCipherTest.zip)

```
        [Fact]
        public void Test1()
        {
            var encryptedConnexion = new SqliteConnection("Data Source=test.db;");
            encryptedConnexion.Open();
            var command = encryptedConnexion.CreateCommand();
            command.CommandText = "SELECT quote($password);";
            command.Parameters.AddWithValue("$password", "password1");
            var quotedPassword = (string)command.ExecuteScalar();

            command.CommandText = "PRAGMA key = " + quotedPassword;
            command.Parameters.Clear();
            command.ExecuteNonQuery();

            encryptedConnexion.Execute("CREATE TABLE IF NOT EXISTS test (value TEXT)");
			encryptedConnexion.Execute("DELETE FROM test");
            encryptedConnexion.Execute("INSERT INTO test VALUES (@val)", new {val = "myVal"});

            var vals = encryptedConnexion.Query<string>("SELECT * FROM test").ToList();
            Assert.Equal(1, vals.Count);
            Assert.Equal("myVal", vals.Single());

            var connection = new SqliteConnection("Data Source=test.db;");
            connection.Open();

            //Should fail
            var vals2 = encryptedConnexion.Query<string>("SELECT * FROM test").ToList();
            Assert.NotEqual(1, vals2.Count);
        }
```

Normally, the second connexion should not be able to read the file as I don't set the PRAGMA key. So I suppose the DB is not encrypted.

In my example, I use Dapper for more convenience, but the result is exactly the same when using only EF

Thanks for your help!

**Comment by ericsink** [comment]
1.  You should take your dependency on Microsoft.EntityFrameworkCore.Sqlite.Core, not Microsoft.EntityFrameworkCore.Sqlite.  Note the extra .Core at the end.  This is the form of that package which is suitable for use with bundle_sqlcipher.

2.  You should dispose the encrypted connection before opening the other one.

With those two changes, your test "works" for me, in the sense that the "should fail" query throws an exception because it cannot read the db.  And using the sqlite3 command line shell app to look at the resulting test.db file shows it to be unreadable.

**Comment by srollinet** [comment]
Thanks a lot for your help!

In my full project, I was using Microsoft.EntityFrameworkCore.Sqlite.Core, but I was also using the new meta-package Microsoft.AspNetCore.All, which includes Microsoft.EntityFrameworkCore.Sqlite.

So the solution is to remove the meta-package and add all the packages individually.
