### ISSUE TITLE
Add sqlite3_create_deterministic_function?

### ISSUE THREAD

**Issue by bordoley** [ericsink/SQLitePCL.raw#18]
What do you think of adding api to create deterministic scalar and aggregate functions. Seem useful for performance reasons? I can put together a PR if so.

https://sqlite.org/c3ref/create_function.html
https://sqlite.org/c3ref/c_deterministic.html

**Comment by bordoley** [comment]
Would you take a PR for this? What API would you want?

**Comment by ericsink** [comment]
If you have a user need (somebody using your library to write an app, for example) for this API, then let's talk about it.  Otherwise, let's not.  I'm trying to make my to-do list, shorter, not longer.

**Comment by ericsink** [comment]
This might just be the ability to pass that DETERMINISTIC flag into sqlite3_create_function_v2.
