### ISSUE TITLE
Inconsist behavior(throw Exception) when a .net framework app reference a net standard library

### ISSUE THREAD

**Issue by ares128** [ericsink/SQLitePCL.raw#180]
https://github.com/ares128/sqlite3bug
 
check bug here

the sqlite3 database is in a .net standard library (2.0)

when the library is referenced by a .netcoreapp ,it will be ok!
when the library is referenced by a .net framework app, it will throw a Exception:

System.TypeInitializationException: “Microsoft.Data.Sqlite.SqliteConnection”的类型初始值设定项引发异常。 ---> System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.DllNotFoundException: 无法加载 DLL“e_sqlite3”: 找不到指定的模?椤?(异常来自 HRESULT:0x8007007E)。
   在 SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_libversion_number()
   在 SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   在 System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Microsoft.Data.Sqlite.Utilities.BundleInitializer.Initialize()
   在 Microsoft.Data.Sqlite.SqliteConnection..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
   在 Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.CreateDbConnection()
   在 Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   在 Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   在 Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open(Boolean errorsExpected)
   在 Microsoft.EntityFrameworkCore.Storage.Internal.SqliteDatabaseCreator.Exists()
   在 Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()

please help me , or is there a workaround

**Comment by ericsink** [comment]
SQLitePCL.raw uses the bait-and-switch technique.  When you reference it from a portable library, you also need to reference it from your main app project.

**Comment by ares128** [comment]
> SQLitePCL.raw uses the bait-and-switch technique. When you reference it from a portable library, you also need to reference it from your main app project.

it is working, thx!
