### ISSUE TITLE
e_sqlite3.dll doesn't get loaded correctly

### ISSUE THREAD

**Issue by jp2masa** [ericsink/SQLitePCL.raw#181]
I'm working on a VS extension which uses Microsoft.Data.SQLite. I was using version 2.0.0, which depends on SQLitePCL.raw and I had to downgrade it to version 1.1.1 because e_sqlite3.dll doesn't get loaded correctly.

<details>
<summary>Stack Trace</summary>

```
An error occurred: System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.DllNotFoundException: Unable to load DLL 'e_sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_libversion_number()
   at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
   at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
   at SQLitePCL.Batteries_V2.Init()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Data.Sqlite.Utilities.BundleInitializer.Initialize()
   at Microsoft.Data.Sqlite.SqliteConnection..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
```
</details>
<br />
When debugging the extension, to find the cause of the issue, I looked at the Modules window and found out that the e_sqlite3 provider was being loaded from a Roslyn VS extension folder. In that folder there are two versions of e_sqlite3.dll, in subdirectories (x86 and x64). I tried copying the x86 version to the Roslyn VS extension folder and I didn't get the error, because DllImport found the assembly in the same folder as the one where the provider assembly is located.

Why isn't e_sqlite3.dll being loaded? Is it supposed to be loaded from the x86 folder?

Any help would be appreciated.

**Comment by ericsink** [comment]
I'm not sure what's going on here.  It may have something to do with the fact that your situation is a VS extension, but I am not at all familiar with that context.

I'm guessing that a VS extension is a .NET Framework project?

Yes, for .NET Framework, the init code for SQLitePCL.raw tries to load the DLL from x86 or x64, depending on the architecture detected at runtime.  But its ability to find those directories could be an issue when coding something like a VS extension.

**Comment by jp2masa** [comment]
Yes, a VS extension is a .NET Framework project.
Where does SQLitePCL.raw look for the x86 and x64 folders?

**Comment by ericsink** [comment]
Take a look at the code in sqlite3_pinvoke.cs.

More specifically, try this:

Before doing anything else with SQLitePCL.raw, set `SQLitePCL.Settings.BaseDirectoryForDynamicLoadNativeLibrary` to the full path of the directory where x86 and x64 ended up in your situation.

**Comment by danki** [comment]
I started to get similar issues as well.

Am using Xamarin for Android and only "error" i see, or correctly said, last log is see is this:
`11-29 12:46:26.215 D/Mono: DllImport searching in: 'e_sqlite3' ('libe_sqlite3.so').
11-29 12:46:26.215 D/Mono: Searching for 'sqlite3_errmsg'.`

After those 2 lines i get no response in app at all, it just hangs /freezes. Only when i hit in Debugger Pause-button manually, i get popup for selecting SQLite.cs cause it cannot be found.

Have no idea where it is located, is at least not any of classes in my project so i gotta be something internal.

PS. Generally I'm no .NET dev and have no clue of Xamarin  and how it does it thing. So if additional info is needed , it would be helpful if given step-by-step instructions. I got this project only cause the base code has Android Java similarities, anything else... im lost!

**Comment by cjlotz** [comment]
Not sure whether this is related, but we've run into issues when upgrading from v1.1.8 to v1.1.9.  Our scenario was when running our set of unit tests using Visual Studio for Mac that make use of sqlite and the `SQLitePCLRaw.bundle_green` package.  The test project targets .NET 4.5.  For v1.1.8 the `libe_sqlite3.dylib` was copied to the `bin\Debug` folder when compiling the test project.  However, for v1.1.9 the `libe_sqlite3.dylib` is not copied and all our db tests then start failing.  This is only an issue on the Mac for us.  On Windows the `e_sqlite3.dll` is loaded successfully from the `x86/x64` folders.  Downgrading back to v1.1.8 solves this issue for us.

**Comment by ErikEJ** [comment]
When calling SQLitePCL.Settings.BaseDirectoryForDynamicLoadNativeLibrary I am getting:

```
System.TypeLoadException: Could not load type 'SQLitePCL.Settings' from assembly 'SQLitePCLRaw.provider.e_sqlite3, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9c301db686d0bd12'.
   at ReverseEngineer20.EfCoreReverseEngineer.SetFolder()
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\Code\SqlCeToolbox\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 55
```
I am using these SQLite packages

```
  <package id="SQLitePCLRaw.bundle_green" version="1.1.8" targetFramework="net461" />
  <package id="SQLitePCLRaw.core" version="1.1.8" targetFramework="net461" />
  <package id="SQLitePCLRaw.lib.e_sqlite3.linux" version="1.1.8" targetFramework="net461" />
  <package id="SQLitePCLRaw.lib.e_sqlite3.osx" version="1.1.8" targetFramework="net461" />
  <package id="SQLitePCLRaw.lib.e_sqlite3.v110_xp" version="1.1.8" targetFramework="net461" />
  <package id="SQLitePCLRaw.provider.e_sqlite3.net45" version="1.1.8" targetFramework="net461" />

```

**Comment by jp2masa** [comment]
After investigating the problem and asking for help on the roslyn gitter chat, there are 2 problems:

1. This is the worse problem: assembly version is 1.0.0.0 for all versions (at least for 1.1.2, used by roslyn, 1.1.7, used by the VS extension I'm working on, and 1.1.9). This doesn't allow me to add binding redirects for example, which would easily resolve this issue.
2. `AppDomain.CurrentDomain.BaseDirectory` is unreliable as an assembly search path (#134). In the scenario of a VS extension, this path is the directory where `devenv.exe` is located, so it fails to load.

@ericsink could you please release a new version with the correct assembly version? and ensure that the assembly version is bumped on every release.

**Comment by ericsink** [comment]
@jp2masa I'll need to do some investigation before I can commit to the change you have requested.  Basically, when I agreed to add strong names, I understood that doing so would be far less painful if the assembly version did not regularly change.  I don't recall all of the details, nor can I claim to be an expert on strong names or binding redirects.  Nonetheless, that is the history behind the NEVER CHANGE THIS comment.

**Comment by ErikEJ** [comment]
@jp2masa FYI:I ended up using System.Data.SQLite.dll instead

**Comment by ericsink** [comment]
Ouch!  That means there's something here I need to fix.  Nothing wrong with System.Data.SQLite, but if you tried to use SQLitePCL.raw and then didn't, I want to find a way to clear the obstacles.

**Comment by ErikEJ** [comment]
I think proper assembly versioning would fix it for me: 

>> assembly version is 1.0.0.0 for all versions (at least for 1.1.2, used by roslyn, 1.1.7, used by the VS extension I'm working on, and 1.1.9).

That would allow me to reference a specific version, and then I could call BaseDirectoryForDynamicLoadLibrary - I believe that would also then work for @jp2masa

**Comment by ErikEJ** [comment]
Also, for troubleshooting, please add an InformationalVersion with the Nuget package version to the build.

**Comment by ErikEJ** [comment]
FYI: My reasoning here: https://github.com/aspnet/EntityFrameworkCore/issues/10596#issuecomment-353952643

**Comment by jp2masa** [comment]
I think that I wouldn't even need to use `BaseDirectoryForDynamicLoadLibrary`, adding a binding redirect would be enough, as e_sqlite3.dll loading has been improved since 1.1.2.

**Comment by ErikEJ** [comment]
@jp2masa I think adding binding redirects for DLLs used by VS could be dangerous, and you would have to add them programmatically

**Comment by jp2masa** [comment]
I asked for help on the roslyn gitter chat and they recommended me to do that. There's an attribute (`ProvideBindingRedirect`) for that.

**Comment by jp2masa** [comment]
@ericsink For compatibility purposes, it makes sense to strong-name sign the assemblies of this project, although [it is not recommended to do so](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md#1-microsoft-strong-names-their-assemblies-should-i), except on specific cases.
The assembly version is part of the assembly identity. So if a program is going to load the assembly, it thinks that all released versions of SQLite.PCL.raw contain the same assemblies (same name, same version, same strong-name signing). One of the main reasons to strong-name sign assemblies is to allow binding redirects, which surely won't work if the assembly version is always the same, because it redirects old assemblies to new ones, based on their version. The problems associated with strong-name signing are described [here](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md#2-i-really-really-need-to-strong-name-what-kinds-of-issues-will-i-run-into), which clearly states that the assembly version can cause problems, as assemblies which reference it need the *exact* version, unless there's a binding redirect.
I read the discussions about strong-name signing in this repo and it's really needed, but assembly versions *must* be bumped (not related to strong-name signing or not) when the content of the assembly changes, which may cause problems related to binding redirects, but at least that can be resolved, as opposed to my situation.

**Comment by ericsink** [comment]
As for the main issue here of updating the assembly version, you guys are moving me toward convinced, but I remain a little concerned, since my posture toward breaking changes is extremely conservative.

@bricelam May I assume that you guys would expect no difficulties if I began updating the assembly version number with each release?

**Comment by bricelam** [comment]
We're good. Binding redirects are **a lot** less painful these days thanks to MSBuild and NuGet.

**Comment by ericsink** [comment]
SQLitePCL.raw pre-release version 1.1.10-pre20180223200113 has been pushed to nuget.  From here forward, SQLitePCL.raw assemblies will include a properly updated AssemblyVersion.  Testing feedback would be appreciated.

**Comment by ericsink** [comment]
Version 1.1.10 is now on nuget.org

**Comment by ErikEJ** [comment]
@ericsink Finally I am able to confirm that using the following package works as expected in my Visual Studio extension:

     <package id="Microsoft.Data.Sqlite" version="2.1.0-rc1-final" targetFramework="net461" />
     <package id="SQLitePCLRaw.bundle_green" version="1.1.10" targetFramework="net461" />
