### ISSUE TITLE
DllNotFoundException when using bundle_sqlchiper

### ISSUE THREAD

**Issue by wes566** [ericsink/SQLitePCL.raw#182]
Repro Steps:
1. Create Xamarin.Mac app (I'm using VS for Mac 7.2.2 Build 11)
2. Install [bundle_sqlcipher 1.1.9 nuget](https://www.nuget.org/packages/SQLitePCLRaw.bundle_sqlcipher/1.1.9)
3. Call `SQLitePCL.Batteries_V2.Init();` in AppDelegate.DidFinishLaunching

It throws a DllNotFoundException "sqlcipher" on the `Init()` line.

I created a [repro repo here](https://github.com/wes566/SqlCipherMacRepro) so you can just clone that and try it yourself.

**Comment by wes566** [comment]
@ericsink this seems similar to #170 but since I'm using 1.1.9 nuget that should be fixed right?  I did verify that changing to bundle_green works correctly, so maybe it's not same issue as #170.

Is there an additional step needed for sqlcipher that I'm missing?

**Comment by ericsink** [comment]
I'll take a look at this, probably early next week, and get back to you.  The fix for #170 was specific to bundle_green.  It's quite possible that something about Xamarin.Mac and sqlcipher is broken.

**Comment by wes566** [comment]
Hi @ericsink any chance you were able to look into this?  Thanks!

**Comment by ericsink** [comment]
Oh dear, my apologies.  Some things slipped my mind during the holiday.

I didn't finish the investigation, but I did reproduce the problem.  I still need to figure out *why*.

Thanks for your patience.

**Comment by ericsink** [comment]
Try updating the SQLitePCLRaw.lib.sqlcipher.osx package to version 1.1.10-pre20171128095033

**Comment by wes566** [comment]
Tested it out in the my repro project and in another project that is using [splite-net](https://www.nuget.org/packages/sqlite-net-sqlcipher) (just added the [pre-release nuget package for SQLitePCLRaw.lib.sqlcipher.oxs](https://www.nuget.org/packages/SQLitePCLRaw.lib.sqlcipher.osx/1.1.10-pre20171128095033) to the top-level app) and it works great!

Thank you @ericsink!  Oskee Wow-Wow

**Comment by ericsink** [comment]
> Oskee Wow-Wow

Illini fan?  ;-)

**Comment by wes566** [comment]
Alum/fan/Illinois native... yes :)

**Comment by ericsink** [comment]
Fixed in 1.1.10, which is now on nuget.org
