### ISSUE TITLE
adding item to database does not indicate state of EntityState.Added

### ISSUE THREAD

**Issue by mister-giga** [ericsink/SQLitePCL.raw#185]
I am creating MacOS app with Xamarin.Forms. 

I have only WordDB simple class
`public class WordDB`
    `{`
       `    public int Id { get; set; }`
      `     public int OnlineId { get; set; }`
       `    public string Word { get; set; }`
       `    public string Definition { get; set; }`
   ` }`

I have another async method to add new word to sqlite database.

`var tracking = await _databaseContext.Words.AddAsync(word);`
`var res = await _databaseContext.SaveChangesAsync();`
`var isAdded = tracking.State == EntityState.Added;`

at this point the res is equal to 1, which I believe indicates that all is ok.
but tracking.State is EntityState.Unchanged.

Why the state does not indicate Unchanged.Added?
When I check on mac, the database file is created as expected "words.db3", when I investigate it there is my table WordDB with all columns, and whenever I execute the above mentioned methods the state is still UnChanged but the new row is added to that table instantly. 

What am I doing wrong?

**Comment by ericsink** [comment]
Sorry, I can't help with this one. It looks like you should post it in the Entity Framework repo instead.

**Comment by bricelam** [comment]
During SaveChanges, the pending changes are persisted to the database and the change tracker entries are reset. This allows additional changes to be made for the next SaveChanges. The SaveChanges method commits the current unit of work.

**Comment by ericsink** [comment]
Closing old/stale issue.
