### ISSUE TITLE
Virtual tables support

### ISSUE THREAD

**Issue by yaliashkevich** [ericsink/SQLitePCL.raw#191]
I'm looking for a way to implement custom "table-valued" function.
From what I've got here: http://sqlite.org/vtab.html I can use virtual tables mechanism, but I cannot find C# counter parts for this API. Is it supported or planned to be supported?

**Comment by ericsink** [comment]
SQLitePCL.raw currently does not support virtual tables.  I would like to add this feature, but there hasn't been much demand for it.  I think it'll get done eventually, but realistically, not soon.

**Comment by springy76** [comment]
And yet another reason against EFcore.

**Comment by bricelam** [comment]
@springy76 This is an odd place for that comment...

**Comment by ericsink** [comment]
@springy76 Could you clarify your comment?  I'm not sure I understand exactly what you're saying.

**Comment by springy76** [comment]
Maybe you should read this [issue](https://github.com/aspnet/EntityFramework6/issues/271#issuecomment-364139252) for better understanding.

**Comment by ericsink** [comment]
@springy76 Ah, sorry I asked. Never mind. Have a nice day.

**Comment by ericsink** [comment]
Closing old/stale issue.
