### ISSUE TITLE
Need e_sqlite3 (et al) builds for Alpine Linux

### ISSUE THREAD

**Issue by ericsink** [ericsink/SQLitePCL.raw#192]
Requested by @natemcmaster

musl instead of glibc

**Comment by natemcmaster** [comment]
Some pointers. Hopefully they might help you.

I got a build for Alpine working in a pre-release version of the "SQlite" package. Here are the changes I made:

https://github.com/natemcmaster/libsqlite3-package/commit/804d8bbd7ff83956f4b88b420253e0de59031abc

The important bits:
 - Use `musl-dev` and `musl-tools`
 - Some monkey patching of SQLite's scripts: https://github.com/natemcmaster/libsqlite3-package/blob/962ef97227204fc56cf9d4706a8ad7f901ce50d6/compile.sh#L52-L56
 - Putting the binary in `runtimes/alpine-x64/native/` so NuGet/.NET Core pick up the binary only on Alpine. https://github.com/natemcmaster/libsqlite3-package/blob/962ef97227204fc56cf9d4706a8ad7f901ce50d6/SQLite.nuspec#L25
```xml
<file src="runtimes/alpine-x64/native/libsqlite3.so" target="runtimes/alpine-x64/native" />
```

**Comment by ericsink** [comment]
SQLitePCL.raw pre-release version 1.1.10-pre20180223200113 has been pushed to nuget.  It contains musl-x64 for alpine-x64.  Let me know if it works okay?

**Comment by natemcmaster** [comment]
Confirmed, it appears to work just fine. Here was my test.

```Dockerfile
FROM microsoft/dotnet:2.1.0-preview1-runtime-alpine
WORKDIR /app
COPY ./pub .

ENTRYPOINT [ "dotnet", "alpine.dll" ]
```
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <RuntimeFrameworkVersion>2.1.0-preview1-26216-03</RuntimeFrameworkVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="2.1.0-preview1-final" />
    <PackageReference Include="SQLitePCLRaw.bundle_green" Version="1.1.10-pre20180223200113" />
  </ItemGroup>

</Project>
```
```c#
using System;
using Microsoft.Data.Sqlite;

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("Hello World!");

        using (var conn = new SqliteConnection("Data Source=./test.db"))
        {
            conn.Open();
            Console.WriteLine("SQlite = " + conn.ServerVersion);
        }
    }
}

```
```
dotnet publish -o pub
docker build . -t test
docker run --rm -it test
```
With SQLitePCLRaw 1.1.8, the test app fails
```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.DllNotFoundException: Unable to load DLL 'e_sqlite3': The specified module or one of its dependencies could not be found.
```
With 1.1.10-pre20180223200113, it succeeds.
```
Hello World!
SQlite = 3.22.0
```

**Comment by ericsink** [comment]
Very good.  Thanks.  I'll close this issue when 1.1.10 final is out.

**Comment by natemcmaster** [comment]
Do you have a timeline for when that will happen?

**Comment by ericsink** [comment]
I would like to release 1.1.10 next week, maybe the week after.  But this is somewhat flexible.  If you have time constraints, tell me more, and I should be able to accommodate.  The main reason to delay is to give more time to the folks at Zetetic, who are testing that bundle.  But I do expect that any fixes for that bundle would end up being very localized and low-risk.

**Comment by natemcmaster** [comment]
No rush. Anytime in the next month would be fine for us. We’re still working on aspnetcore 2.1.0-preview2, which we could release with the preview you pushed. We’ll be doing more testing on EFCore.SQlite this week to make sure it works with this update.

**Comment by ericsink** [comment]
The 1.1.10 release is now on nuget.org
