### ISSUE TITLE
SQlcipher_export function does not work for UWP

### ISSUE THREAD

**Issue by JKennedy24** [ericsink/SQLitePCL.raw#197]
I have a UWP project and I am trying to upgrade existing db files to sqlcipher files using the following code:

                var d = db.Connection.ExecuteScalar<string>("PRAGMA cipher_version"); // 3.4.1
                
                db.Connection.Execute("ATTACH DATABASE '" + tempDbFile.Path + "' AS encrypted KEY '" + dbKey + "';");
                db.Connection.Execute("SELECT sqlcipher_export('encrypted');");
                db.Connection.Execute("DETACH DATABASE encrypted;");

But the line `sqlcipher_export` fails with error 

> SQL error or missing database

If I check the `TempFile` I can see the tables are created but no data has been populated.

If I use the same commands in SqliteBrowser program I can create my sqlcipher file

**Comment by JKennedy24** [comment]
Ok so I managed to stop it throwing an error by changing tit to:

                db.Connection.Execute("ATTACH DATABASE '" + tempDbFile.Path + "' AS encrypted KEY '" + dbKey + "';");
                var res = db.Connection.Query<object>("SELECT sqlcipher_export('encrypted');");
                db.Connection.Execute("DETACH DATABASE encrypted;");

but still on UWP it creates a file with all the tables but no data in it

**Comment by ericsink** [comment]
Do you have any indication that this is UWP specific?  For example, if your project involves other platforms, is this same code working on those other platforms?

**Comment by JKennedy24** [comment]
@ericsink I have checked and actually this does work on UWP for 2 of my 3 db3 files. It fails for one, so it is probably something about that file that fails the function.

I will close this issue and re-open a more specific one if I can

**Comment by JKennedy24** [comment]
Ok so further testing.

This is only an issue on UWP
This only happens with 1 of my 3 databases which is 131mb big (so could be a size thing)

using the same database I can run the `sqlcipher_export` command using sqlitebrowser and it succeeds (although reports it errored) but using sqldiff utility it tells me the databases are the same

**Comment by ericsink** [comment]
Thanks for the additional testing.  I'm not entirely sure how to make progress on this one, as I know more about building sqlcipher than about using it.

My copy of the sqlcipher code is a bit outdated.  Perhaps if I updated to something more recent...

**Comment by ericsink** [comment]
I have pushed another build of SQLitePCLRaw.lib.sqlcipher.windows:

https://www.nuget.org/packages/SQLitePCLRaw.lib.sqlcipher.windows/1.1.10-pre20180210141505

I am curious whether it might fix the problem.

**Comment by JKennedy24** [comment]
@ericsink I have just tried the latest package, unfortunately same problem, tables copied but none of the data. What was updated in the latest package?

**Comment by ericsink** [comment]
I had found that my uwp sqlcipher build did not have SQLITE_TEMP_STORE=2 set, and the sqlcipher docs say this is required.  So I rebuilt, hoping that might have been the source of the problem.

Would it be possible (without *too* much trouble) for you to construct a simple test project that reproduces this problem?

**Comment by ericsink** [comment]
If I have not exhausted your patience, and you are really wanting to try another build:

https://www.nuget.org/packages/SQLitePCLRaw.lib.sqlcipher.windows/1.1.10-pre20180212190230

This build is based on the updated/current version of sqlcipher and uses libtomcrypt as the crypto provider, which is directly supported by the sqlcipher maintainers.

**Comment by JKennedy24** [comment]
@ericsink I'll give the new build a go today and get back to you

**Comment by JKennedy24** [comment]
@ericsink  that latest pre release fixed the issue. Thanks for your help!
