### ISSUE TITLE
System.DllNotFoundException: Unable to load DLL 'sqlcipher'

### ISSUE THREAD

**Issue by StefanoD** [ericsink/SQLitePCL.raw#201]
Hi,
I think, this is related to #194. But this is happening with SQLitePCLRaw.bundle_sqlcipher with the `RID` `win-x64`.
I have following dlls in my win_x64 folder:
- SQLitePCLRaw.batteries_sqlcipher.dll
- SQLitePCLRaw.batteries_v2.dll
- SQLitePCLRaw.core.dll
- SQLitePCLRaw.provider.e_sqlite3.dll
- SQLitePCLRaw.provider.sqlcipher.dll

Is there some kind of workaround? Because I need to stay to 1.1.7, because of this [issue](https://github.com/aspnet/Microsoft.Data.Sqlite/issues/480).
Are there maybe precompiled dlls for `win-x64`? Can I maybe use the compiled dll from `win7-x64`?

**Comment by ericsink** [comment]
Can you try version 1.1.10-pre20180223200113 ?

The 1.1.10 prerelease has fixes for the win7 RID problem.

I am also interested in the (perhaps small) possibility that the 1.1.10 prerelease might fix the problem you are seeing with aspnet/Microsoft.Data.Sqlite#480.

**Comment by StefanoD** [comment]
Ok, this is fixed in 1.1.10-pre20180223200113.
Thank you very much!
