### ISSUE TITLE
Consider using built-in UTF-8 marshalling

### ISSUE THREAD

**Issue by bricelam** [ericsink/SQLitePCL.raw#202]
.NET Core 1.1+ and .NET Framework 4.7+ support this via `[MarshalAs(UnmanagedType.LPUTF8Str)]`, `Marshal.StringToCoTaskMemUTF8()`, and `Marshal.PtrToStringUTF8()`.

But given all the platforms you target, it may not make sense to add another `#if` block just for this...

**Comment by ericsink** [comment]
As mentioned in #268, it would seem that the right direction is to facilitate cases where the layers above want to control when or if UTF-8 conversion takes place.  The suggestion in this issue would seem to be an idea in the opposite direction.

So I'm closing this.  Feeel free to re-open if push back or further discussion is needed.
