### ISSUE TITLE
Visual Studio 2017 for Mac -> Target Raspbian Linux Armhf using Entity Framework

### ISSUE THREAD

**Issue by tpitman** [ericsink/SQLitePCL.raw#203]
I am using VS2017 for Mac to make a ASP net core application. It is net core 2.0.4

I have the web app working and added sqlite support using Entity Framework.

Everything runs fine on Mac os for the sqlite.

When I try to run it on my raspberry pi running raspbian, the other web pages all work just fine.

When I try to go to the page that loads the sqlite database I get the error that everyone has seen that e_sqlite cannot be loaded.

I read a post saying to come to this repo and download the libe_sqlite.so file and just put it in the same folder as my application.

There are a lot of other .so files there as well, so I put libe_sqlite.so in that same folder.

I made sure to chmod +x it so it was executable like the others.

I still get the same error about not being able to load e_sqlite module.

Can someone help me?

**Comment by ericsink** [comment]
Sorry, somehow I didn't notice this issue when it first came in.

Have you moved past the problem yet?

**Comment by tpitman** [comment]
I switched to mysql, but if there is an easy fix sqlite is much easier to
setup.

**Comment by ericsink** [comment]
What version of SQLitePCL.raw are you using?

And what command did you use to publish for raspbian?

**Comment by ericsink** [comment]
(So in other words, no there is no easy fix, at least not until we diagnose what's wrong, which could take some time.)

**Comment by tpitman** [comment]
Whatever the latest nuget package is as of the day I posted this issue. I am all set up with mysql now so I will branch what I have and have to go back to that to help diagnose.

I was using the publish with -r linux-arm.

**Comment by ericsink** [comment]
Closing old/stale issue.
