### ISSUE TITLE
Alter ARM compiler flags for Raspberry Pi 1 compatibility

### ISSUE THREAD

**Issue by directhex** [ericsink/SQLitePCL.raw#204]
The Pi 1 hardware (of which there are a whole bunch) only supports the ARMv6 instruction set, not ARMv7.

The default flags of your armhf cross-compiler produce v7 binaries:

```directhex@flame:/tmp/foo/runtimes/linux-arm/native$ readelf -A libe_sqlite3.so 
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "7-A"
  Tag_CPU_arch: v7
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv3-D16
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_rounding: Needed
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_align_preserved: 8-byte, except leaf SP
  Tag_ABI_enum_size: int
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6
```

Adding `-march=armv6 -mfloat-abi=hard -mfpu=vfp` to the compiler flags should ensure compatibility with the first generation Pi (Pi 2 & 3 can use v7 binaries, even though the Pi OS is built for v6)

**Comment by ericsink** [comment]
Maybe I should keep the armv7 binary and produce a separate binary for armv6?

From what I can tell, dotnet RIDs use "arm" to mean v7 and "armel" to mean v6.

**Comment by directhex** [comment]
Armel is for soft float - on paper it should be arm v4t, but nobody has hardware for that any more so builds for v5 without anyone complaining 

Armhf (arm rid) is hard float, which is a completely incompatible ABI. You can't load armel libraries in an Armhf OS, regardless of processor instruction level 

Armhf is built for v7 with the default flags you used in Debian and Ubuntu - but raspbian (the OS shipped with raspberry pi) is compiled for v6 due to limitations of the pi 1 silicon

V6 Armhf binaries work at a small performance cost on v7 OSes and hardware, but v7 binaries will just throw an illegal instruction error on pi 1 hardware

**Comment by ericsink** [comment]
@directhex And so if I add a build using the compiler flags you specified above, what should its RID be?

**Comment by directhex** [comment]
If you want it as an additional rather than replacement, I think the most sensible RID would be `raspbian-arm` or `raspbian.8-arm`. Whilst raspbian isn't defined in the RID catalog, the format is consistent & valid. That would be the right way to say "built for raspbian" rather than "built for portable, generic linux"

**Comment by ericsink** [comment]
Closing this issue on the assumption that so much time has passed that supporting Pi1 doesn't matter anymore.
