### ISSUE TITLE
How to use SqliteCipher in UWP project using  sqlite-net-pcl?

### ISSUE THREAD

**Issue by shahramSo** [ericsink/SQLitePCL.raw#212]
I used  sqlite-net-pcl in a UWP project which has explained as follows:
 

> 

var databasePath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "MyData.db");

var conn = new SQLiteAsyncConnection(databasePath);

await conn.CreateTableAsync<Stock>();
> 
 So I would like to know how to use sqliteCipher for encryption of Sqlite?
any Idea? is there any example project?
Thanks

**Comment by ericsink** [comment]
If you are asking about how to use sqlcipher in general, it is not UWP-specific.  See the following link for some starting points:

https://www.zetetic.net/sqlcipher/sqlcipher-api/

**Comment by shahramSo** [comment]
Hi,
Thank you for your reply, I saw it but I want to know how to implement SQLitePCL.raw under sqlite-net-pcl in a UWP project? is it possible? 
Thanks

**Comment by shahramSo** [comment]
Hi Eric,
I implemented  SQLitePCLRaw.bundle_sqlcipher and  sqlite-net-pcl, in a test VS2017 project, and then tested it as follows:
    
          var dbPath = Path.Combine(ApplicationData.Current.LocalFolder.Path, "MyData.db");

            var db = new SQLiteConnection(dbPath );
            db.Execute("PRAGMA key='123'");
            db.CreateTable<Stock>();
            db.CreateTable<Valuation>();

So this works fine form me and Db is encrypted without defaine "SQLitePCL.Batteries_V2.Init()".
Is it normal?
Thanks

**Comment by ericsink** [comment]
Yes.
