### ISSUE TITLE
could not find a part of the path...sqlite3.dll

### ISSUE THREAD

**Issue by amorpsyche** [ericsink/SQLitePCL.raw#213]
Hello,
I am sorry if this topic already exists, I was searching for it, but couldn't find this specific problem here.

So I want to use SQLite on my Xamarin Project, and I followed a tutorial, it should work perfectly fine, but it doesn't, at least not with the Xamarin Live Player (Testflight). I googled quite much to fix this, but it just won't..
Does anyone have an idea how? I know it should be possible.

I tested this on another computer with the Android Live Player and it worked. Just on my iPhone Live Player it doesn't. But I have no other options but my iPhone Live Player to keep testing the app.
I hope somebody can help me. Kinda desperate by now.

`System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path "/var/mobile/Containers/Data/Application/7E3BF498-FCC6-46CE-91CE-DAE7FBAB8FEF/Documents/External/.nuget/packages/sqlitepclraw.provider.sqlite3.ios_unified/1.1.5/lib/Xamarin.iOS10/SQLitePCLRaw.provider.sqlite3.dll".`

**Comment by ericsink** [comment]
Sorry I haven't replied to this.  I don't have any experience with Live Player and its potential compatibility issues.
