### ISSUE TITLE
React to changes in Alpine RID graph

### ISSUE THREAD

**Issue by natemcmaster** [ericsink/SQLitePCL.raw#214]
Starting in .NET Core 2.1, there is a new parent rid for `alpine-x64` called `linux-musl-x64` (see https://github.com/dotnet/corefx/pull/28560). #192 added Alpine support (thanks again). To make this available to other Linux distros based on muslc-based SQLite, I'd recommend the following, fairly minor change:

 - Change the package folder name in SQLitePCLRaw.lib.e_sqlite3.linux from `runtimes/alpine-x64/` to `runtimes/linux-musl-x64/`. 

If you want to keep the package backwards compatible with .NET Core 2.0 and earlier, you can either..
 - put the libe_sqlite3.so file in both "runtimes/alpine-x64" and "runtimes/linux-musl-x64", or
- consumers can reference `Microsoft.NETCore.Platforms` 2.1.0 or greater. (This magic package defines the alpine-x64->linux-musl-x64 relationship)

**Comment by ericsink** [comment]
Acknowledged.

I assume that you need this fairly soon?

**Comment by natemcmaster** [comment]
Don't feel rushed on this one. The workaround is fairly simple for us. But, if you have time to get this in the next few weeks, that would be great.

For some context: https://github.com/aspnet/Universe/pull/1104, https://github.com/aspnet/Universe/issues/1101

**Comment by ericsink** [comment]
Very good.  Thanks.

**Comment by natemcmaster** [comment]
> So, unless you have other concerns, I plan to just go ahead with a 1.1.11, probably in the next few days

That would be great. We're almost in escrow for 2.1.0 RTM. It may actually be beneficial to getting this in as a last minute change if the package layout is the *only* thing that changed in this patch.

By the way, I thought about this a little more. To keep .NET Core 2.0 customers happy, it might be better to put the libe_sqlite3.so file in both "runtimes/alpine-x64" and "runtimes/linux-musl-x64". It makes me sad this is necessary, but .NET Core 2.0 apps won't know how to treat "linux-musl-x64" yet, only .NET Core 2.1+

**Comment by ericsink** [comment]
I tweaked the package layout as you just described, putting the same libe_sqlite3.so file in both alpine-x64 and linux-musl-x64.

I am pushing 1.1.11 to nuget now.  The package layout described herein is the _only_ change.

Well, to be pedantic, the version number also changed, which means:.  All the assemblies got rebuilt, with the AssemblyVersion updated.  So the assemblies in these nuget packages are not the *exact* same bits as 1.1.10, but they were built from the same code on the same machine using the same build script calling the same tooling, all of which have been quite trustworthy.

**Comment by natemcmaster** [comment]
Awesome, thanks @ericsink. I'll get a PR ready to aspnetcore to consume this update.

**Comment by natemcmaster** [comment]
Tested and updated to 1.1.11. Thanks again for fixing this!
