### ISSUE TITLE
Would you ever distribute SpatiaLite?

### ISSUE THREAD

**Issue by bricelam** [ericsink/SQLitePCL.raw#215]
I'm curios if you'd ever consider packaging [SpatiaLite](https://www.gaia-gis.it/fossil/libspatialite/index) as part of SQLitePCL.raw. I'm not looking for any .NET bindings or anything; just enough to enable a cross-platform workflow like this:

``` shell
dotnet add package SQLitePCLRaw.ext.spatialite
```
``` csharp
SQLitePCL.raw.sqlite3_enable_load_extension(db, 1);
```
``` sql
SELECT load_extension('spatialite');
```

**Comment by ericsink** [comment]
Maaaaybe.

I don't know much about SpatiaLite, so it would seem silly at this point to either promise or refuse.

**Comment by bricelam** [comment]
Digging into it, I don't think this belongs as part of this project. SpatiaLite has a lot of external dependencies.

I plan to create a NuGet package to make installation on Windows (x86 and x64) easier, but everywhere else, it probably makes more sense just to install it globally using APT/Homebrew/etc.
