### ISSUE TITLE
Error building Xamarin.Android project

### ISSUE THREAD

**Issue by ataparia** [ericsink/SQLitePCL.raw#218]
Project Structure:
1. PCL
   Have added the following PCL dll references to this project
   a) SQLitePCL.raw(0.9.4-pre1)
   b) SQLitePCLRaw.batteries_e_sqlite3(3.1.1.11)
   c) SQLitePCLRaw.batteries_v2(3.1.1.11)
2. Xamarin Android project
      Have added the following Android dll references to this project
      a) SQLitePCL.raw(0.9.4-pre1)
      b) SQLitePCLRaw.batteries_e_sqlite3(3.1.1.11)
      c) SQLitePCLRaw.batteries_v2(3.1.1.11)

Note:
-------
I have a copy of SQLiteNet.cs and since I made modifications to it, I cant throw it away. So I copied this code from https://github.com/praeclarum/sqlite-net/blob/master/src/SQLite.cs to my class and redid my modifications.

I am getting the following error while building the android project:
----------------------------------------------------------------------------
Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'SQLitePCLRaw.provider.e_sqlite3, Version=1.1.11.121, Culture=neutral, PublicKeyToken=9c301db686d0bd12'. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'SQLitePCLRaw.provider.e_sqlite3.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	Infor.Mobile.PublicSector.Android	
--------------------------------------------------------------------------------

One thing to observe is that the dlls I added to the PCL project are throwing warning signs. Please see attached image.
![pcl_project_reference](https://user-images.githubusercontent.com/2609962/39774395-b6922df2-52c8-11e8-9aca-e0f962483ebb.PNG)

Am I doing this the right way or am I missing something in here?

**Comment by ataparia** [comment]
My PCL project targets this:
![pcl_project_target](https://user-images.githubusercontent.com/2609962/39776031-a52ec6b0-52cd-11e8-9ddf-8ee3c483c93e.PNG)

**Comment by ericsink** [comment]
You should not be using version 0.9.x of SQLitePCL.raw.

When you say "3.1.1.11", I assume you mean "1.1.11", which is the current version.

You should not need to reference the batteries assemblies in the PCL project.  Do the call to SQLitePCL.Batteries_V2.Init() in the app project instead.

Are you referencing the SQLitePCL.raw assemblies directly, or by adding the nuget package?

Even with your own copy of SQLite.cs, you should be able to use nuget for SQLitePCL.raw stuff, which will make your life much easier.

Add SQLitePCLRaw.Core to the PCL project.  Add SQLitePCLRaw.batteries_e_sqlite3 to the Android project.

**Comment by ataparia** [comment]
Yes, the version is 1.1.11 for the batteries dlls.

Just making sure I understand this right:
1. I should add SQLitePCL.Raw.Core dll to the PCL project 
2. Should add SQLitePCLRaw.batteries_e_sqlite3 to the android project
3. Should add SQLitePCLRaw.batteries_v2 to the android project
4. From the app project, I should call SQLitePCL.Batteries_V2.Init() right?

**Comment by ericsink** [comment]
Minor clarifications:

1.  Add SQLitePCLRaw.Core, the nuget package, not the dll itself, to the PCL project.
2.  Add SQLitePCLRaw.batteries_e_sqlite3, the nuget package, to the android project.
3.  You don't need to add SQLitePCLRaw.batteries_v2, the assembly, because it is contained in the nuget package from item (2).
4.  Yes

And all this assumes you have merged the proper stuff into your copy of SQLite.cs

**Comment by ataparia** [comment]
Thanks Eric. I will try this out and see what I get. Thanks again for your help on this.

**Comment by ataparia** [comment]
Solution builds fine after following Erics advise.

**Comment by ataparia** [comment]
The project builds successfully, but when I try to run the android project, I get the following error - "**System.DllNotFoundException: /system/lib/libsqlite.so**"

![error](https://user-images.githubusercontent.com/2609962/39886934-e7a0f6de-545e-11e8-8713-877edead9e09.PNG)
![pcl_references](https://user-images.githubusercontent.com/2609962/39886937-eaa14b2c-545e-11e8-915e-b4f2fbd8bdfe.PNG)
![android_references](https://user-images.githubusercontent.com/2609962/39886938-ebe0a5dc-545e-11e8-97ce-a177e9d86a21.PNG)

Not sure if I have to do anything extra.

**Comment by ataparia** [comment]
PCL Project References shown below
![pcl_references](https://user-images.githubusercontent.com/2609962/39886988-0a7d20c4-545f-11e8-94a5-086e6edb9e69.PNG)

Android Project References shown below:
![android_references](https://user-images.githubusercontent.com/2609962/39887014-143bd272-545f-11e8-9a01-184d1ecded9b.PNG)

**Comment by ericsink** [comment]
That means you are trying to load the system sqlite, which on android is not allowed.

And this is probably happening because your private copy of sqlite.cs is configured that way.

You will need to `#define USE_SQLITEPCL_RAW` in sqlite.cs, and your copy of that file needs to have the corresponding stuff merged into it.

You should define `NO_SQLITEPCL_RAW_BATTERIES` too.

**Comment by ataparia** [comment]
Yep....I had the Sqlite.cs merged fine....all I forgot was to define the build symbols in my proj file. Its works like a charm now. Thanks again Eric.
