### ISSUE TITLE
Native iOS support

### ISSUE THREAD

**Issue by gmakoudi** [ericsink/SQLitePCL.raw#219]
Hey! Thank you for your awesome project!

Is e_sqlite3.framework supposed to support native iOS apps?

I have built the .sh file for iOS with bitcode enabled. However, when I'm adding the framework to an XCode iOS project, I am getting a "not found" error. Tried both as an Embedded and as a Linked framework option.

Just curious if you have tried that. Thanks in advance for your input.

**Comment by ericsink** [comment]
Sorry, no, the e_sqlite3 builds are intended only for use with .NET platforms.

**Comment by gmakoudi** [comment]
Thank you for your help and your quick response.

Do you think the xamarin.ios e_sqlite3.dll would be compatible?
Or maybe does the SQLitePCLRaw.bundle_e_sqlite3 support iOS?
Thanks again for the help.

**Comment by ericsink** [comment]
SQLitePCL.raw does have an iOS build of e_sqlite3, but it is a static lib (not a dylib or a framework) and it is embedded inside a .NET assembly, so it would not be compatible with Xcode.

However, the builds are checked in to this repo.  Look in
'
apple/libs/ios/sqlite3

there you have the static lib, e_sqlite3.a

there is also e_sqlite3.framework, but I don't know if it works.  Some time ago I was working on possibly supporting dynamic libs for iOS (which I have not finished).  This is leftover from that effort.

**Comment by gmakoudi** [comment]
Thank you for your help.
