### ISSUE TITLE
NetCore App with Mono - DllNotFoundException

### ISSUE THREAD

**Issue by deinok** [ericsink/SQLitePCL.raw#221]
Hi, I have a NetCore app that i need to run in a linux-x86.
NetCore don't support linux-x86, only x64 and arm. So I have to use Mono, targeting net471.

Everything works fine except Microsoft.EntityFrameworkCore.Sqlite.
Seems like i'm having a `System.DllNotFoundException: e_sqlite3`

I'm doing something in an incorrect way?

* dotnet --version (On Compilation machine) [dotnet--version.log](https://github.com/ericsink/SQLitePCL.raw/files/2044512/dotnet--version.log)
* mono --version (On Execution machine) [mono--version.log](https://github.com/ericsink/SQLitePCL.raw/files/2044474/mono--version.log)
* mono *.exe (`dotnet publish --configuration Release --framework net471`)(Executed on the execution machine) [execution-log.log](https://github.com/ericsink/SQLitePCL.raw/files/2044521/execution-log.log)

**Comment by ericsink** [comment]
Try adding the nuget package SQLitePCLRaw.bundle_e_sqlite3

**Comment by deinok** [comment]
Did not work

**Comment by oOGenosOo** [comment]
Never try on NetCore but fews days ago i'd the same problem on an Android Project (Mono framework) and i solve doing a right click to my droid platform project (in your case so use the NetCore project) and click on "use at startup project", rebuild is needed.
Hope that help,
A-

**Comment by deinok** [comment]
@oOGenosOo Not working for me :(
Probably is due the fact that I'm running NetCore under an i586 arch.

**Comment by deinok** [comment]
Hi, @ericsink just one question. the native library, is there a dll for Linux-x86?

**Comment by ericsink** [comment]
Yes.  It's in SQLitePCLRaw.lib.e_sqlite3.linux

**Comment by ericsink** [comment]
Closing old/stale issue.
