### ISSUE TITLE
Problem with Xamarin6Visual Studio 2017 when compiling for IOS (CrossPlatform).

### ISSUE THREAD

**Issue by oOGenosOo** [ericsink/SQLitePCL.raw#222]
Hi Erik,
As explained in title, only on IOS (the android version works  like a charm) i cannot compile with the following error:

> Can't resolve the reference 'System.Void SQLitePCL.lib.embedded::Init()', referenced from the method 'System.Void SQLitePCL.Batteries_V2::Init()' in 'SQLitePCLRaw.lib.sqlcipher, Version=1.1.11.121, Culture=neutral, PublicKeyToken=980f7eff3ce1003e'.	

I've installed the following plugins and the sql-lite-pcl extension:
![image](https://user-images.githubusercontent.com/35723489/40724569-a226603a-6421-11e8-96e9-39bc7b557b17.png)

Can you explain what i'm doing wrong because i cannot get out of that :(

Thanks-

**Comment by ericsink** [comment]
Is this the list of packages in your iOS project?

**Comment by oOGenosOo** [comment]
Unfortunately not.... is a very big project with lots of packages, that are the only related to SQLite, all in IOS project except the 2 *.android that are installed only to the android specific project

**Comment by ericsink** [comment]
OK, I was wondering why the android packages are there.

So I'm not exactly sure which packages you have where, so here are more general thoughts on how to make this work:

I recommend using PackageReference in your csproj files, not packages.config and definitely not project.json, and each project only referencing the projects it directly needs, letting PackageReference sort out transitive dependencies.

If you're using sqlite-net-pcl, you need to also add bundle_green package to your app-level projects.

The error about "SQLitePCLRaw.batteries_v2, Version=1.0.0.0" suggests that you may need to add binding redirects.  SQLitePCLRaw assemblies are strong-named, and as of 1.1.10, the Version attribute is being updated.

**Comment by oOGenosOo** [comment]
> I recommend using PackageReference in your csproj files, not packages.config and definitely not project.json, and each project only referencing the projects it directly needs, letting PackageReference sort out transitive dependencies.

**Done**

> If you're using sqlite-net-pcl, you need to also add bundle_green package to your app-level projects.

**Done**

The error about "SQLitePCLRaw.batteries_v2, Version=1.0.0.0" suggests that you may need to add binding redirects. SQLitePCLRaw assemblies are strong-named, and as of 1.1.10, the Version attribute is being updated.

I've just add <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects> to IOS csproj, if i need something else to do can you explain better?

Thanks a lot for take your time to answer me :)
A-

**Comment by ericsink** [comment]
I'm not certain that a binding redirect is in fact the problem you are seeing.  But if it is, here is more info:

sqlite-net was built against SQLitePCL.raw assemblies that specified 1.0.0.0 as their version number.

The ones you are using are version 1.1.11.121

To make this work, you need a binding redirect which says "when something is looking for version 1.0.0.0, use 1.1.11.121 instead".

In most cases, the tooling figures this out and does the binding redirect for you.  This is why I cannot say with confidence that I am diagnosing the problem correctly.

One way for you to proceed is to add the binding redirect and see if it changes the error or solves the problem.

See below for docs on binding redirects:

https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions

**Comment by oOGenosOo** [comment]
Thanks, now i got it, but nothing has changed :(
the AutoGenerateBindingRedirects just generate some code:

```
<dependentAssembly>
        <assemblyIdentity name="SQLitePCLRaw.Batteries_V2" publicKeyToken="8226ea5df37bcae9" culture="neutral" />
        <bindingRedirect oldVersion="1.0.0.0-1.1.11.121" newVersion="1.1.11.121" />
      </dependentAssembly>
```

that i try to edit in that 2 way:

```
<dependentAssembly>
        <assemblyIdentity name="SQLitePCLRaw.Batteries_V2" publicKeyToken="8226ea5df37bcae9" culture="neutral" />
        <bindingRedirect oldVersion="1.0.0.0" newVersion="1.1.11.121" />
      </dependentAssembly>
```

```
      <dependentAssembly>
        <assemblyIdentity name="SQLitePCL.Batteries_V2" publicKeyToken="8226ea5df37bcae9" culture="neutral" />
        <bindingRedirect oldVersion="1.0.0.0" newVersion="1.1.11.121" />
      </dependentAssembly>
```

But the error is still present :(

**Comment by oOGenosOo** [comment]
Justo for testing I completely change the host maching and i go on visualStudio for mac on a Mac Machine but i've the same problem:
![image](https://user-images.githubusercontent.com/35723489/40781813-94981744-64dd-11e8-9b3b-d610b5373274.png)

**Comment by ericsink** [comment]
Hmmm.

Did this problem just come up?  I mean, if everything was working, and then the error started happening, what changed?

If you downgrade your SQLitePCLRaw.* packages to version 1.1.9, does the problem go away?

**Comment by oOGenosOo** [comment]
IT'S WORKS!!!!! (..... maybe..... now it crash after the app start, but for that i trust in Debug Mode).
Seriously very thanks to all the answer.... and sorry if i spent your time for a so "easy to solve"  problem.... I try evrything but i forgot that i update the SQLitePCLraw few week ago to "update" [that fork of sqlite-net-pcl](https://github.com/oysteinkrog/SQLite.Net-PCL) to the main project, simple i never build the IOS version since now.... If i remember right SQLite.Net-PCL need some of SQLitePCLraw packages, that I probably update to the last version during the migration....

Now analyzing the problem a little deep, when installing the 1.1.9 version i see the dll Batteries_v2 in the project references, before i not see it (idk if is beacuse is integrated in _green after that version or because is missing in 1.1.11)
![image](https://user-images.githubusercontent.com/35723489/40787296-883d580a-64ed-11e8-8ca9-34120acf6b69.png)

Thanks again for your time :)
A-

**Comment by ericsink** [comment]
Yay.
