### ISSUE TITLE
Hope to support SQLite 3.24.0

### ISSUE THREAD

**Issue by guodf** [ericsink/SQLitePCL.raw#224]
See [SQLite3.24.0](https://www.sqlite.org/changes.html)

**Comment by ericsink** [comment]
Indeed. I am planning on this. 3.24.0 is a big release.

**Comment by bricelam** [comment]
EF Core customers are super excited about the ALTER TABLE enhancements in 3.25.0

**Comment by ericsink** [comment]
Looks like it's time for me to get moving on another release...

:-)

**Comment by ericsink** [comment]
Superseded by #242
