### ISSUE TITLE
Help with adding SQLitePCL.raw to another library

### ISSUE THREAD

**Issue by dlandi** [ericsink/SQLitePCL.raw#226]
Hi Eric,

I am not sure how else to reach you so I thought I would try this way.

I have developed a .NET Standard 2 Cache library that handles memory pressure, object serialization, compression and in-memory data protection. I used SQLite-net for the on-disk cache.  However, I am having a dickens of a time trying to figure how to add the right nuget pkgs to each platform build.

With your permission, I would like to add you to that project as a collaborator, so you can have a look and give me some guidance on what to do.  Once I get this part figured out, I will make the project public.

The project's name is "MemStache".

Let me know if this is OK with you, and I'll add you as a collaborator.

Thanks!

-dennis

**Comment by ericsink** [comment]
Sounds fine.

**Comment by dlandi** [comment]
Thanks. Invitation sent.

**Comment by ericsink** [comment]
Hmmm.  I just clicked on the invitation link (in the email sent by github) and it goes to a 404.

Do you still need help with this issue?

**Comment by dlandi** [comment]
Hi Eric,  Sorry about that. I went in another direction, yesterday.  Thanks for taking the time.
