### ISSUE TITLE
How to use SQLCipher in .Net

### ISSUE THREAD

**Issue by marin1993** [ericsink/SQLitePCL.raw#230]
I want to use C# (winform) to read an SQLCipher database.
but I have not found examples of this use, and the documentation is not a lot. 
Have any friends used this thing, can you provide some examples to help me?

Thank you!

**Comment by ericsink** [comment]
Sorry for the lack of reply on this one.

For documentation on using SQLCipher-specific features, I recommend the zetetic website.
