### ISSUE TITLE
The high OS validation detected using 'SQLitePCL 3.8.7.2' NuGet package

### ISSUE THREAD

**Issue by droprose** [ericsink/SQLitePCL.raw#231]
I have an application that copies sqlite from a local package to a local folder and reads it from the local folder. After I created the package into windows store and tested it using the Windows App Cert Kit the results failed like the picture on this link: https://1drv.ms/u/s!Av6G8Zq_Px8Wa0QkyPekOoJdV4A And after I try to install the application using powershell, in the first time the application starts, the application can run smoothly. After the application closes and starts again, the application only appears splash screen and after a while the application immediately exits. The following is the sample project: https://1drv.ms/u/s!Av6G8Zq_Px8WbOv5-Xl6AuW3o7s

**Comment by ericsink** [comment]
Closing old/stale issue.
