### ISSUE TITLE
WPF application : Unable to load DLL e_sqlite3

### ISSUE THREAD

**Issue by gutierrezralph** [ericsink/SQLitePCL.raw#233]
I have WPF application using SQLitePCL.
The application is running when I used Visual Studio to launch the app on my Desktop but when I create an installer, Then install on my computer, After hitting the launcher I received an error in my Raygun crash reporting.

**Stacktrace**

```
Message: Unable to load DLL 'e_sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
SQLitePCL.SQLite3Provider_e_sqlite3+NativeMethods.sqlite3_libversion_number():-1
SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number():0
SQLitePCL.raw.SetProvider(ISQLite3Provider imp):8
SQLitePCL.Batteries_V2.Init():5
SQLite.SQLiteConnection..cctor():0
```

**packages.config**
```
  <package id="sqlite-net-pcl" version="1.4.118" targetFramework="net461" />
  <package id="SQLitePCL.raw" version="0.9.3" targetFramework="net461" />
  <package id="SQLitePCL.raw_basic" version="0.8.6" targetFramework="net461" />
  <package id="SQLitePCLRaw.bundle_green" version="1.1.11" targetFramework="net461" />
  <package id="SQLitePCLRaw.core" version="1.1.11" targetFramework="net461" />
  <package id="SQLitePCLRaw.lib.e_sqlite3.linux" version="1.1.11" targetFramework="net461" />
  <package id="SQLitePCLRaw.lib.e_sqlite3.osx" version="1.1.11" targetFramework="net461" />
  <package id="SQLitePCLRaw.lib.e_sqlite3.v110_xp" version="1.1.11" targetFramework="net461" />
  <package id="SQLitePCLRaw.provider.e_sqlite3.net45" version="1.1.11" targetFramework="net461" />
```

I checked the C:\Program Files (x86)\MyApp folder where all DLL's will be extracted after installation but I can't find **e_sqlite3.dll**

Do I need to download it separately? If yes, What specific nugget package I need to install on my app to remove this error, I thought it was included in the package **SQLitePCL.raw**

**Comment by ericsink** [comment]
This depends a great deal on the tool you use to create the installer.  If that tool is not detecting the e_sqlite3.dll dependency (and I would be rather surprised if it did) then you need to make sure it is included somehow.

**Comment by keithrowe** [comment]
I'm seeing the same issue. I'm able to run the WPF app by itself. When I create a package using the Visual Studio 2019 Windows App Packaging Project, the e_sqlite3.dll does not get created in the package. 

Is there a workaround?

**Comment by ericsink** [comment]
Sorry, I have no experience with an "App Packaging Project".  You may need to somehow manually specify that file to be included.
