### ISSUE TITLE
Enable recursive triggers by default in e_sqlite3

### ISSUE THREAD

**Issue by bricelam** [ericsink/SQLitePCL.raw#238]
As far as I can tell, there's no compile-time option to do this. ☹️ Is it worth petitioning the SQLite team to add one so you can leverage it in e_sqlite3? Would anyone not want this on by default?

**Comment by ericsink** [comment]
As I understand it, recursive triggers have caused very significant backward compatibility problems for some cases.  So the answer to "Would anyone not want this on by default?" is yes, probably quite a few people.

That said, I would agree that ON would be a better default, and I do wish that there was a compile-time option for it.  This comes up as a support issue with our Zumero customers.

Even as I write this, I'll admit that if the compile-time option were available, I would pause and think before enabling it in e_sqlite3, wondering what kind of breakage it might cause.  But ON is the setting I would *want* to use.

**Comment by bricelam** [comment]
Feel free to close this. I'm OK with the world as it is today.

We're adding the `Recursive Tirggers` keyword to connections strings in Microsoft.Data.Sqlite version 3.0.0. This makes it easier to turn it on for all connections.

**Comment by ericsink** [comment]
Closing old/stale issue.
