### ISSUE TITLE
Add sqlite3_blob_reopen() to ISQLite3Provider interface

### ISSUE THREAD

**Issue by DanielGilbert** [ericsink/SQLitePCL.raw#240]
Hi,

judging from the [ISQLite3Provider](https://github.com/ericsink/SQLitePCL.raw/blob/e57af260a4b01650da0dae3900ae7708c3e9ce73/src/cs/isqlite3.cs#L165) interface, the "BLOB"-functions lack the `int sqlite3_blob_reopen(sqlite3_blob *, sqlite3_int64);` declaration.
Would be great to have it, performance wise. <3

See the [Docs](https://sqlite.org/c3ref/blob_reopen.html) for further info.

**Comment by ericsink** [comment]
Implemented as part of upcoming 2.0 release #255
