### ISSUE TITLE
Update unofficial sqlcipher builds to 4.x

### ISSUE THREAD

**Issue by ericsink** [ericsink/SQLitePCL.raw#244]
We currently ship sqlcipher 3.x, which contains the magellan vulnerability.

We could update to 4.0.1 to fix that, but without extra steps it is not backward compatible with 3.x.

**Comment by ericsink** [comment]
sqlcipher/sqlcipher#296

**Comment by jlcool** [comment]
Can't there be two versions? Use the new version of 4.x and the old version of 3.x. Isn't that okay?

**Comment by ericsink** [comment]
@jlcool  In principle, yes.

I just haven't done that.  Yet.

**Comment by Tristan-gu** [comment]
Is there a link between this [issue](https://github.com/aspnet/EntityFrameworkCore/issues/14212), in the end of the post, I explain than when I use SQLitePCLRaw.bundle_sqlcipher, the SQLite version is automatically 3.20.1, and not 3.26.0 as described [here](https://www.nuget.org/packages/SQLitePCLRaw.bundle_sqlcipher/) ?

Or I'm totally wrong ?

**Comment by ericsink** [comment]
Yes, the e_sqlcipher builds are currently on SQLCipher 3.x, which was based on SQLite 3.20.1.

**Comment by Tristan-gu** [comment]
OK, thank you for the explanation.

As you said, you didn't have the time yet to update it, do you have an idea when you think you will update it ?
It's only to organize a release product on my side.
Regards

**Comment by ericsink** [comment]
I do plan to get this done, but I remain hesitant to give a specific time frame.  

If anyone else wants to do the work, I can give some guidance, and will review any resulting pull request for inclusion.

In the meantime, another option is to purchase official SQLCipher builds from Zetetic.

**Comment by ericsink** [comment]
The unofficial sqlcipher builds for SQLitePCLRaw v2 (see #255) are based on SQLCipher Community 4.2.
