### ISSUE TITLE
SqlCipher library V1.1.12 does not work on iOS with linking enabled

### ISSUE THREAD

**Issue by JKennedy24** [ericsink/SQLitePCL.raw#246]
I am building my iOS project after updating to 1.1.12 using sqlitePCL.raw.bundle_sqlcipher and I a getting the following error:

> clang : error : linker command failed with exit code 1 (use -v to see invocation)
> error MT5209 : Native linking error : file not found: /Users/MyNameDocuments/TFS/MyComp/MyComp-dev/MyComp.iOS/obj/iPhone/Debug/mtouch-cache/libsqlcipher.a
> MTOUCH : error MT5202: Native linking failed. Please review the build log.

I have the linker set to Link Framework SDKs Only

**Comment by JKennedy24** [comment]
Building with Visual studio for mac in debug mode..

**Confirmed that rolling back to V1.1.11 fixes the issue**

**Comment by dgeller-OUHSC** [comment]
I am having what appears to be a problem using xamarin-android, both with SDK linking or no linking:

> System.DllNotFoundException: sqlcipher
> 12-21 11:11:34.151 I/mono-stdout(25371):   at (wrapper managed-to-native) SQLitePCL.SQLite3Provider_sqlcipher+NativeMethods.sqlite3_libversion_number()System.DllNotFoundException: sqlcipher

rolling back to 1.1.11 also fixes my issue.

**Comment by ericsink** [comment]
@dgeller-OUHSC The Android part of this issue is moved to #247

**Comment by ericsink** [comment]
@JKennedy24 Just curious: does this problem go away if you do a full clean of your build directories?

The error message mentions `libsqlcipher.a`, but in 1.1.12, the name of this file changed to `sqlcipher.a`, so I am wondering if something stale is sitting around referencing the old filename.

**Comment by JKennedy24** [comment]
looks like the fix for this issue has been merged. Is this in V1.1.13?

**Comment by ericsink** [comment]
Oops, sorry I forgot to clarify that with a comment here. Yes, this fix is in 1.1.13.

**Comment by JKennedy24** [comment]
Thanks @ericsink. I've just tested it out this end and seems to have fixed the issue
