### ISSUE TITLE
The unofficial sqlcipher builds for Android in 1.1.12 are broken

### ISSUE THREAD

**Issue by ericsink** [ericsink/SQLitePCL.raw#247]

**Comment by 1iveowl** [comment]
Is this why I get `System.DllNotFoundException: sqlcipher` when trying to compile on Android with Xamarin?

**Comment by ericsink** [comment]
@1iveowl If you are using 1.1.12, and if the problem goes away when you switch to 1.1.11, then yes, probably.

**Comment by 1iveowl** [comment]
Downgrading `SQLitePCLRaw.bundle_sqlcipher` to version 1.1.11 did indeed fix the issue for now.

Thank you

**Comment by corykroll** [comment]
Same issue with 1.1.12 here.  Going back to 1.1.11 fixed it.

**Comment by ericsink** [comment]
Fixed in version 1.1.13, which I just pushed to nuget.
