### ISSUE TITLE
Consider using NativeLibrary.Load()

### ISSUE THREAD

**Issue by bricelam** [ericsink/SQLitePCL.raw#248]
.NET Core 3.0 includes a new [NativeLibrary](https://github.com/dotnet/coreclr/blob/110835b1b818b333f27ab76db3f223a03027698a/src/System.Private.CoreLib/src/System/Runtime/InteropServices/NativeLibrary.cs) class that can be used instead of `LoadLibraryEx` and `dlopen`.

**Comment by ericsink** [comment]
Neato.

**Comment by ericsink** [comment]
https://ericsink.com/entries/native_library.html
