### ISSUE TITLE
1.1.12 shows SQLite 3.24 on iOS (3.26 expected)

### ISSUE THREAD

**Issue by vovodroid** [ericsink/SQLitePCL.raw#249]
It shows 3.26 on WIndows/Android, as expected, but in iOS it shows 3.24.

**Comment by ericsink** [comment]
This might mean you are somehow ending up with the iOS system SQLite instead of the ones bundled with SQLitePCLRaw. Recent versions of iOS include 3.24.0.

Can you provide more detail about which packages you are referencing in which projects?

**Comment by vovodroid** [comment]
>sqlite-net-pcl   1.5.231
SQLitePCLRaw.bundle_green   1.1.12
Microsoft.AppCenter.Crashes 1.12.0
Newtonsoft.Json   12.0.1
SkiaSharp   1.68.0
SkiaSharp.Views   1.68.0
SkiaSharp.Views.Forms   1.68.0
System.Reactive.Compatibility   4.1.2 
Xam.Plugins.Settings   3.1.1 
Xamarin.Forms 3.4.0.1009999 
Xamarin.Forms.Mocks   3.0.0.2 
ZXing.Net.Mobile   2.4.1 
ZXing.Net.Mobile.Forms   2.4.1 

sqlite-net-pcl   1.5.231 is linked to SQLitePCLRaw 1.1.11, using 3.22, so I added SQLitePCLRaw.bundle_green 1.1.12. It works on Windows/Android, but not for iOS, which uses 3
.24 also without explicitly adding SQLitePCLRaw.

**Comment by vovodroid** [comment]
Great, it's 3.26.0 now, thanks!
Is it ok to keep bundle_green for other platforms, or always include bundle_e_sqlite3?

**Comment by vovodroid** [comment]
Great, it's 3.26.0 now, thanks!
Is it ok to keep bundle_green for other platforms, or always include bundle_e_sqlite3?

**Comment by ericsink** [comment]
I usually recommend people use e_sqlite3 everywhere, but it won't make any practical difference here.  Except for iOS, the two bundles are identical.
