### ISSUE TITLE
Xamarin.Forms UWP, exception in SQLitePCLRaw.provider.e_sqlite3.dll

### ISSUE THREAD

**Issue by emigranto** [ericsink/SQLitePCL.raw#250]
Hi,
in the Xamarin.Forms project, I'm using sqlite.
And periodically the program crashes:
From the report:
`combase.dll
RoOriginateLanguageException() error.cpp:1522
System.Private.Interop.dll
System::Runtime::InteropServices::ExceptionHelpers OriginateLanguageException() ExceptionHelpers.cs:115
System.Private.Interop.dll
System::Runtime::InteropServices::ExceptionHelpers ReportUnhandledError() ExceptionHelpers.cs:883
System.Private.Interop.dll
Internal::Interop::InteropCallbacks ReportUnhandledError() InteropCallbacks.cs:17
System.Private.WinRTInterop.CoreLib
Internal::WinRT::Interop::WinRTCallbacks ReportUnhandledError() Interop.WinRT.cs:390
SharedLibrary.dll
System::RuntimeExceptionHelpers ReportUnhandledException() RuntimeExceptionHelpers.cs:154
SharedLibrary.dll
Internal::Runtime::Augments::RuntimeAugments ReportUnhandledException() RuntimeAugments.cs:896
SharedLibrary.dll
System::Threading::WinRTSynchronizationContext::Invoker InvokeCore$catch$0() SynchronizationContext.WinRT.cs:92
mrt100_app.dll
RhpCallCatchFunclet() exceptionhandling.asm:437
mrt100_app.dll
System::Runtime::EH DispatchEx() ExceptionHandling.cs:755
mrt100_app.dll
System::Runtime::EH RhThrowEx() ExceptionHandling.cs:617
mrt100_app.dll
RhpThrowEx() exceptionhandling.asm:191
SharedLibrary.dll
System::Runtime::ExceptionServices::ExceptionDispatchInfo Throw() ExceptionDispatchInfo.cs:63
SharedLibrary.dll
System::Runtime::CompilerServices::AsyncMethodBuilderCore::__c _ThrowAsync_b__7_0() AsyncMethodBuilder.cs:931
SharedLibrary.dll
System::Func$2_System::__Canon,System::Runtime::InteropServices::WindowsRuntime::EventRegistrationToken_ Invoke() Invoke:15732480
SharedLibrary.dll
System::Threading::WinRTSynchronizationContext::Invoker InvokeCore() SynchronizationContext.WinRT.cs:82
SharedLibrary.dll
System::Threading::WinRTSynchronizationContext::Invoker Invoke() SynchronizationContext.WinRT.cs:73
SharedLibrary.dll
System::Func$2_System::__Canon,System::Runtime::InteropServices::WindowsRuntime::EventRegistrationToken_ InvokeOpenStaticThunk() InvokeOpenStaticThunk:15732480
SQLitePCLRaw.provider.e_sqlite3.dll
SQLitePCL::rollback_hook_info call() Interop.WinRT.cs:381
Daphnis.UWP.McgInterop.dll
Windows::UI::Core::DispatchedHandler Invoke() Invoke:15732480
Daphnis.UWP.McgInterop.dll
__Interop::ReverseComStubs Stub_4() Stub_4:15732480
Daphnis.UWP.McgInterop.dll
Windows::UI::Core::DispatchedHandler__Impl::Vtbl Invoke__n() Invoke__n:15732480
Windows.UI.dll
Windows::UI::Core::CDispatcher ProcessInvokeItem() dispatcher.cpp:1266
Windows.UI.dll
Windows::UI::Core::CDispatcher ProcessMessage() dispatcher.cpp:270
Windows.UI.dll
Windows::UI::Core::CDispatcher WaitAndProcessMessagesInternal() dispatcher.cpp:1953
Windows.UI.dll
Windows::UI::Core::CDispatcher ProcessEvents() dispatcher.cpp:599
Windows.UI.Xaml.dll
CJupiterWindow RunCoreWindowMessageLoop() jupiterwindow.cpp:1246
Windows.UI.Xaml.dll
DirectUI::DXamlCore RunMessageLoop() dxamlcore.cpp:2452
twinapi.appcore.dll
Windows::ApplicationModel::Core::CoreApplicationView Run() coreapplicationview.cpp:422
twinapi.appcore.dll
_lambda_02cef69f8ae13d771fa47a74be974b8f_ operator() coreapplicationviewagilecontainer.cpp:1079
SHCore.dll
_WrapperThreadProc() thread.cpp:321
kernel32.dll
BaseThreadInitThunk() thread.c:64
ntdll.dll
RtlUserThreadStart() rtlstrt.c:1163`

Help me to understand the problem.

**Comment by emigranto** [comment]
I am use transactions. Yes, i use async/await.
Could that be the problem?

**Comment by ericsink** [comment]
Yes, that could be the problem. I’m pretty sure an async function cannot work when called from SQLite.

**Comment by emigranto** [comment]
Thank you! I will try the option without async/await.

**Comment by manlikenim** [comment]
I'm having a similar issue in https://github.com/ericsink/SQLitePCL.raw/issues/329. 

I'm using Microsoft.Data.Sqlite nuget package in a UWP app. This issue seems to be very similar but I don't understand how async/await are involved.

**Comment by manlikenim** [comment]
My has been solved now. For some reason, a test project missing package reference caused this when booting the app.
