### ISSUE TITLE
Consider using NuGet's new buildTransitive folder

### ISSUE THREAD

**Issue by bricelam** [ericsink/SQLitePCL.raw#252]
See [Allow package authors to define build assets transitive behavior](https://github.com/NuGet/Home/wiki/Allow-package--authors-to-define-build-assets-transitive-behavior).

This could help the situation where you have ProjectA -> ProjectB -> SQLitePCL.raw and e_sqlite3.dll isn't copied to the output directory of ProjectA.

**Comment by ericsink** [comment]
Oh that looks cool.

**Comment by bricelam** [comment]
Wahoo! I'm removing `PrivateAssets="none"` from Microsoft.Data.Sqlite in https://github.com/dotnet/efcore/pull/27191 which was in place to help mitigate this. (It propagated SQLitePCLRaw's `build` assets one more level into the user's project.)
