### ISSUE TITLE
Cross-target .NET Standard 2.0

### ISSUE THREAD

**Issue by bricelam** [ericsink/SQLitePCL.raw#253]
Per [this guidance](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting), libraries should cross-target .NET Standard 2.0 to avoid bringing in (when possible) the giant closure of .NET Standard 1.x packages.

**Comment by bricelam** [comment]
I tried to do a PR for this, but then I realized you're still using `project.json`...

**Comment by ericsink** [comment]
Yes, project.json at this point is rather shameful.  I just never got around to changing it.

I’ll try to give this some attention soon.

**Comment by bricelam** [comment]
I’m happy to help out too where I can. I think there was another issue about dropping PCL and/or other targets covered by netstandard too. It’s probably worth reconsidering all the targeted frameworks as part of migrating off project.json.

Would you consider dropping support for older platforms? What’s the lowest version of VS/NuGet you need to support?

I’ve also been thinking a lot about how we could leverage newer things like Span<T> and Utf8 to improve perf in areas, unfortunately this creates a bit of a maintainence cost if you also have to support older platforms.

There are also useful things like NativeLibrary and some NuGet features that could simplify the codebase if you’re able to raise the “minimum requirements”.

How big of a break are you willing to make? It’s painful, but Microsoft already put a stake in the ground saying C# 8 will only work on .NET Standard 2.1 which won’t be supported by .NET Framework. But it kind of makes sense now that you’ll be able to produce a self-contained WinForms/WPF exe using .NET Core 3 that runs everywhere .NET Framework is supported (but without actually requiring it to be installed). It’ll be interesting so see how everyone handles the transition...

**Comment by ericsink** [comment]
I totally agree with what you're saying.  I've been intending to make a big break along the lines you describe.  I just hadn't decided "when".  But I definitely feel like I've gone above and beyond the call by supporting Windows Phone 8 Silverlight for this long.  :-)

Also, since I've switched everything else I do over to PackageReference, working in this build system isn't much fun.

Recently I redid all the C builds and moved them out of gen_build.cs.  That was kinda the first step.

Anyway, the main question in my mind is how far to go.  Making netstandard 2.1 the minimum feels like maybe too far, but I'm staying open minded on that.

**Comment by bricelam** [comment]
Agreed about netstandard2.1. If EF Core didn’t need C# 8’s async foreach, staying on netstandard2.0 would be a no-brainer. But now we have to weigh the cost of either maintaining two implementations (either by cross-targeting or by supporting two versions), jumping to netstandard2.1 (and dropping net461), or waiting to support async foreach.

**Comment by bricelam** [comment]
cc @ajcvickers & @divega (FYI)

**Comment by ericsink** [comment]
Can you say something about the urgency of this issue?

As is my tendency, I tried a low-risk very-incremental approach, adding .NET Standard 2.0 to my current build system.  I ran into problems.

OTOH, I have started a new branch for version 2.0.  In that branch, .NET Standard 2.0 is simple.  See #255 

What I don't know yet is whether the V2 branch will stabilize in time to meet the need that prompted this issue.

If I need to, I can push through the difficulties of incorporating a .NET Standard 2.0 target into the current code.

**Comment by bricelam** [comment]
It’s not urgent.

EF Core today only supports .NET Standard 2.0 so dropping platforms in SQLitePCL.raw won’t be a breaking change for us. We can upgrade when it’s ready.

Are any other breaking changes planned for 2.0?
