### ISSUE TITLE
SQLitePCLRaw.bundle_zetetic Issue

### ISSUE THREAD

**Issue by developernotes** [ericsink/SQLitePCL.raw#260]
Hello @ericsink,

We are finalizing the next release of SQLCipher and noticed when we bump our dependency on `SQLitePCLRaw.bundle_zetetic` to `1.1.13`, the UAP target is including a dependency on `SQLitePCLRaw.lib.sqlcipher.windows`. Unfortunately, this breaks our integration when bundling the commercial builds of SQLCipher for Windows UAP.

We previously used `1.1.11` of `SQLitePCLRaw.bundle_zetetic` which does not take on the lib dependency for UAP, it appears to have been added in `1.1.12`.

It appears the other platform targets in that package do not depend on a `lib` package, was this intentional for other reasons? We are tentatively planning on rolling back to `1.1.11` but wanted to reach out to get your feedback.

Thank you,

**Comment by ericsink** [comment]
This was probably a mistake on my part.  I will investigate.

**Comment by ericsink** [comment]
Yep.  That was a bug.  Not sure how I managed that.

I suspect 1.1.11 is the best way for you to proceed.  The only other alternative would be for me to do a new release with this fix, but I am a little hesitant to go that way.  I could be talked into it.

**Comment by developernotes** [comment]
Hi @ericsink,

Thanks for the quick response, no need to make another release at this time for it, we can just run with 1.1.11 for now. If it could be adjusted for the next release that would be great. Thanks!

**Comment by ericsink** [comment]
SQLitePCLRaw 1.1.14, which includes the fix for this issue, has been pushed to nuget.org.

Feel free to reopen this issue if I didn't get it right.

**Comment by developernotes** [comment]
Hi @ericsink,

Thanks so much. We just [released](https://discuss.zetetic.net/t/sqlcipher-4-2-0-release/3702) SQLCipher 4.2.0 so we will look into 1.1.14 for our next release. Thanks again!
