### ISSUE TITLE
Row_Number() Funcation generates malformed SQL for SQCipher

### ISSUE THREAD

**Issue by JagdCrab** [ericsink/SQLitePCL.raw#261]
I'm using Microsoft.Data.Sqlite together with SQCipher and observed that whenever you would include row_number() Over(Partition by Order by) as a command text, SQLite would throw following exception: 
`SQLite Error 1: 'near "(": syntax error'.`

For test purpose, i've created a new project and tested Microsoft.Data.Sqlite without SQCipher first - command was executed successfully, then added bundle_sqcipher to project and same query now produces exception above. 

Code from test:

```
 static void Main(string[] args)
        {
            string connectionString = "Data Source=Test.db";
            using (SqliteConnection connection = new SqliteConnection(connectionString))
            {
                connection.Open();

                string sql;
                sql = "PRAGMA key = Test;";
                using (SqliteCommand command = new SqliteCommand(sql, connection))
                    command.ExecuteNonQuery();

                using (SqliteCommand command = connection.CreateCommand())
                {
                    command.CommandText = "Select row_number() Over(Partition by [Bar] Order by [Id] asc) n, [Id], [Bar] From [Foo];";
                    using (SqliteDataReader reader = command.ExecuteReader())
                        while (reader.Read())
                            Console.WriteLine(reader.GetInt32(0).ToString() + " " + reader.GetInt32(1).ToString() + " " + reader.GetInt32(2).ToString());
                }
            }
            Console.ReadLine();
        }
```

**Comment by JagdCrab** [comment]
OK, i've only now released that SQCipher is based on 3.20.1 version and window functions only appeared in 3.25.
Closed.

**Comment by ericsink** [comment]
Currently, my e_sqlite3 builds are based on SQLite 3.26.0

But my (unofficial) sqlcipher builds are based on SQLite 3.20.1

So without looking closely, my first guess is that the SQL statement is using a feature that was not in 3.20.1

**Comment by ericsink** [comment]
Ah, your comment came in just as mine did.  :-)

**Comment by sjlombardo** [comment]
@JagdCrab - If you have an immediate need for this functionality, official SQLCipher 4.1.0 builds are available [via Commercial Edition](https://www.zetetic.net/sqlcipher/buy/).
