### ISSUE TITLE
How to make case-insensitive search for non-ascii characters?

### ISSUE THREAD

**Issue by PavelK1988** [ericsink/SQLitePCL.raw#262]
Hello!

We have XamarinForms mobile app targeting Android, iOS and UWP, and one of our sqlite tables has 700 000 records.

Currently we use custom functions registered like
raw.sqlite3_create_function(_connection.Handle, "lower", 1, null, CustomSqliteFunctions.CustomLower), but performance of this is too bad on big amount of data.

Is it possible for you to make a build that supports ICU or is there any other workaround?

Thank you.

**Comment by ericsink** [comment]
The last time I looked at ICU, it seemed like it would be a significant undertaking for me to incorporate it into my build system.  I'll give this another look, but I don't think it's likely I will want to support sqlite/ICU builds.

If you want to integrate your own build, I can provide some guidance on how to do this with SQLitePCL.raw.  But currently this is not a simple task.  I have been working on a v2 release, and using custom SQLite builds should be easier in v2.

**Comment by PavelK1988** [comment]
Is it possible to use Sqlite provided by iOS or Android?
I have read that it supports ICU out of the box on Android API 21 and higher, not sure about iOS.

Thank you very much!

**Comment by ericsink** [comment]
Android does not allow direct access to the SQLite library instance that is in the OS.  See my blog entry on that topic:

https://ericsink.com/entries/sqlite_android_n.html

**Comment by ericsink** [comment]
Dupe of #146
