### ISSUE TITLE
How to force TableQuery.Where to generate a query with sql LIKE expression

### ISSUE THREAD

**Issue by brano1** [ericsink/SQLitePCL.raw#264]
Hello,

My problem is a performance of full-text search in large tables (up to 1000000 records). Performance of LIKE in our sql queries is much better than performance of INSTR(LOWER()) that gets generated when we're using C# String.Contains for a predicate expression. Can we use some other C# expression to generate LIKE sql expression?

Thanks for your answer.

**Comment by ericsink** [comment]
This issue looks like it somehow ended up in the wrong repo.
