### ISSUE TITLE
SQLitePCLRaw.bundle_green Dependencies linux and osx?

### ISSUE THREAD

**Issue by generik0** [ericsink/SQLitePCL.raw#265]
Hi

Why would you put osx, linus and xp dependencies in SQLitePCLRaw.bundle_green.
Especially for net framework packages?
This can cause nuget/build issues... And why would we want to automatically have linux/osx for something that only runs on windows (i.e. net framework "stuff").

![image](https://user-images.githubusercontent.com/2411563/56119373-4d547c80-5f6c-11e9-9dd0-a64c6b17f3fa.png)

**Comment by ericsink** [comment]
Because the .NET Framework TFMs are the way mono identifies itself.

I agree that the situation is unfortunate.

**Comment by generik0** [comment]
Hmmm. But you have the droid and iOS or linux you should install on the parent / host project, getting the correct package in.
This solution here causes sometimes build issues.

**Comment by ericsink** [comment]
Can you be more specific?  What build issues?

**Comment by generik0** [comment]
@ericsink I needded time to  inveestigate.
The issues was simple.
The build server is not open to nuget.org. We have a package server,
And the linux version was not available..

I still think it is unfortunate that the SQLitePCLRaw.bundle_green depends on the linux, iosx, droid etc..
Maybe you could rethink?

**Comment by ericsink** [comment]
"Maybe you could rethink?"

Based on the information I have, no.

The dependencies have been this way for years.  Changing the definition of this bundle would break things for many users.

And I don't see a reason why.  It's a bundle.  It's purpose is to bring in dependencies for all platforms.  For all cases where it is problematic, the solution is to not use the bundle and instead use a subset of the individual packages it depends on.
