### ISSUE TITLE
Ability to get the native library name

### ISSUE THREAD

**Issue by bricelam** [ericsink/SQLitePCL.raw#271]
My [clever hack](https://github.com/aspnet/EntityFrameworkCore/blob/0bbb297a05185b28885a822a1f0c993cb826386c/src/Microsoft.Data.Sqlite.Core/Extensions/SQLitePCLExtensions.cs#L16-L33) no longer works in v2 with SQLite3Provider_StdCall. We'd love a supported way to get the native image name (e_sqlite3, e_sqlcipher, sqlite3, etc.)

Today, we use this for two things:
- To throw when we know encryption for sure isn't supported (i.e. it's e_sqlite3)
- To test that [encryption works](https://github.com/aspnet/EntityFrameworkCore/blob/0bbb297a05185b28885a822a1f0c993cb826386c/test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs#L263-L319) on e_sqlcipher

**Comment by ericsink** [comment]
(1)  I can add a method to ISQLite3Provider to return (a) the name used for DllImport, or (b) for the dynamic provider, the name that was given for searching.

(2)  Not sure if it'll work in your situation(s), but according to Zetetic, the best way to check to see if the SQLite library is actually SQLCipher is "PRAGMA cipher_version".  Example in `src/common/tests_xunit.cs`

(3)  At the moment, the dynamic provider (which uses System.Runtime.InteropServices.NativeLibrary as mentioned in #248) is used for .NET Core 3.0 but not for 2.2 and earlier.  We *could* favor consistency and change and use the DllImport provider for .NET Core 3.0 as well, but in general, the shift toward dynamic load seems to me like a positive thing.  Anyway, I just wanted to mention the possibilities here.

**Comment by ericsink** [comment]
Does 7f01f83 look like what you need?

**Comment by bricelam** [comment]
Perfect. 👌

**Comment by ericsink** [comment]
@bricelam I pushed up another pre-release.  It contains GetLibraryName() and it resurrects `sqlite3_trace()` and `sqlite3_profile()`.  The `sqlite3_trace_v2()` stuff is still there, but should be considered a half-done feature.
