### ISSUE TITLE
binskim.exe throws Control Flow Guard errors on e_sqlite3

### ISSUE THREAD

**Issue by vonders** [ericsink/SQLitePCL.raw#278]
The following error is thrown when analysing e_sqlite3.dll in binskim.exe
error BA2008: 'e_sqlite3.dll' does not enable the control flow guard (CFG) mitigation. To resolve this issue, pass /GUARD:CF on both the compiler and linker command lines. Binaries also require the /DYNAMICBASE linker option in order to enable CFG.

Control Flow Guard (CFG) should be enabled in release mode by default

**Comment by ericsink** [comment]
See:

ericsink/cb@902d79e0c4714c4472309759230d58c936555119

**Comment by vonders** [comment]
Thanks, will this be available in a SQLitePCLRaw.bundle_green at some point? regards

**Comment by ericsink** [comment]
Yes, this will be part of the 2.0 release, coming soon. #255

**Comment by ericsink** [comment]
This should be fixed in 2.0.1, which has been pushed up to nuget.org.
