### ISSUE TITLE
Bundle_sqlcipher yields server version 3.20.1

### ISSUE THREAD

**Issue by adrianhara** [ericsink/SQLitePCL.raw#280]
Hi,

First off, thanks a lot for the great work and making it easier to (magically) use sqlite 😸 

I have a question about the bundles. We're using EF Core 2.2.4 with SQLite in a WPF Windows Desktop app (.net 4.6.2). While trying to implement migrations, I noticed that the rename column SQLite functionality didn't work. Upon further investigation, it turns out that after opening a connection and calling `.ServerVersion` I get `3.20.1` which doesn't support rename column. Maybe you can help me figure out why the ServerVersion is so old.

Here's the setup:

- Installed NuGet packages: `SQLitePCLRaw.core` 1.1.14, `SQLitePCLRaw.bundle_green` 1.1.14, `SQLitePCLRaw.bundle_sqlcipher` 1.1.14 (according to the [release notes](https://www.nuget.org/packages/SQLitePCLRaw.bundle_sqlcipher/) this should bring in server 3.28.0)
- I'm calling `SQLitePCL.Batteries_V2.Init();`

I noticed that if I remove the `SQLitePCLRaw.bundle_sqlcipher` package and call `SQLitePCL.Batteries.Init();` (which if I understand correctly will use the e_sqlite3 dll brought in by `SQLitePCLRaw.bundle_green`) then the `ServerVersion` is indeed `3.28.0`. Since we'd like to encrypt the DB, I guess I need to use the `SQLitePCLRaw.bundle_sqlcipher` package, but that yields a  `ServerVersion` of `3.20.1` 😞 

I tried cleaning the solution, removing the `SQLitePCLRaw.bundle_sqlcipher` package and adding it back, no effect.

Any idea what I'm doing wrong?

**Comment by ericsink** [comment]
You're not doing anything wrong.

Well actually, you should never have two bundles in the same project, so either use bundle_green or bundle_sqlcipher, but not both.  Still, that is not the source of this problem.

The problem here is just what it looks like: my unofficial SQLCipher builds (from bundle_sqlcipher) are actually older.

Short answer:  SQLitePCLRaw version 2.0 is currently in pre-release and available on nuget.org.  And in 2.0, the SQLCipher builds have been updated.  But do see the draft release notes:

https://github.com/ericsink/SQLitePCL.raw/blob/v2/v2.md

**Comment by adrianhara** [comment]
Thanks for the answer!

Regarding the two bundles: I can't remove the bundle_green as EF Core depends on it. So I guess it'll just have to stay there, even though not used.

Regarding the SQLCipher build: does this mean the release notes of 1.1.14 are incorrect? Or am I reading it wrong? `1.1.14:  update e_sqlite3 builds to 3.28.0`

Regarding upgrading to 2.0: could you please give me a bit more info how I should go about doing this? Specifically:

- I just upgraded `SQLitePCLRaw.core` and `SQLitePCLRaw.bundle_green` to `2.0.0-pre-...13`
- however Visual Studio doesn't show a similar 2.0 version (or any 2.0 version) for `SQLitePCLRaw.bundle_sqlcipher`. I do need this bundle if I want to encrypt the DB, right?
- after upgrading as mentioned above opening the connection throws `Method not found: 'System.String SQLitePCL.raw.sqlite3_errstr(Int32)'`

**Comment by ericsink** [comment]
"So I guess it'll just have to stay there, even though not used."

Keeping bundle_green in your solution WILL cause problems.

1.  I think the Entity Framework team publishes a second version of their SQLite package which does *not* depend on bundle_green, but rather, on SQLitePCLRaw.core, for exactly this situation.  That said, at the moment I can't remember the package ID.

2.  If you want (or need) to keep bundle_green due to the transitive dependency, you can exclude it by adding:

```
<PackageReference Include="SQLitePCLRaw.bundle_green">
<Version>1.*</Version>
<ExcludeAssets>All</ExcludeAssets>
</PackageReference>
```

**Comment by ericsink** [comment]
"Regarding the SQLCipher build: does this mean the release notes of 1.1.14 are incorrect? Or am I reading it wrong?"

The 1.1.4 release notes are correct, although perhaps confusing.  The name "e_sqlite3" refers to the SQLite builds, not to the SQLCipher builds.

**Comment by ericsink** [comment]
"however Visual Studio doesn't show a similar 2.0 version (or any 2.0 version) for SQLitePCLRaw.bundle_sqlcipher."

In 2.0, the name of the unofficial SQLCipher builds has changed to `e_sqlcipher`, so the name of its bundle has changed to SQLitePCLRaw.bundle_e_sqlcipher.

"after upgrading as mentioned above opening the connection throws Method not found: 'System.String SQLitePCL.raw.sqlite3_errstr(Int32)'"

Ouch.  This comment made me realize:  SQLitePCLRaw 2.0 is not compatible with EF Core 2.2.4.  If you update to SQLitePCLRaw 2.0, you would also need to update to EF Core 3.0 preview 7, which isn't out yet.

Sorry about that.  I should have remembered that and said it sooner.

For now, SQLitePCLRaw 2.0 won't really help you, except as a sign that a fix is on the horizon.

**Comment by adrianhara** [comment]
It looks like the package which doesn't pull in `bundle_green` is `Microsoft.EntityFrameworkCore.Sqlite.Core`.

**Comment by adrianhara** [comment]
Hmm I see 😞 Does this mean then my only alternative is to:

1. Stick with EF Core 2.2.4
2. Install `SQLitePCLRaw.core`  `1.1.14`
3. Download a build of sqlcipher myself that's newer than what's in the `bundle_sqlcipher`
4. Load that up manually for `SQLitePCLRaw` instead of using the batteries included option?

Would that work?

**Comment by ericsink** [comment]
Yes, that approach would work, for certain meanings of"Download a build of sqlcipher myself".

The easiest way would be to just buy an official SQLCipher build from Zetetic.  They have packages that work with SQLitePCLRaw.

Another way would be to grab this nuget package:

https://www.nuget.org/packages/SQLitePCLRaw.lib.e_sqlcipher/2.0.0-pre20190628101813

unzip it, and find the `e_sqlcipher.dll` you want, and rename it to `sqlcipher.dll`.

I'm pretty sure that, aside from the name change, those SQLCipher builds are fully compatible with SQLitePCLRaw 1.1.14.

**Comment by adrianhara** [comment]
Great, thanks, I'll give the options a try, in the reverse order 😄 (get from package, then if that fails buy it from Zetetic). Could you please point me to the right NuGet custom provider package I should be using? I guess it's something with `SQLitePCLRaw.provider.custom.<something>` where I'm not sure about the `<something>` part.

**Comment by ericsink** [comment]
Probably this one:

https://www.nuget.org/packages/SQLitePCLRaw.provider.sqlcipher.net45/

**Comment by adrianhara** [comment]
Thanks, I'll give it a try Monday. One more question: with what threading option is your build built? (https://sqlite.org/threadsafe.html) Serialized?

**Comment by ericsink** [comment]
(Sorry for the delay in reply)

Yes, serialized.  More to the point, my build scripts don't set SQLITE_THREADSAFE, and serialized is the default.

The build scripts are in the ericsink/cb repo.

**Comment by Kation** [comment]
> Yes, that approach would work, for certain meanings of"Download a build of sqlcipher myself".
> 
> The easiest way would be to just buy an official SQLCipher build from Zetetic. They have packages that work with SQLitePCLRaw.
> 
> Another way would be to grab this nuget package:
> 
> https://www.nuget.org/packages/SQLitePCLRaw.lib.e_sqlcipher/2.0.0-pre20190628101813
> 
> unzip it, and find the `e_sqlcipher.dll` you want, and rename it to `sqlcipher.dll`.
> 
> I'm pretty sure that, aside from the name change, those SQLCipher builds are fully compatible with SQLitePCLRaw 1.1.14.

Is that same with android and ios?
I replace `SQLitePCLRaw.lib.sqlcipher.android` with `SQLitePCLRaw.lib.e_sqlcipher.android` and make a private package, but it throw `DllNotFoundException` with `'sqlcipher assembly:<unknown assembly> type:<unknown type> member:(null)'`
And IOS show error with `native linking failed, undefinded symbol`.

Is there any solution to use new sqlcipher version from 1.1.14?
