### ISSUE TITLE
Help Akavache transition to v2

### ISSUE THREAD

**Issue by ericsink** [ericsink/SQLitePCL.raw#282]
Looks like maybe @glennawatson is the right person to tag here.

**Comment by glennawatson** [comment]
I can help in a pinch but Akavache has traditionally been @pureween baby.

**Comment by ericsink** [comment]
Ah, yes, I should have remembered that.

@PureWeen There are some minor breaking changes in SQLitePCLRaw 2.0, but the transition should involve very little pain.

**Comment by ericsink** [comment]
See reactiveui/Akavache#496

**Comment by worldbeater** [comment]
Not sure if this is related or not, but after upgrading `Akavache` from `v6.5.20` to `v6.7.1` and `SQLitePCLRaw.bundle_e_sqlite3` from `v1.1.14` to `v2.0.0` when trying to initialize Akavache I get the following exception:
```
Unhandled exception: System.TypeInitializationException: The type initializer for "Akavache.BlobCache" threw an exception. ---> System.ArgumentException: Path is invalid.
   in System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   in System.IO.Path.InternalGetDirectoryName(String path)
   in SQLitePCL.NativeLibrary.MakePossibilitiesFor(String basename, Assembly assy, Int32 flags, LibSuffix suffix)
   in SQLitePCL.NativeLibrary.MyLoad(String basename, Assembly assy, Int32 flags, Action`1 log)
   in SQLitePCL.NativeLibrary.Load(String libraryName, Assembly assy, Int32 flags)
   in SQLitePCL.Batteries_V2.MakeDynamic(String name, Int32 flags)
   in SQLitePCL.Batteries_V2.DoDynamic_cdecl(String name, Int32 flags)
   in SQLitePCL.Batteries_V2.Init()
   in Akavache.Registrations.Register(IMutableDependencyResolver resolver, IReadonlyDependencyResolver readonlyDependencyResolver)
   in Akavache.DependencyResolverMixin.InitializeAkavache(IMutableDependencyResolver resolver, IReadonlyDependencyResolver readonlyDependencyResolver)
   in Akavache.BlobCache.<>c.<.cctor>b__9_0()
   in Splat.InternalLocator.RegisterResolverCallbackChanged(Action callback)
   in Splat.Locator.RegisterResolverCallbackChanged(Action callback)
   in Akavache.BlobCache..cctor()
```
The exception is thrown from here:
https://github.com/worldbeater/Camelotia/blob/misc-updates/src/Camelotia.Presentation.Wpf/App.xaml.cs#L24
Planning to investigate what's causing this later, but any ideas of what could go wrong with Akavache are appreciated. The repro is [here](https://github.com/worldbeater/Camelotia/tree/misc-updates), `misc-updates` branch, `Camelotia.Presentation.Wpf` project. Akavache initializes without exceptions when targeting .NET Core (Avalonia) or UWP.

**Comment by ericsink** [comment]
At first glance, this looks like a bug in SQLitePCLRaw.  A bug that is specific to .NET Framework.  I need to look more closely.
