### ISSUE TITLE
NuGet errors since version 2.0.0 was released out of "pre " state

### ISSUE THREAD

**Issue by UweKeim** [ericsink/SQLitePCL.raw#283]
Since version 2.0.0 was released, 19 hours ago, my build script does not work anymore.

It fails with the error message:

> Could not install package 'SQLitePCLRaw.bundle_green 2.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

The full command line I'm executing is:

```cmd
"C:\MyCode\Source\nuget.exe" Update "C:\MyCode\Source\Core\Main\Main.csproj" -NonInteractive -RepositoryPath "C:\MyCode\Source\Core\packages"
```

And the output is:

```text
Attempting to gather dependency information for multiple packages with respect to project 'C:\MyCode\Source\Core\Main\Main.csproj', targeting '.NETFramework,Version=v4.5.2'
Gathering dependency information took 4,76 sec
Applying constraint '(<= 2.3.0)' defined in 'packages.config'.
Applying constraint '(<= 1.3.1)' defined in 'packages.config'.
Applying constraint '(<= 1.0.0.8)' defined in 'packages.config'.
Attempting to resolve dependencies for multiple packages.
Resolving dependency information took 0 ms
Resolving actions install multiple packages
Retrieving package 'SQLitePCLRaw.bundle_green 2.0.0' from 'nuget.org'.
Retrieving package 'SQLitePCLRaw.core 2.0.0' from 'nuget.org'.
Removed package 'SQLitePCLRaw.bundle_green 1.1.14' from 'packages.config'
Successfully uninstalled 'SQLitePCLRaw.bundle_green 1.1.14' from Main
Removed package 'SQLitePCLRaw.core 1.1.14' from 'packages.config'
Successfully uninstalled 'SQLitePCLRaw.core 1.1.14' from Main
WARNING: Install failed. Rolling back...
WARNING: Package 'SQLitePCLRaw.bundle_green 2.0.0' does not exist in project 'Main'
Package 'SQLitePCLRaw.core 1.1.14' already exists in folder 'C:\MyCode\Source\Core\packages'
Added package 'SQLitePCLRaw.core 1.1.14' to 'packages.config'
Package 'SQLitePCLRaw.bundle_green 1.1.14' already exists in folder 'C:\MyCode\Source\Core\packages'
Added package 'SQLitePCLRaw.bundle_green 1.1.14' to 'packages.config'
Executing nuget actions took 259,33 ms
Could not install package 'SQLitePCLRaw.bundle_green 2.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

### My question:

Any chance to avoid putting a version constraint into my packages configuration file?

**Comment by UweKeim** [comment]
As I've written above, the following inside "packages.config" helps avoiding this issue:

```xml
<package id="SQLitePCLRaw.bundle_green" version="1.1.14" targetFramework="net452" allowedVersions="(,2.0)" />
```

[The `allowedVersion` is described in the Microsoft documentation](https://docs.microsoft.com/en-us/nuget/reference/package-versioning#version-ranges-and-wildcards).

Of course, I would love to avoid this.

**Comment by ericsink** [comment]
SQLitePCLRaw 2.0 requires .NET Standard 2.0, so it is not compatible with .NET 4.5.2.  

When you run the "update" command of nuget.exe, it tries to update all your packages to their latest versions.  Doing this as part of a build script is a practice I would consider to be risky.  Most people want to update their dependencies with a more explicit/manual action.

Anyway, if you need to stay with net452, and if you want to continue using "nuget update", then you need to force it to stay with SQLitePCLRaw 1.x, so your allowedVersions approach seems like the right fix.

**Comment by UweKeim** [comment]
Why not put constraints right into the NuGet package to not even show my project with .NET 4.5.2 the NuGet package 2.0.0?

**Comment by ericsink** [comment]
> Why not put constraints right into the NuGet package to not even show my project with .NET 4.5.2 the NuGet package 2.0.0?

I don't think there's a way to do that.

The package already has the things necessary to declare what TFMs it can support.  It does not claim support for net452.  Since you are attempting to install it in a net452 project, you get an error, and that's what should happen.

What you're describing would be somewhat like a different behavior of "nuget update".  Instead of updating every package to the latest version, it would update every package to the highest version that supports a given TFM.  This would require it to grab the latest version, check for compatibility, and walk backwards until it finds one.  Anyway, that's apparently not how "nuget update" works.

**Comment by UweKeim** [comment]
Thanks for clarifying, Eric!
