### ISSUE TITLE
Make sure SQLitePCLRaw 2.0 works with official SQLCipher builds from Zetetic

### ISSUE THREAD

**Issue by ericsink** [ericsink/SQLitePCL.raw#284]
This needs to be tested.

Cc @sjlombardo @developernotes

**Comment by sjlombardo** [comment]
Hi @ericsink - we're planing to test this out early next week.

**Comment by sjlombardo** [comment]
Hi @ericsink, sorry this took longer than expected, but we just finished up baseline testing the official SQLcipher builds with SQLitePCLRaw.bundle_zetetic 2.0.1 on Xamarin iOS, Xamarin Android, Xamarin Mac, Windows UAP, .NET Core and .NET Framework projects. Everything is looking good so far. We'll let you know if anything crops up. Thanks so much for updating bundle_zetetic to 2.0!

**Comment by ericsink** [comment]
Yay!

**Comment by ericsink** [comment]
Closing old/stale issue.
