### ISSUE TITLE
Investigate problem with missing symbols in UWP build AOT

### ISSUE THREAD

**Issue by ericsink** [ericsink/SQLitePCL.raw#286]
Trying to upgrade to the latest version `3.0.0-preview7.19362.6` of `Microsoft.Data.SQLite` causes these warnings to appear when building my ARM64 app:

```
19>C:\Users\foo\.nuget\packages\microsoft.net.native.compiler\2.2.3\tools\Microsoft.NetNative.targets(801,5): warning :
       MCG : warning MCG0004: The method 'sqlite3_key' was not found in module 'e_sqlite3' specified by DllImport method 'System.Int32 SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_key(SQLitePCL.sqlite3, System.Byte*, System.Int32)'. Calling this method would throw exception at runtime.
19>C:\Users\foo\.nuget\packages\microsoft.net.native.compiler\2.2.3\tools\Microsoft.NetNative.targets(801,5): warning :
       MCG : warning MCG0004: The method 'sqlite3_key_v2' was not found in module 'e_sqlite3' specified by DllImport method 'System.Int32 SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_key_v2(SQLitePCL.sqlite3, System.Byte*, System.Byte*, System.Int32)'. Calling this method would throw exception at runtime.
19>C:\Users\foo\.nuget\packages\microsoft.net.native.compiler\2.2.3\tools\Microsoft.NetNative.targets(801,5): warning :
       MCG : warning MCG0004: The method 'sqlite3_rekey' was not found in module 'e_sqlite3' specified by DllImport method 'System.Int32 SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_rekey(SQLitePCL.sqlite3, System.Byte*, System.Int32)'. Calling this method would throw exception at runtime.
19>C:\Users\foo\.nuget\packages\microsoft.net.native.compiler\2.2.3\tools\Microsoft.NetNative.targets(801,5): warning :
       MCG : warning MCG0004: The method 'sqlite3_rekey_v2' was not found in module 'e_sqlite3' specified by DllImport method 'System.Int32 SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_rekey_v2(SQLitePCL.sqlite3, System.Byte*, System.Byte*, System.Int32)'. Calling this method would throw exception at runtime.
```

Also, running my app against this version causes the following exception:

```
    Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.Data.Sqlite.dll
SQLite Error 14: 'unable to open database file'.
```

_Originally posted by @RehanSaeed in https://github.com/ericsink/SQLitePCL.raw/issues/254#issuecomment-520425683_

**Comment by shibayan** [comment]
This warning seems to be caused by `e_sqlite3.dll` not exporting `sqlite3_key` and etc.

I investigated using `dumpbin /exports e_sqlite3.dll`, but I couldn't find functions that warned me.

**Comment by ericsink** [comment]
Try this prerelease package:

https://www.nuget.org/packages/SQLitePCLRaw.lib.e_sqlite3/2.0.1-pre20190815133105

**Comment by shibayan** [comment]
Thank you. When I installed the package, all warnings were gone.

**Comment by ericsink** [comment]
This should be fixed in 2.0.1, which has been pushed up to nuget.org.

**Comment by RehanSaeed** [comment]
I'm using `Microsoft.Data.Sqlite` in a UWP app and can't wait for them to upgrade their package (if they're ever going to do that). Is it possible to upgrade the SQLitePCLRaw package while sticking to the latest `Microsoft.Data.Sqlite` which uses the old version? When I try to add version 2.0.1 of this package, I get the following error:

> Error APPX1101: Payload contains two or more files with the same destination path 'e_sqlite3.dll'. Source files: C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\sqlitepclraw.lib.e_sqlite3\2.0.1\runtimes\win10-x86\nativeassets\uap10.0\e_sqlite3.dll C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\sqlitepclraw.lib.e_sqlite3.v140\1.1.12\runtimes\win10-x86\native\e_sqlite3.dll"

**Comment by ericsink** [comment]
No, you can't mix SQLitePCLRaw 1.x and 2.x in the same project.  

Microsoft.Data.SQLite 3.0 will be released in just a few weeks and it uses SQLitePCLRaw 2.0.

Preview releases are available now:

https://www.nuget.org/packages/Microsoft.Data.SQLite/3.0.0-preview8.19405.11
