### ISSUE TITLE
Attempts to get SQLite to use files outside the UWP sandbox

### ISSUE THREAD

**Issue by ericsink** [ericsink/SQLitePCL.raw#287]
Let "Foo" = whatever API calls are needed to deal with the concerns addressed in this issue.  Having no experience with trying to use UWP outside its sandbox, I don't really know anything about Foo, but I know where Foo has to fit into the puzzle.

There are, as far as I can tell, two ways to address this:

(1)  Modify SQLite itself to change its built-in Windows VFS implementation to support Foo.  I don't actually know if this is feasible.  That VFS is written in C and maintained by the SQLite team.  You would have to talk to them about whether this can be done.

(2)  (a) Add VFS support to SQLitePCLRaw and, (b) use that to write a new VFS, implemented with .NET, and (c) fix that VFS to support Foo.

I have made some progress on (2a).  It's in the `vfs` branch over in the SQLitePCLRaw repo.

However, (2b) is a very large piece of work.  It's somewhat simpler if the WAL mode feature is omitted, but that's pretty important.

PS.  Actually, if you want to really get your hands dirty, in principle, (1) could be done without cooperation from the SQLite team.  Just take the source code for the Windows VFS from SQLite (it's in os_win.c) and make the necessary changes to add Foo, then build your own custom SQLite with that VFS replacing the built-in one.  I'm not saying this would be easy.

Note that this whole issue has nothing to do with sqlite-net, and except for the possibility of using some sort of VFS feature as described in item (2), it doesn't really have much to do with SQLitePCLRaw either.  Nonetheless, I'm interested in tracking any possible progress on this matter, so after I post this comment, I'm going to open a corresponding issue in the SQLitePCLRaw repo.

_Originally posted by @ericsink in https://github.com/praeclarum/sqlite-net/issues/756#issuecomment-522602322_

**Comment by osolo** [comment]
@ericsink You don't need to write a full vfs for this.  To get Sqlite to play nice with UWP, you only need a few lines of C code to coerce the existing vfs to use the UWP-aware versions of the file management functions:

```c
#pragma comment(lib, "WindowsApp.lib")

#include <windows.h>
#include "sqlite3.h"

SQLITE_API void sqlite3_uwp_init()
{
    sqlite3_vfs* pVfs = sqlite3_vfs_find("win32");
    pVfs->xSetSystemCall(0, "DeleteFileW", (sqlite3_syscall_ptr)DeleteFileFromAppW);
    pVfs->xSetSystemCall(0, "GetFileAttributesExW", (sqlite3_syscall_ptr)GetFileAttributesExFromAppW);
    pVfs->xSetSystemCall(0, "CreateFile2", (sqlite3_syscall_ptr)CreateFile2FromAppW);
}
```

This can be easily done in a stub file ([like the one you have here](https://github.com/ericsink/cb/blob/master/stubs/stubs.c)).  

Technically this can also be done from C#, but I don't believe you currently define the `sqlite3_vfs` structure in C# at the moment.

**Comment by ericsink** [comment]
@osolo Interesting.

I do have a branch ('vfs') which contains some progress on the sqlite3_vfs structure support, but I have not merged it into master yet.

**Comment by ericsink** [comment]
Closing old/stale issue.
