### ISSUE TITLE
SQLitePCLRaw.lib.e_sqlcipher.android nuget contains both libsqlcipher.so and libe_sqlcipher.so

### ISSUE THREAD

**Issue by tranb3r** [ericsink/SQLitePCL.raw#295]
SQLitePCLRaw.lib.e_sqlcipher.android nuget contains both libsqlcipher.so and libe_sqlcipher.so (in SQLitePCLRaw.lib.e_sqlcipher.android.dll).
As a consequence, both libs are added to my android app.
I was expecting to find only libe_sqlcipher.so. Is it a bug ?
Version 2.0.1 and 2.0.2-pre20190904113843

**Comment by ericsink** [comment]
I can't find evidence of this.  Could the old libsqlcipher.dll be left from previous builds?  Try cleaning the build output directory and see if it shows up again?

**Comment by tranb3r** [comment]
No it's in the nuget. I'm not building anything...
The so libs are embedded within the dll.

**Comment by ericsink** [comment]
Hmmm.

I just can't figure HOW it got there.

https://github.com/ericsink/SQLitePCL.raw/blob/master/src/SQLitePCLRaw.lib.e_sqlcipher.android/SQLitePCLRaw.lib.e_sqlcipher.android.csproj

**Comment by ericsink** [comment]
Yep, you're right -- they're both in there.  And yes, that's a bug.  Still not sure how that happened, but I'll figure it out...

**Comment by ericsink** [comment]
Ha!  I was right, the problem was leftover stuff from previous builds.  But that problem was in MY tree, not yours.  :-)

Thanks for the bug report.

**Comment by ericsink** [comment]
I just pushed up version 2.0.2-pre20191018090318 to nuget.org, which contains a fix for this problem.

**Comment by ericsink** [comment]
2.0.2 is out

**Comment by thulsa** [comment]
and this means what, exactly?  I have the same issues with the VS2022 community edition, the latest updated.

XA0141: NuGet package '<unknown>' version '<unknown>' contains a shared library 'libe_sqlcipher.so' which is not correctly aligned. See https://developer.android.com/guide/practices/page-sizes for more details

what package and how to fix?
