### ISSUE TITLE
Should SQLite.raw protect against managed delegates throwing exceptions?

### ISSUE THREAD

**Issue by bordoley** [ericsink/SQLitePCL.raw#30]
SQLite.raw supports using managed delegates for several sqlite functions:
  * sqlite3_create_function
  * sqlite3_create_collation
  * sqlite3_commit_hook
  * sqlite3_progress_handler (hopefully in a near future release).

As I recall the current code doesn't protect against exceptions being thrown by these functions. Should it? Is there any kind of data corruption risk if an exception goes unhandled, perhaps caught by managed code but crashing the native sqlite code? 

Specifically sqlite3_create_function callbacks can call sqlite3_result_error and sqlite3_result_error_code to communicate error cases. Should the library catch exceptions and call these to communicate an error. The downside of course is that the managed exception is swallowed in this case and you would lose the managed stack trace.

**Comment by bordoley** [comment]
Any thoughts on this? I'm not sure if this is an issue or not.

**Comment by ericsink** [comment]
For now, I don't plan to change this unless we have a compelling reason to do so.
