### ISSUE TITLE
Can this be used with ADO.net ?

### ISSUE THREAD

**Issue by pha3z** [ericsink/SQLitePCL.raw#305]
I want to use the ADO.net approach to providing a DbProvider. I want to be able to make my application run agnostic to sqlite or another sql database.

Apache shows an example of how to use System.Data.Sqlite.DLL with ADO.net here:
[http://system.data.sqlite.org/index.html/artifact/96f3932f9f371cca](http://system.data.sqlite.org/index.html/artifact/96f3932f9f371cca)

But I can't figure out how to do it with the Green Bundle or with the SqlitePcl Raw lib in general.

Do you know how to do this?

I made an attempt to wire up things manually (forgoing the proper ADO.net workflow), but I can't even figure how to properly use the Green Bundle after I call Batteries.Init().  Once I've initialized it, what do I actually do to get a reference to a database instance to start working with?

**Comment by ericsink** [comment]
For an ADO.NET API built on this library, use Microsoft.Data.Sqlite instead of System.Data.Sqlite.

**Comment by bricelam** [comment]
NuGet Package: https://www.nuget.org/packages/Microsoft.Data.Sqlite
API Docs: https://docs.microsoft.com/dotnet/api/microsoft.data.sqlite
Samples: https://github.com/aspnet/EntityFrameworkCore/tree/master/samples/Microsoft.Data.Sqlite

**Comment by pha3z** [comment]
Thank you. Immensely helpful!

**Comment by bricelam** [comment]
Docs: https://docs.microsoft.com/dotnet/standard/data/sqlite/
