### ISSUE TITLE
Assembly number of 0.7 release is still 0.6.1

### ISSUE THREAD

**Issue by bordoley** [ericsink/SQLitePCL.raw#31]
I noticed that in the most recent release for some reason the assembly version is still 0.6.1. Not 0.7. 

https://github.com/ericsink/SQLitePCL.raw/blob/master/src/cs/AssemblyInfo.cs

**Comment by bordoley** [comment]
Noticed you bumped the version number. Wanted to ping on this in case you do another release :)

**Comment by ericsink** [comment]
Yeah, thanks for the reminder.  This commit was just a test for somebody.

E
