### ISSUE TITLE
SQLitePCLRaw.provider.e_sqlite3.uwp10 update the dependency

### ISSUE THREAD

**Issue by henry-wei** [ericsink/SQLitePCL.raw#311]
sqlite3 had released the 3.30 version, but the latest NuGet package of 1.1.14 still include the 3.28.0

**Comment by ericsink** [comment]
Note that SQLitePCLRaw 1.1.14 has been superseded by version 2.0.

I will be updating the e_sqlite3 builds for 2.0 somewhat regularly, but version 1.1.x will get updates only if necessary.
