### ISSUE TITLE
Where Can I Get PDB's?

### ISSUE THREAD

**Issue by RehanSaeed** [ericsink/SQLitePCL.raw#315]
According to this commit ['no more pdbs on release builds'](https://github.com/ericsink/SQLitePCL.raw/commit/6f07ed614bbb902e52959c774af35fa94085dfaa), it looks like PDB's are deliberately not shipped. 

In particular, I'm looking for PDB files for `e_sqlite3.dll` on UWP with x86/x64/ARM64 architectures. Is it possible to get hold of them from somewhere?

**Comment by ericsink** [comment]
At the moment, no, I don't have PDBs for the e_sqlite3 builds.

Another recent request for same prompted me to log #312

**Comment by RehanSaeed** [comment]
Closing in favour of https://github.com/ericsink/SQLitePCL.raw/issues/312
