### ISSUE TITLE
Missing methods in SQLitePCLRaw.bundle_green on Xamarin.Android

### ISSUE THREAD

**Issue by xanderh** [ericsink/SQLitePCL.raw#317]
Whenever we run our project, we run into the following exception:
`Method not found: string SQLitePCL.raw.sqlite3_column_name(SQLitePCL.sqlite3_stmt,int)`

We're running version 2.0.2 of the packages, compiling with android 9.0 (Pie), minimum version of 4.4.

Compiling works fine, the issue doesn't arise until runtime.

**Comment by xanderh** [comment]
Turns out the issue was on our end, we had the wrong nuget package versions installed

**Comment by xamarinshukla** [comment]
It seems the problem is still there. When monodroid  version is v90 this problem shows up, when it is v81, no issues.  I can't seem to find any documentation specific to Monodroid version v90. Any ideas?

**Comment by ericsink** [comment]
This issue is closed.  Yours may or may not be related.  Please open a new issue and provide lots of details about what you are seeing.
