### ISSUE TITLE
netcoreapp3.0 compatibility

### ISSUE THREAD

**Issue by UrsusDev** [ericsink/SQLitePCL.raw#318]
Thank you for your work! Have you tried your library with netcoreapp3.0? 

I have the following settings:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.0.0"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="3.0.0"/>
    <PackageReference Include="SQLitePCLRaw.bundle_sqlcipher" Version="1.1.14" />
    <PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.0.2" ExcludeAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <None Update="blogging.db">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
```

And got the error here:
`
var connection = new SqliteConnection("Data Source=blogging.db");
`

> Exception has occurred: CLR/System.TypeInitializationException
> An unhandled exception of type 'System.TypeInitializationException' occurred in Microsoft.Data.Sqlite.dll: 'The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.'
>  Inner exceptions found, see $exception in variables window for more details.
>  Innermost exception 	 System.MissingMethodException : Method not found: 'Int32 SQLitePCL.ISQLite3Provider.sqlite3_win32_set_directory(Int32, System.String)'.

**Comment by ericsink** [comment]
1.  SQLitePCLRaw is regularly tested under .NET Core 3.0.  That's not the issue here.

2.  You have bundle_sqlcipher 1.1.14 and bundle_green 2.0.2 -- you should not mix 1.x stuff with 2.x stuff.  There was a compatibility break between 1.x and 2.x.

3.  You also should never have two bundles at the same time.

**Comment by ericsink** [comment]
Closing this for now.  Feel free to open a new issue if you are still having trouble.
