### ISSUE TITLE
Failed to add reference. The package 'SQLitePCLRaw.lib.e_sqlite3.ios' tried to add a framework reference to 'System.Drawing.Common.dll' which was not found in the GAC.

### ISSUE THREAD

**Issue by chrfin** [ericsink/SQLitePCL.raw#320]
I am trying to update `Microsoft.EntityFrameworkCore.Sqlite` in my Xamarin.iOS project and get the follwoing error:

> Failed to add reference. The package 'SQLitePCLRaw.lib.e_sqlite3.ios' tried to add a framework reference to 'System.Drawing.Common.dll' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

I already tried adding `<DisableExtraReferences>true</DisableExtraReferences>` to the project without any change...

**Comment by ericsink** [comment]
I cannot imagine how that error message could happen.  System.Drawing.Common is not involved at all.

All I can suggest is to try the usual things for cases where your tooling is confused.  Clean and full rebuild?

**Comment by nagendaepoch** [comment]
our team is trying to use Microsoft.Data.Sqlite 3.0.2 in our Xamarin project with all three platforms. we had some issues using it in IOS project. as a solution mentioned here in the thread 
 https://github.com/dotnet/efcore/issues/18317 for that issue we are trying to update the SQLitePCLRaw pacakges to 2.0.2 and getting this error "Failed to add reference. The package 'SQLitePCLRaw.lib.e_sqlite3.ios' tried to add a framework reference to 'System.Drawing.Common.dll' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance" in the console. is there any fix available for this.

Thanks

**Comment by ericsink** [comment]
I have to say, I'm really curious how this is happening, but right now I don't have a clue.

I'll take a fresh look and see if I can find something odd, or maybe reproduce it.

**Comment by ericsink** [comment]
Maybe relevant:

https://stackoverflow.com/questions/58490375/cannot-update-msal-to-v4-51-on-xamarin-forms-ios

**Comment by chrfin** [comment]
Switching to package references solved the problem.
