### ISSUE TITLE
the build script crash at start (unhandled exception)

### ISSUE THREAD

**Issue by IAmJustAQuestion** [ericsink/SQLitePCL.raw#332]
HI,
I am trying to build the libraries from the code. (win10, vs19, sdk core 3.1)
I have downloaded the branch, and trying to build by running "dotnet run" in the /build folder as advised in the notes.

I have tried with regular command line, i have tried with developer command prompt and even powershell.
I have also tried the same procedure on linux OS, and on different machine ( just in case there is something wrong with my environment) 

**i get the following output:**

> D:\GIT\SQLitePCL.raw\build>dotnet run
> D:\GIT\SQLitePCL.raw\build\exec.fs(28,9): warning FS0020: The result of this expression has type 'bool' and is implicitly ignored. Consider using 'ignore' to discard this value explicitly, e.g. 'expr |> ignore', or 'let' to bind the result to a name, e.g. 'let result = expr'. [D:\GIT\SQLitePCL.raw\build\build.fsproj]
> D:\GIT\SQLitePCL.raw\build\Program.fs(24,5): warning FS0020: The result of this expression has type 'DirectoryInfo' and is implicitly ignored. Consider using 'ignore' to discard this value explicitly, e.g. 'expr |> ignore', or 'let' to bind the result to a name, e.g. 'let result = expr'. [D:\GIT\SQLitePCL.raw\build\build.fsproj]
> D:\GIT\SQLitePCL.raw\build\Program.fs(150,9): warning FS0020: The result of this expression has type 'DirectoryInfo' and is implicitly ignored. Consider using 'ignore' to discard this value explicitly, e.g. 'expr |> ignore', or 'let' to bind the result to a name, e.g. 'let result = expr'. [D:\GIT\SQLitePCL.raw\build\build.fsproj]
> -------- dotnet run .. in D:\GIT\SQLitePCL.raw\version_stamp
> 
> 
> Finished dotnet run .. in D:\GIT\SQLitePCL.raw\version_stamp after 3183L milliseconds
> -------- dotnet run .. in D:\GIT\SQLitePCL.raw\gen_nuspecs
> gen_nuspecs.cs(1120,59): warning CS0162: Unreachable code detected [D:\GIT\SQLitePCL.raw\gen_nuspecs\gen_nuspecs.csproj]
> 
> 
> Finished dotnet run .. in D:\GIT\SQLitePCL.raw\gen_nuspecs after 2213L milliseconds
> -------- dotnet restore in D:\GIT\SQLitePCL.raw\src\providers
>   Restore completed in 15.38 ms for D:\GIT\SQLitePCL.raw\src\providers\tool.csproj.
>   Restore completed in 32.97 ms for D:\GIT\SQLitePCL.raw\src\providers\tool.csproj.
> 
> 
> Finished dotnet restore in D:\GIT\SQLitePCL.raw\src\providers after 1207L milliseconds
> -------- t4 -o D:\GIT\SQLitePCL.raw\src\SQLitePCLRaw.provider.dynamic_cdecl\Generated\provider_dynamic_cdecl.cs -p:NAME=dynamic_cdecl -p:CONV=Cdecl -p:KIND=dynamic -p:UWP=false -p:FEATURE_KEY=true  provider.tt in D:\GIT\SQLitePCL.raw\src\providers
> 
> Unhandled Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
>    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start()
>    at build.exec(String filename, String args, String startDir) in D:\GIT\SQLitePCL.raw\build\exec.fs:line 27
>    at Program.exec@8-10.Invoke(String filename, String args, String startDir) in D:\GIT\SQLitePCL.raw\build\Program.fs:line 8
>    at Program.gen_provider@33D.Invoke(String uwp, String ftr_key) in D:\GIT\SQLitePCL.raw\build\Program.fs:line 42
>    at Program.main(String[] argv) in D:\GIT\SQLitePCL.raw\build\Program.fs:line 44

any help will be appreciated.
thank you

**Comment by ericsink** [comment]
Sorry.  You have to install the t4 tool.  I should include this in the README.

Try this:

`dotnet tool install -g dotnet-t4`

**Comment by IAmJustAQuestion** [comment]
Thank you for the prompt reply,

i have installed the tool, and now i get different error:


> Build started 13/02/2020 08:40:54.
> Project "D:\GIT\SQLitePCL.raw\src\SQLitePCLRaw.lib.sqlcipher.ios.placeholder\SQLitePCLRaw.lib.sqlcipher.ios.placeholder.csproj" on node 1 (default targets).
> Project "D:\GIT\SQLitePCL.raw\src\SQLitePCLRaw.lib.sqlcipher.ios.placeholder\SQLitePCLRaw.lib.sqlcipher.ios.placeholder.csproj" (1) is building "D:\GIT\SQLitePCL.raw\src\SQLitePCLRaw.lib.sqlcipher.ios.placeholder\SQLitePCLRaw.lib.sqlcipher.ios.placeholder.csproj" (1:3) on node 1 (Build target(s)).
> C:\Users\Yossi.Gurvich\.nuget\packages\msbuild.sdk.extras\2.0.54\Build\LanguageTargets\CheckMissing.targets(44,5): error : The specified language targets for xamarin.ios10 is missing. Ensure correct tooling is installed for 'xamarin.ios'. Missing: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.CSharp.targets' [D:\GIT\SQLitePCL.raw\src\SQLitePCLRaw.lib.sqlcipher.ios.placeholder\SQLitePCLRaw.lib.sqlcipher.ios.placeholder.csproj]
> Done Building Project "D:\GIT\SQLitePCL.raw\src\SQLitePCLRaw.lib.sqlcipher.ios.placeholder\SQLitePCLRaw.lib.sqlcipher.ios.placeholder.csproj" (Build target(s)) -- FAILED.
> Done Building Project "D:\GIT\SQLitePCL.raw\src\SQLitePCLRaw.lib.sqlcipher.ios.placeholder\SQLitePCLRaw.lib.sqlcipher.ios.placeholder.csproj" (default targets) -- FAILED.
> 
> Build FAILED.
> 
> "D:\GIT\SQLitePCL.raw\src\SQLitePCLRaw.lib.sqlcipher.ios.placeholder\SQLitePCLRaw.lib.sqlcipher.ios.placeholder.csproj" (default target) (1) ->
> "D:\GIT\SQLitePCL.raw\src\SQLitePCLRaw.lib.sqlcipher.ios.placeholder\SQLitePCLRaw.lib.sqlcipher.ios.placeholder.csproj" (Build target) (1:3) ->
> (_ShowMissingLanguageTargetsError target) ->
>   C:\Users\Yossi.Gurvich\.nuget\packages\msbuild.sdk.extras\2.0.54\Build\LanguageTargets\CheckMissing.targets(44,5): error : The specified language targets for xamarin.ios10 is missing. Ensure correct tooling is installed for 'xamarin.ios'. Missing: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.CSharp.targets' [D:\GIT\SQLitePCL.raw\src\SQLitePCLRaw.lib.sqlcipher.ios.placeholder\SQLitePCLRaw.lib.sqlcipher.ios.placeholder.csproj]
> 
>     0 Warning(s)
>     1 Error(s)
> 
> Time Elapsed 00:00:00.79
> 
> 
> Finished msbuild /p:Configuration=Release in D:\GIT\SQLitePCL.raw\src\SQLitePCLRaw.lib.sqlcipher.ios.placeholder after 1096L milliseconds
> 
> Unhandled Exception: System.Exception: Exception of type 'System.Exception' was thrown.
>    at build.exec(String filename, String args, String startDir) in D:\GIT\SQLitePCL.raw\build\exec.fs:line 36
>    at Program.exec@8-10.Invoke(String filename, String args, String startDir) in D:\GIT\SQLitePCL.raw\build\Program.fs:line 8
>    at Program.main(String[] argv) in D:\GIT\SQLitePCL.raw\build\Program.fs:line 109

I don't need xamarin, can i just ignore this exception? or there are some libraries that are built after,  that i will need?
thank you in advance.

**Comment by IAmJustAQuestion** [comment]
one more question:
does the script supposed to build nuget packages?
or I have to build them from the nuspec files by myself?
thank you.

**Comment by ericsink** [comment]
You need the `cb' tree checked out as a peer of the SQLitePCL.raw tree.

https://github.com/ericsink/cb

The script does build nuget packages.  But I'm curious -- what circumstances are making you need to build your own packages?

**Comment by IAmJustAQuestion** [comment]
> But I'm curious -- what circumstances are making you need to build your own packages?

due to some certification issues, we need to prove that all our components are equal to the source code.  

is there a way to change the script ( or some input parameter) to exclude xamarin /ios and android from the build ?

**Comment by ericsink** [comment]
> is there a way to change the script ( or some input parameter) to exclude xamarin /ios and android from the build

Currently no.
