### ISSUE TITLE
Problem with e_sqlite UWP build?

### ISSUE THREAD

**Issue by ericsink** [ericsink/SQLitePCL.raw#335]
See dotnet/efcore#20044

**Comment by bricelam** [comment]
I suspect it's a bug that crept into SQLite after version 3.25.3 (the version of winsqlite3.dll)

**Comment by ericsink** [comment]
This appears to be another case of needing to call `sqlite3_win32_set_directory()`.

Using the test project supplied by @osolo in the original issue, I can reproduce the error.

But if I make the following change, the error no longer occurs:

```
        public MainPage()
        {
            this.InitializeComponent();

            SQLitePCL.Batteries_V2.Init();
            SQLitePCL.raw.sqlite3_win32_set_directory(1, ApplicationData.Current.LocalFolder.Path);
            SQLitePCL.raw.sqlite3_win32_set_directory(2, ApplicationData.Current.LocalFolder.Path);
            RunTest(ApplicationData.Current.LocalFolder.Path);
        }
```

**Comment by bricelam** [comment]
Microsoft.Data.Sqlite will start doing this again in an upcoming 3.1 patch (3.1.4 I think)

**Comment by ericsink** [comment]
Closing old issue that was probably resolved a long time ago.

**Comment by anthony1969** [comment]
Hi @ericsink ,
after updating Microsoft.Data.Sqlite library to version 7.0.9 that have dependency with SQLitePCLRaw.core version 2.1.4, the issue reported above happens again, and i needed to re-introduce the code above to made it works.
