### ISSUE TITLE
UWP : API __std_type_info_destroy_list in vcruntime140.dll is not supported 

### ISSUE THREAD

**Issue by Adrien6** [ericsink/SQLitePCL.raw#342]
hello, 

i got an issue that i fail to fix. I have a xamarin forms application that used SQLitePCLRaw.bundle_e_sqlcipher. Everything works well on Android and iOS but when i want to deploy my application on microsoft store i got this errors : 

> 

    API __C_specific_handler in vcruntime140.dll is not supported for this application type. e_sqlcipher.dll calls this API.
    API __std_type_info_destroy_list in vcruntime140.dll is not supported for this application type. e_sqlcipher.dll calls this API.
    API memcmp in vcruntime140.dll is not supported for this application type. e_sqlcipher.dll calls this API.
    API memcpy in vcruntime140.dll is not supported for this application type. e_sqlcipher.dll calls this API.
    API memmove in vcruntime140.dll is not supported for this application type. e_sqlcipher.dll calls this API.
    API memset in vcruntime140.dll is not supported for this application type. e_sqlcipher.dll calls this API.
    API strrchr in vcruntime140.dll is not supported for this application type. e_sqlcipher.dll calls this API.

> 

You can find a little repro project, but you just have to add the package on a UWP solution and try to pass it to Windows app certification (you can juste run the supported api test).

Thank you for your time.

[Sqlitepclissue.zip](https://github.com/ericsink/SQLitePCL.raw/files/4540926/Sqlitepclissue.zip)

**Comment by ericsink** [comment]
You might see if #254 has any information that is helpful.

**Comment by Adrien6** [comment]
Thank you for your quick reply. I saw this topic before but i read it quickly because i believed it was an issue for ARM64 builds and I target only x86 for now.
I'm not sure to get everything in the issue mentionned but after reading it again, it seems to appear on ARM64 and fixed with 2.0.1.
I'm on x86, and i use version 2.0.2. 

![image](https://user-images.githubusercontent.com/30474621/80499626-83914e00-896d-11ea-94b0-537b275eb30d.png)

Thank you for your help

**Comment by ericsink** [comment]
I can't get the repro project to build:

```
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(3222,5): error MSB3325: Cannot import the following key file: SQLiteTest.pfx. The key file may be password protected. To correct this, try to import the certificate again or manually install the certificate to the Strong Name CSP with the following key container name: VS_KEY_7AB13B6CDB2A5E74
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(3222,5): error MSB3321: Importing key file "SQLiteTest.pfx" was canceled.

```

**Comment by Adrien6** [comment]
Sorry for that, i had to sign the package to test on microsoft partner, here is an other one without signature 
[SQLIssueWithoutSigning.zip](https://github.com/ericsink/SQLitePCL.raw/files/4556713/SQLIssueWithoutSigning.zip)
(It is just a xamarin tabbed project with SQLitePCLRaw.bundle_e_sqlcipher installed)

**Comment by ericsink** [comment]
I'm still having trouble doing a repo on this, but I'm probably doing it wrong.  I don't regularly make UWP packages, and every time I need to do so, I have to relearn it.

How exactly do I run WACK to get the errors you are seeing?

I'm trying to right-click on the project, choose Publish, then Create Packages, and it asks me a couple of questions, and then it crunches for a while.  I get no errors.

**Comment by Adrien6** [comment]
oh, deploying on microsoft can be a mess..  Here, you need to sign your application to run WACK, here are the steps :

Build your application :
- Select Release mode
- Right-click on the solution and select Publish / Create App Packages
- Select Sideloading, click next
- Select "Yes, select a certificate" and click on "Create"
- Enter a password, note it somewhere, click next
- It will generate a certificate for your solution, you may now have a [SolutionName]_TemporaryKey.pfx in your solution
- Don't forget to trust the certificate, you have a "Trust" button
- Select your certificate and click next 
- You can now build your application
- As you use sideloading, WACK doesn't launch automatically at this step

Run WACK : 
- Launch the UWP app Windows App Cert Kit
- Select "Validate Store App"
- Browse your app, you need to find the .appx in the bin/x86/release folder of your solution
- Click next and Just Select "Supported API test" 
- Click next, the test will run

Thank you for your time.

**Comment by ericsink** [comment]
Thanks for the instructions.

But unfortunately I'm having trouble here:

"Don't forget to trust the certificate, you have a "Trust" button"

I can't find that "Trust" button anywhere.  And when I run WACK, it won't validate because the cert isn't trusted.

**Comment by ericsink** [comment]
Another diagnostic question:

Do you by chance know if this problem occurs with bundle_e_sqlite3 also, or just with bundle_e_sqlcipher?

Also, is it specific to x86, or does it also occur with x64?

**Comment by Adrien6** [comment]
hello Eric,
I was making all tests this morning and i saw that there was a new version available. I updated my project with 2.0.3 and the error went away (x86 & x64).
Don't know how it has been fixed but thanks ! :)

**Comment by ericsink** [comment]
WELL then.

2.0.3 contained no changes that should have affected this issue.

**Comment by ericsink** [comment]
Closing old/stale issue.
