### ISSUE TITLE
PRAGMA foreign_keys=OFF not working

### ISSUE THREAD

**Issue by lion92pl** [ericsink/SQLitePCL.raw#344]
When foreign keys enforcement is enabled on connection level, `PRAGMA foreign_keys=OFF;` is not working. DROP TABLE results in `SQLite Error 19: 'FOREIGN KEY constraint failed'.`

Adding `Foreign Keys=False` to connection string is only workaround for this issue

**Comment by ericsink** [comment]
Are you saying that this is a recently introduced bug?  I mean, did it work as you expect in one version and then the behavior changed in a newer version?  What version are you using?

**Comment by lion92pl** [comment]
This is not working in EF Core 3.0.
[EF Core 3.0 Breaking change: SQLite foreign keys](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#pragma)
Was working in EF Core 2.2

**Comment by ericsink** [comment]
Can you post a small sample to reproduce the problem?

The link you mentioned merely talks about how the default setting is done.  It should not affect whether PRAGMA foreign_keys works or not.

Note that PRAGMA foreign_keys cannot be used inside of a transaction.

**Comment by bricelam** [comment]
Are you executing `PRAGMA foreign_keys=OFF;` inside a transaction? Because IIRC, that no-ops.

**Comment by lion92pl** [comment]
EF Core 3.0 is running every migration in transaction. It was probably working in different way in prior versions. As you said, running this PRAGMA in transaction is not working.
