### ISSUE TITLE
Sqlite 3.32 Upgrade Plans ?

### ISSUE THREAD

**Issue by inforithmics** [ericsink/SQLitePCL.raw#350]
Are there any plans to Upgrade to SQLite 3.32

Because one feature that I could use is that the Maximum Variable Number was increased from 999
to 32766
https://www.sqlite.org/limits.html#max_variable_number

Or

Is there a way to Read SQLITE_LIMIT_VARIABLE_NUMBER Parameter? 
Currently I have hard coded this value to 999

**Comment by FetFrumos** [comment]
Hello, Any news?

**Comment by ericsink** [comment]
I will plan to incorporate 3.32.x in the next release (or maybe the one after).

**Comment by inforithmics** [comment]
Thanks for the Information

**Comment by mduchev** [comment]
Great! Looking forward to that too!

**Comment by melimion** [comment]
There are also several vulnerabilites fixed in 3.32

**Comment by mduchev** [comment]
@ericsink Can't we close this, since 2.0.4 is updated to 3.33.0?

**Comment by inforithmics** [comment]
I'm closing this, i tried the newst sqlite.raw package and it worked with 16000 Variables instead of 999 Variables
