### ISSUE TITLE
Strange ALTER TABLE issues in e_sqlite3

### ISSUE THREAD

**Issue by bricelam** [ericsink/SQLitePCL.raw#351]
I feel like I'm going crazy, but the following code fails:

```cs
using System;
using System.Diagnostics;

using static SQLitePCL.raw;

class Program
{
    static void Main()
    {
        int rc;
        SQLitePCL.Batteries_V2.Init();

        rc = sqlite3_open(":memory:", out var db);
        Debug.Assert(rc == SQLITE_OK);

        rc = sqlite3_exec(db, "CREATE TABLE People ( Id INTEGER NOT NULL )");
        Debug.Assert(rc == SQLITE_OK);

        // SQLITE_ERROR: Cannot add a column with non-constant default
        rc = sqlite3_exec(db, "ALTER TABLE People ADD Sum INTEGER NULL DEFAULT(1 + 2)");
        if (rc != SQLITE_OK)
            Console.WriteLine(sqlite3_errmsg(db).utf8_to_string());
    }
}
```

If I run the same SQL inside sqlite3.exe (using the same SQLite version), it succeeds. Any ideas?

**Comment by bricelam** [comment]
Ditto for stored computed columns:

```sql
-- SQLITE_ERROR: cannot add a STORED column
ALTER TABLE People ADD Sum AS (X + Y) STORED;
```

**Comment by ericsink** [comment]
I tried running the first example above (DEFAULT (1+2)), with both SQLitePCLRaw and with sqlite3.exe.  I get the same error (Cannot add a column with non-constant default) both ways.

**Comment by ericsink** [comment]
Same for (X + Y) STORED -- I get "cannot add a STORED column" both ways of running it.

**Comment by bricelam** [comment]
So I have gone crazy... 🥴

**Comment by bricelam** [comment]
![image](https://user-images.githubusercontent.com/1226749/87083818-15c19800-c1e2-11ea-80b4-02c0c124db99.png)

**Comment by bricelam** [comment]
lol 🤷‍♂️

**Comment by ericsink** [comment]
Ha. That's 3.32.2 but I'm still on 3.31.1.  Maybe that's the difference.

**Comment by bricelam** [comment]
Ah, that makes sense. I probably misread it as 3.3***2***.1 when I "used the same version"

**Comment by ericsink** [comment]
I don't see anything in the sqlite release history bullets that would suggest a difference.

I'll try 3.32.2 and see what happens.

**Comment by bricelam** [comment]
Yeah, I've been digging through their issue tracker too. Just one of those "fixed by coincidence" bugs. Maybe in 3.32.1 under "Other minor compiler-warning fixes and whatnot."

**Comment by bricelam** [comment]
Confirmed. Repros on 3.31.1 but not 3.32.0. External

**Comment by ericsink** [comment]
Confirmed here as well -- 3.32.3 does not show the problem.
