### ISSUE TITLE
libsqlite3.so vs libsqlite3.so.0

### ISSUE THREAD

**Issue by jrocha** [ericsink/SQLitePCL.raw#352]
If I use `SQLitePCL.raw.SetProvider(new SQLitePCL.SQLite3Provider_sqlite3());` the loader looks for `libsqlite3.so`.

But `libsqlite3.so` symlink is provided by `libsqlite3-dev` and not provided in `libsqlite3-0`.
`libsqlite3-0` only provides `libsqlite3.so.0`

I think SQLitePCL.raw should look for `libsqlite3.so.0`. They all point the same the place though.

```
jrocha@DK015:/usr/lib/x86_64-linux-gnu$ dpkg -S /usr/lib/x86_64-linux-gnu/libsqlite3.so
libsqlite3-dev:amd64: /usr/lib/x86_64-linux-gnu/libsqlite3.so
jrocha@DK015:/usr/lib/x86_64-linux-gnu$ dpkg -S /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
libsqlite3-0:amd64: /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
```

**Comment by ericsink** [comment]
Broadly speaking, provider_sqlite3 seems to work fine for folks on Linux.

Closing old/stale issue.
