### ISSUE TITLE
Cannot encrypt existing and populated database with SQLitePCLRaw.bundle_e_sqlcipher

### ISSUE THREAD

**Issue by vmoglan** [ericsink/SQLitePCL.raw#354]
Hello,

- Issue: 
    - Trying to encrypt an existing, non-encrypted, empty database works
    - Trying to encrypt an existing, non-encrypted, _populated_ database **does not** work (no error, encryption is just not applied)
- Packages:
    - `Microsoft.Data.Sqlite.Core` v3.1.6
    - `SQLitePCLRaw.bundle_e_sqlcipher` v2.0.2 (v2.0.3 does not seem to work at all)
- Example (full code [here](https://github.com/vmoglan/DotNetSqlitePlayground/blob/master/DotNetSqlitePlayground.Tests/EncryptionTest.cs), `ShouldEncryptExistingPopulatedDb()` test method):
 ```csharp
string dataSource = EncryptionTestUtils.GetUniqueDataSource();  // does not exist
string password = "test";

string connectionString = new SqliteConnectionStringBuilder
{
    DataSource = dataSource,
    Mode = SqliteOpenMode.ReadWriteCreate
}.ConnectionString;

// [...] code for creating and populating database omitted 

// encryption

using (var connection = new SqliteConnection(connectionString))
{
    connection.Open();

    EncryptionTestUtils.ExecuteKeyQuery(connection, password, false);
    EncryptionTestUtils.ExecuteKeyQuery(connection, password);
}

Assert.IsTrue(EncryptionTestUtils.IsEncrypted(dataSource)); // fails
Assert.IsTrue(EncryptionTestUtils.TestEncryption(dataSource, password));
```
@bricelam I think you might be interested in this.

**NOTE:** I am running `EncryptionTestUtils.ExecuteKeyQuery(connection, password, false);` two times, first time as a key operation and second time as a re-key operations, because just running the key operation does nothing (related issue #355).

**Comment by ericsink** [comment]
Maybe I'm reading this wrong, but isn't this how PRAGMA key is supposed to work?

https://www.zetetic.net/sqlcipher/sqlcipher-api/#PRAGMA_key

**Comment by vmoglan** [comment]
Thank you for the clarification, I think this is a misunderstanding on my side on how on how the pragma is supposed to work.

I guess I was expecting the encryption to work as soon as the pragma's executed, and not during the first following operation.

I will review my test cases and close this issue.

**Comment by vmoglan** [comment]
I'm closing the issue as this is the expected behavior.
