### ISSUE TITLE
How to support libe_sqlite3.so for mips64 ARCH ?

### ISSUE THREAD

**Issue by sunny868** [ericsink/SQLitePCL.raw#360]
How to support libe_sqlite3.so for mips64 ARCH ?

**Comment by ericsink** [comment]
I don't currently build e_sqlite3 for mips64.

The build system for e_sqlite3 is in a separate repo:

https://github.com/ericsink/cb

What platform are you needing?  Linux?  Android?

**Comment by sunny868** [comment]
Thank you very much. I need to build it on Linux

**Comment by sunny868** [comment]
I have not finded makefile and source code of sqlite3 in repo https://github.com/ericsink/cb . Can you tell me how to build cb on Linux platform for support mips64 ?

**Comment by ericsink** [comment]
It is not a simple task at all, but here are a few tips if you really want to try:

The build files are generated by a program, the source code for that program is in cb.cs.

Compiling cb.cs is done by simply running csc or mcs.  There is no csproj file.

There are no Makefiles.  Each script is either a bash script of .bat file, depending on the platform.

cb.cs has virtually no comments to help.  But the basic idea is to modify cb.cs to also generate linux mips64 stuff.

You'll need to figure out which ubuntu packages have the cross-compilers for mips64 and how to invoke them.  I have no idea about this.

The source code for sqlite is in the cb/sqlite.  It's sqlite3.c.

You could skip the whole cb step by just figuring how to invoke the right cross-compiler and then drop the resulting .so file in the right place.

Then you'll need to modify the nuspec scripts in the SQLitePCL.raw repo to include the new file.  And so on.

This will be extremely difficult.  These parts of SQLitePCL.raw were never designed to be easy for others to work on.  As far as I know, nobody else has ever modified these scripts.

**Comment by sunny868** [comment]
@ericsink I have support  libe_sqlite3.so libe_sqlcipher.so for mips64 architecture on Linux platform , and I has a PR on epo https://github.com/ericsink/cb . Can you review it ? Thank you very much.

**Comment by xiangzhai** [comment]
I am on it.

Thanks,
Leslie Zhai

**Comment by ericsink** [comment]
What is the RID for linux mips64 for .NET Core?

**Comment by sunny868** [comment]
> What is the RID for linux mips64 for .NET Core?

linux-mips64

**Comment by sunny868** [comment]
@ericsink Can you rebuild SQLitePCL.raw for support linux-mips64? Thanks very much

**Comment by ericsink** [comment]
Yes, I’m planning to do a 2.0.4-pre release soon, which should include the mips64 builds.

**Comment by ericsink** [comment]
@sunny868 Please verify that the linux-mips64 builds for e_sqlite3 and e_sqlcipher in 2.0.4-pre20200828111558 are working properly.  These are not the builds you committed, but rather, were re-done by my build system.

**Comment by sunny868** [comment]
ok ,I will verify  as soon as possible.
