### ISSUE TITLE
Unable to load DLL 'e_sqlcipher' 

### ISSUE THREAD

**Issue by vellk** [ericsink/SQLitePCL.raw#366]
prerequisites 
Packages: 
SQLitePCLRaw.bundle_e_sqlcipher" version="2.0.4" targetFramework="net472"
SQLitePCLRaw.core" version="2.0.4" targetFramework="net472"
SQLitePCLRaw.lib.e_sqlcipher" version="2.0.4" targetFramework="net472"
SQLitePCLRaw.provider.dynamic_cdecl" version="2.0.4" targetFramework="net472"
SQLitePCLRaw.provider.e_sqlcipher" version="2.0.4" targetFramework="net472"

on SQLitePCL.raw.SetProvider(new SQLite3Provider_e_sqlcipher()); get the following error:

at SQLitePCL.SQLite3Provider_e_sqlcipher.NativeMethods.sqlite3_libversion_number()
   at SQLitePCL.SQLite3Provider_e_sqlcipher.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
   at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)

with def provider and SQLitePCL.Batteries_V2.Init(); it works ok but there is no db encryption I need.

Tried on .net core 3 with Microsoft.Data.Sqlite.Core and SQLitePCLRaw.bundle_e_sqlcipher - everything works fine

**Comment by vellk** [comment]
Solved

**Comment by chuki2** [comment]
@vellk , can share how you solved it?

**Comment by vellk** [comment]
It was my mistake. No need to call `SQLitePCL.raw.SetProvider(new SQLite3Provider_e_sqlcipher());`. 
It's enouth to call `SQLitePCL.Batteries_V2.Init();` and have `SQLitePCLRaw.provider.e_sqlcipher"` installed.
