### ISSUE TITLE
WinRT not working?

### ISSUE THREAD

**Issue by corliss** [ericsink/SQLitePCL.raw#37]
Great project. It runs successfully on Windows desktop, but in a WinRT project, it throws:

Unable to load 'sqlite3' - the specified module could not be found.

The lib folder also doesn't have any folder that looks like it would work for WinRT:

MonoAndroid
MonoTouch
net45
netcore45
netcore451
portable-net45+netcore45+wp8+MonoAndroid10+MonoTouch10+Xamarin.iOS10
portable-net45+netcore45+wpa81+MonoAndroid10+MonoTouch10+Xamarin.iOS10
portable-net45+netcore45+wpa81+wp8+MonoAndroid10+MonoTouch10+Xamarin.iOS10
portable-net45+sl5+netcore45+wp8+MonoAndroid10+MonoTouch10+Xamarin.iOS10
wp8
wp81
wpa81
Xamarin.iOS10

Any ideas?

**Comment by ericsink** [comment]
The netcore libs are for WinRT.

Did you add a reference to the extension SDK for the visual c++ runtime?

Are you building for a specific CPU? (AnyCPU won't work for WinRT here).

WInRT works for me, but it's fussy about these kinds of settings being just
right.

E

**Comment by corliss** [comment]
> Did you add a reference to the extension SDK for the visual c++ runtime?
No, what exactly is this? Is it on nuget?

> Are you building for a specific CPU? (AnyCPU won't work for WinRT here)
Yes, I'm building x86.

Cheers

**Comment by ericsink** [comment]
It's not on nuget.  I think it comes with visual studio.  Do Add
Reference.  Look for it in there. Maybe under Extensions. I don't have a
windows machine handy right now, so I'm fuzzy on the details.

E

**Comment by corliss** [comment]
Thanks, I see these listed (among others):

| Microsoft Visual C++ 2013 Runtime Package for Windows  |  Version 12.0 |
| (greyed out) Microsoft Visual C++ Runtime package | Version 11.0 |
| SQLite for Windows Runtime (Windows 8.1) | 3.8.8.1 |

Should I select the first and third, or just the first?

**Comment by ericsink** [comment]
Just the first.

E

**Comment by corliss** [comment]
Great, that worked. Definitely worth adding in the README, btw - spent a lot of time trying to figure this one out :)

**Comment by corliss** [comment]
BTW is there any chance that AnyCPU can be made to work for WinRT? I don't fully understand WinRT app packaging, but previous to this had assumed I could ship a single image (AnyCPU) to work on all WinRT devices. This breaks that. I know the sqlite binary is platform-specific, but perhaps the correct version can be loaded at runtime from a platform subfolder?

**Comment by ericsink** [comment]
I've spent quite a bit of time trying to find a way, but so far, no luck.
The problem comes down to that C++ runtime library.  I would still like to
find a solution at some point.

--
E
