### ISSUE TITLE
Are the SQLCipher providers thread-safe?

### ISSUE THREAD

**Issue by vmoglan** [ericsink/SQLitePCL.raw#371]
Hi, not sure if this is the right place to ask but is the `e_sqlcipher` provider compiled with the `SQLITE_THREADSAFE` flag?

**Comment by ericsink** [comment]
The e_sqlcipher libraries are compiled without defining SQLITE_THREADSAFE, so the default is used, and according to the SQLite docs, that default is 1:

https://www.sqlite.org/compile.html#threadsafe

**Comment by vmoglan** [comment]
That answers my question, thanks.
