### ISSUE TITLE
Performance with SQLite and Microsoft.EntityFrameworkCore.Sqlite.Core and SQLitePCLRaw.bundle_e_sqlcipher

### ISSUE THREAD

**Issue by wjvii** [ericsink/SQLitePCL.raw#376]
I am not sure of the proper etiquette for posting into two repos about the same issue but I wanted to call out this issue that I put into the efcore repo because I am not sure it has to do with efcore or sqlcipher or some combination.

We have created a small .NET Core console app that confirms that EF queries with SQLite were on par with non-encrypted ones up to EF Core 2.2 but as of EF Core 3.1 and later it is about 45x slower to execute a simple single table query, at least in our scenario.

[https://github.com/dotnet/efcore/issues/23099 ](url)

**Comment by ericsink** [comment]
Link to other issue:  dotnet/efcore#23099
