### ISSUE TITLE
not much as an issue as more a question

### ISSUE THREAD

**Issue by cmorgado** [ericsink/SQLitePCL.raw#38]
Does SQLite.Raw suport multiple statments on execute?

I need to update several records like this:  "update x set a=1 where k=0;update x set a=1 where k=2;"

**Comment by ericsink** [comment]
Do you have a snippet of code that isn't working the way you would expect?

--
E


On Mon, Feb 16, 2015 at 5:07 AM, Cristóvão Morgado <notifications@github.com

**Comment by bordoley** [comment]
For reference, you should be able to do this with sqlite3_exec: https://www.sqlite.org/c3ref/exec.html
