### ISSUE TITLE
Outdated sqlite3 in sqlcipher.dll - (Nuget - SQLitePCLRaw.lib.sqlcipher.windows 1.1.14)

### ISSUE THREAD

**Issue by davisannie** [ericsink/SQLitePCL.raw#382]
Outdated sqlite3 in sqlcipher.dll - (Nuget - SQLitePCLRaw.lib.sqlcipher.windows 1.1.14) is causing  critical vulnerabilities on blackduck binary analysis tool. Current version of sqllite3 on sqlcipher dll is 3.4.2. The recommendation is to update sqlcipher.dll to latest version of sqllite3 to 3.33.0

**Comment by ericsink** [comment]
That package ID is no longer being updated.  For more recent versions, see:

https://www.nuget.org/packages/SQLitePCLRaw.lib.e_sqlcipher/

which is still not current, but it's much closer.  :-)

**Comment by davisannie** [comment]
Thanks for you prompt response Eric

**Comment by davisannie** [comment]
I tried SQLitePCLRaw.bundle_e_sqlcipher 2.0.4 with EF3.1.10
however this updates the sqlite3 to 3.28, which still leaves us with 2 critical vulnerabilities.
Is there anything planned to update sqlite3 to the latest and greatest version?

**Comment by ericsink** [comment]
Yes, the unsupported and unofficial e_sqlcipher builds are currently based on a version of SQLCipher based on 3.28.0.  I do plan to update them, and hopefully soon, but in the meantime, you can always purchase official supported builds from Zetetic.

**Comment by davisannie** [comment]
Thanks Eric.

**Comment by ericsink** [comment]
See #390
