### ISSUE TITLE
Not working on macos since upgrading from v1 to v2

### ISSUE THREAD

**Issue by pellet** [ericsink/SQLitePCL.raw#386]
Since upgrading from v1.1.11 to v2.0.2 I'm getting this error now:
`    System.MissingMethodException
    Method not found: 'Int32 SQLitePCL.raw.sqlite3_create_collation(SQLitePCL.sqlite3, System.String, System.Object, SQLitePCL.delegate_collation)'.
    at SQLitePCL.pretty.SQLiteDatabaseConnectionBuilder.Build()
    at SQLitePCL.pretty.SQLite3.OpenInMemory()`
The target/host is netcoreapp3.0 running on Mac OSX 10.15.7.
Any ideas on how to work around this issue?

**Comment by ericsink** [comment]
Check the release notes for 2.0:  https://github.com/ericsink/SQLitePCL.raw/blob/master/v2.md

Make sure you don't have any 1.x packages still involved.

**Comment by pellet** [comment]
Spot on @ericsink, I went through my target's **project.assets.json** and tracked down all the SQLitePCLRaw v1 implicit dependencies.  Issue was **SQLitePCL.pretty** still references SQLitePCLRaw v1 but I replaced it with an upgraded fork called **SQLitePCL.pretty.netstandard** which references SQLitePCLRaw v2, now I no longer get the error.
Cheers!
