### ISSUE TITLE
Does the IGetFunctionPointer implementer need to implement also IDisposable functionality with Destructors

### ISSUE THREAD

**Issue by tinmanjk** [ericsink/SQLitePCL.raw#387]
Since, I couldn't really find any more info in the documentation / web searches:

Following this:
https://docs.microsoft.com/en-us/dotnet/standard/data/sqlite/custom-versions?tabs=netcore-cli

Doesn't the implementation of an "NativeLibraryAdapter" necessitate also a fully-fledged Dispose pattern?
After all this class is working with unmanaged resources - library handle and function pointers?

From this discussion https://github.com/ericsink/SQLitePCL.raw/issues/166, I was a bit confused to the final stand of SQLitePCL.raw in regards to who is supposed to provide the safety-net in form of destructors.

**Comment by ericsink** [comment]
I think this question was about code that has since been replaced.

Closing old/stale issue.
