### ISSUE TITLE
Not compatible with UAP (for AppCenter usage)

### ISSUE THREAD

**Issue by amp64** [ericsink/SQLitePCL.raw#391]
I have a long-standing successful UWP app that now needs to use AppCenter as HockeySDK just got turned off. However AppCenter depends on this package, and I cannot add a reference to this package because:

NU1202: Package SQLitePCLRaw.bundle_green 2.0.4 is not compatible with uap10.0.10240 (UAP,Version=v10.0.10240). Package SQLitePCLRaw.bundle_green 2.0.4 supports:
  - net461 (.NETFramework,Version=v4.6.1)
  - netcoreapp3.1 (.NETCoreApp,Version=v3.1)
  - netstandard2.0 (.NETStandard,Version=v2.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)

**Comment by ericsink** [comment]
For netstandard2.0, which is the minimum for SQLitePCLRaw 2.x, the minimum supported version of UWP is Fall Creators Update, 10.0.16299.

**Comment by amp64** [comment]
Ah, so no more Windows Mobile support for my app, makes sense now, thanks.
