### ISSUE TITLE
SQLitePCL.raw does not run on Xamarin.Mac Unified

### ISSUE THREAD

**Issue by corliss** [ericsink/SQLitePCL.raw#40]
I upgraded a fairly large project to the Xamarin Unified API, without reading the fine print that SQLitePCL.raw runs on Xamarin.iOS Unified, but only .net45 on OSX. 

I could try to selectively roll back changes, but thought I'd ask - would it be possible for you to release a build that runs against Xamarin.Mac Unified? Since you've already got iOS Universal working, I imagine this is not too difficult.

Many thanks.

**Comment by corliss** [comment]
Hi, just a quick ping - is this something you think you'll be able to do, and if so, when?
I'd appreciate any response. Thanks.

**Comment by ericsink** [comment]
Oops, sorry for the radio silence on this.

I do want to fix this issue.  But right now I don't have a license for
Xamarin.Mac, so first I have to fix /that/ issue.

Right now I can't give an estimate.

E

**Comment by corliss** [comment]
Thanks for the reply. I've rolled back my changes to build against the classic API for Mac. Looking forward to rolling forward again :)

**Comment by nberardi** [comment]
Is anybody working on this?  If not I would like to take a stab at it.  I need it for a current project.

**Comment by bordoley** [comment]
If you get this started, i have a pretty complete set of unit tests in SQLitePCL.pretty that we can use to verify on mac. I'd love to be able to run them on mac instead of needing to run them on windows.

**Comment by nberardi** [comment]
If I am reading the NuGet and the code right, it looks like Xamarin.iOS10 is already supported, which is already running off the Unified API.  It should be relatively trivial to get it running on Xamarin.Mac20 which is also Unified API. http://developer.xamarin.com/guides/cross-platform/macios/unified/

**Comment by ericsink** [comment]
Sorry, I haven't made any progress on this, but I've been thinking I would get to it soon.

I'd love a pull request if you can submit one.  :-)

Thanks.

**Comment by nberardi** [comment]
Let me know what you think.  This provides the setup.  Nothing else needed to be changed, at least from my initial tests.  Looking forward to your review.

**Comment by ericsink** [comment]
Version 0.8.1-pre1 of the package (on nuget) contains this feature.  Testing of that build would be appreciated.

**Comment by ericsink** [comment]
0.8.1 has been pushed to nuget.  Closing this issue.

**Comment by nberardi** [comment]
Great news. Thanks for the push to nuget

--
Nick Berardi
(484) 302-0125
Sent on the go from my phone.
