### ISSUE TITLE
Support for sqlite3_carray_bind

### ISSUE THREAD

**Issue by lstratman** [ericsink/SQLitePCL.raw#404]
Are there plans to support sqlite3_carray_bind in the upcoming 2.0.5 release or is anyone actively working on it?  It would be pretty useful for my company's product, so I'd be happy to give it a go and submit a PR, but I just wanted to make sure that I wouldn't be stepping on anyone's toes before I do that.

**Comment by ericsink** [comment]
No plans for that API yet.

Unfortunately, implementing it would be decidedly non-trivial.  Currently, the e_sqlite3 builds are done using the SQLite amalgamation, and the carray stuff is not included in it.  So, implementing this would require major changes to the build system I use for making e_sqlite3 native builds.

**Comment by lstratman** [comment]
Yep, saw when I started really looking into this that this would best be handled on our side via a loaded SQLite extension.  Closing the issue...
