### ISSUE TITLE
ASP.Net attempts to load Native Dlls from Temporary ASP.Net Files location

### ISSUE THREAD

**Issue by twaddell** [ericsink/SQLitePCL.raw#405]
Target Framework: .NET Framework 4.6.1
Project Type: ASP.Net website
Running debug in IISExpress.

When I call `SQLitePCL.Batteries_V2.Init();` in startup I get the following error:

```
System.Exception
  HResult=0x80131500
  Message=Library e_sqlcipher not found
plat: win
suffix: DLL
possibilities (1):
    1) C:\Users\[USER]\AppData\Local\Temp\Temporary ASP.NET Files\vs\2aaff545\10dff8fc\assembly\dl3\a602148a\00458763_690bd701\runtimes\win-x86\native\e_sqlcipher.dll
win TryLoad: C:\Users\[USER]\AppData\Local\Temp\Temporary ASP.NET Files\vs\2aaff545\10dff8fc\assembly\dl3\a602148a\00458763_690bd701\runtimes\win-x86\native\e_sqlcipher.dll
thrown: System.ComponentModel.Win32Exception (0x80004005): The specified module could not be found
   at SQLitePCL.NativeLibrary.TryLoad(String name, Loader plat, Action`1 log, IntPtr& h)
NOT FOUND

  Source=SQLitePCLRaw.nativelibrary
  StackTrace:
   at SQLitePCL.NativeLibrary.Load(String libraryName, Assembly assy, Int32 flags)
   at SQLitePCL.Batteries_V2.MakeDynamic(String name, Int32 flags)
   at SQLitePCL.Batteries_V2.DoDynamic_cdecl(String name, Int32 flags)
   at SQLitePCL.Batteries_V2.Init()
   at MyServer.Startup.Configuration(IAppBuilder app) in X:\MyProject\Startup.cs:line 47
```

The `C:\Users\[USER]\AppData\Local\Temp\Temporary ASP.NET Files\vs\2aaff545\10dff8fc\assembly\dl3\a602148a\00458763_690bd701` contains the `SQLitePCLRaw.core.DLL` file

The above error is from a local build of master branch, after getting just a "Library e_sqlcipher not found" error with no path information from 2.0.4

Is there a way of setting the load path for the Native dlls before initialization, so it is not always trying to load from the same dir as the SQLitePCLRaw.core.dll?

**Comment by sjlombardo** [comment]
This is caused by ASP.NET shadow copying. One possible workaround add the following to the `system.web` section in `web.config`:

```
<hostingEnvironment shadowCopyBinAssemblies="false" />
```

This disables shadow copy entirely so that the native DLL can be resolved relative to `SQLitePCLRaw.core.dll`. 

I wonder if it would be possible to determine if shadow copy is in play, and if so, use an alternate means to look for libraries relative to the application root.

**Comment by uholeschak** [comment]
I have patched the `Batteries_V2 `INIT function as follow to directly load the library from the correct location:
```
        public static void Init()
        {
            string codeBase = Path.GetDirectoryName(Assembly.GetExecutingAssembly().CodeBase);
            if (!string.IsNullOrEmpty(codeBase))
            {
                UriBuilder uriBuilder = new UriBuilder(codeBase);
                string path = Uri.UnescapeDataString(new Uri(uriBuilder.Path).LocalPath);
                string rid = (IntPtr.Size == 8) ? "win-x64" : "win-x86";
                string libPath = Path.Combine(path, "runtimes", rid, "native", "e_sqlite3mc");
                DoDynamic_cdecl(libPath, NativeLibrary.WHERE_PLAIN);
            }
        }
```

**Comment by duncansmart** [comment]
I solved it by copying the native runtimes to the `Temporary ASP.NET Files` directory at runtime. Call the following at application startup or a static constructor:

    static void ensureNativeLibraries()
    {
        // Due to ASP.NET shadow-copying, SQLitePCLRaw.core.dll is loaded from the Temporary ASP.NET Files directory, e.g.:
        //      ..Temporary ASP.NET Files\...\f00\SQLitePCLRaw.core.dll
        // The native libraries are assumed to be in the "runtimes" directory alongside SQLitePCLRaw.core.dll, e.g.
        //      ..Temporary ASP.NET Files\...\f00\runtimes\win-x64\native\e_sqlite3.dll
        // but they are actually still in the ~/bin/runtimes directory because ASP.NET doesn't copy native libraries to the Temporary ASP.NET Files directory.

        var aspRuntimesDir = Path.Combine(Path.GetDirectoryName(typeof(SQLitePCL.raw).Assembly.Location), "runtimes");
        var binRuntimesDir = Path.Combine(HttpRuntime.BinDirectory, "runtimes");
        copyDirectory(binRuntimesDir, aspRuntimesDir);
    }

    static void copyDirectory(string sourceDir, string targetDir)
    {
        // normalize paths
        sourceDir = Path.GetFullPath(sourceDir).TrimEnd(Path.DirectorySeparatorChar) + Path.DirectorySeparatorChar;
        targetDir = Path.GetFullPath(targetDir).TrimEnd(Path.DirectorySeparatorChar) + Path.DirectorySeparatorChar;

        foreach (var sourcePath in Directory.GetFiles(sourceDir, "*.*", SearchOption.AllDirectories))
        {
            try
            {
                var targetPath = sourcePath.Replace(sourceDir, targetDir);
                // copy if newer
                if (!File.Exists(targetPath) || File.GetLastWriteTimeUtc(sourcePath) > File.GetLastWriteTimeUtc(targetPath))
                {
                    Directory.CreateDirectory(Path.GetDirectoryName(targetPath));
                    File.Copy(sourcePath, targetPath, true);
                }
            }
            catch (IOException ioex) when (ioex.HResult == -2147024864)
            {
                // Ignore "The process cannot access the file '...' because it is being used by another process" errors
            }
        }
    }
