### ISSUE TITLE
0.7.2 stable release?

### ISSUE THREAD

**Issue by bordoley** [ericsink/SQLitePCL.raw#41]
Just was curious when you were planning on releasing 0.7.2 as stable on nuget?

**Comment by ericsink** [comment]
Maaaybe this week.  More likely the following week.

I've been trying to get back to this, but swamped with other stuff.

When I do make this release, it will probably be called 0.8.0.

And I want to get the net40 support from couchbase in first.

Are you waiting on this release for anything specific?

--
E

**Comment by bordoley** [comment]
Nothing that is date driven. I added some features to pretty that depend on 0.7.2 so I've had to release it as pre as well. Definitely can wait a couple of weeks though. Thanks for the update.
