### ISSUE TITLE
SqlitePCLRaw.batteries_V2 version conflicts

### ISSUE THREAD

**Issue by mrakhra** [ericsink/SQLitePCL.raw#411]
Hello Erik,

I have updated libraries in the Xamarin Forms project. In Xamarin iOS, I am getting the following error message.

` error CS0433: The type 'Batteries_V2' exists in both 'SQLitePCLRaw.batteries_v2, Version=2.0.2.669, Culture=neutral, PublicKeyToken=8226ea5df37bcae9' and 'SQLitePCLRaw.batteries_v2, Version=2.0.4.976, Culture=neutral, PublicKeyToken=8226ea5df37bcae9'`

I am confirming that I have updated the project to use **SqlitePCLRaw.bundle.green (2.0.4)** 

As a result, I can't build the iOS project.

Please help.
**Regards and Thanks,**
Manbir Rakhra

**Comment by ericsink** [comment]
The error message looks self explanatory.  You have two versions of SQLitePCLRaw in conflict.  Maybe something is bringing in a second copy of SQLitePCLRaw as a dependency?  Maybe you need a full rebuild?  Without more information, I don't have any way of guessing what is going on.

**Comment by mrakhra** [comment]
Hello Eric,

Thanks for giving me an idea. This was another NuGet package bringing in conflicts. I've resolved the dependencies conflicts.

**Regards and Thanks,**
Manbir Rakhra
