### ISSUE TITLE
About e_sqlcipher builds

### ISSUE THREAD

**Issue by ericsink** [ericsink/SQLitePCL.raw#417]
I wrote a wiki page to give more background and context about my `e_sqlcipher` builds:

https://github.com/ericsink/SQLitePCL.raw/wiki/Expectation-setting-for-e_sqlcipher

Questions and concerns are welcome here.

Tagging @sjlombardo so the folks at Zetetic can provide corrections if I said anything that isn't quite right.

**Comment by ericsink** [comment]
A coworker sent me this meme.  I laughed and decided it should be here as well:

![image](https://user-images.githubusercontent.com/3877005/118040804-a358a180-b337-11eb-81cd-625d8126a86c.png)

**Comment by sjlombardo** [comment]
Hello @ericsink, this is a great Wiki page, and should be very helpful for those evaluating or choosing to implement SQLCipher in their projects. I also appreciate the kind words about SQLCipher and Zetetic. Most of all though, thank you for your work on SQLitePCL.raw, through which all things "SQLite" are possible in .NET. Without this project, using customized SQLite packages like SQLCipher would be incredibly painful, so we are very grateful for it.

**Comment by bricelam** [comment]
I've also tried to be very clear about this in the Microsoft.Data.Sqlite docs ([here](https://docs.microsoft.com/dotnet/standard/data/sqlite/encryption) and [here](https://docs.microsoft.com/dotnet/standard/data/sqlite/custom-versions)). Let me know if you want me to change any wording or add a big red caution to these pages linking to this your wiki.
