### ISSUE TITLE
Feature request: Add provider for SQLite3 Multiple Ciphers

### ISSUE THREAD

**Issue by kroimon** [ericsink/SQLitePCL.raw#420]
> **[SQLite3 Multiple Ciphers](https://utelle.github.io/SQLite3MultipleCiphers/)** is an extension to the public domain version of SQLite that allows applications to read and write encrypted database files. Currently 5 different encryption cipher schemes are supported:
> 
> - wxSQLite3: AES 128 Bit CBC - No HMAC
> - wxSQLite3: AES 256 Bit CBC - No HMAC
> - sqleet: ChaCha20 - Poly1305 HMAC
> - SQLCipher: AES 256 Bit CBC - SHA1/SHA256/SHA512 HMAC
> - System.Data.SQLite: RC4

Although it seems to be possible to use the _SQLitePCLRaw.provider.sqlite3_ or _SQLitePCLRaw.bundle_sqlite3_ packages with a renamed sqlite3mc.dll, having a specialized provider and possibly a bundle would be great.

**Comment by ericsink** [comment]
Closing in favor of discussion #513
