### ISSUE TITLE
Add `[UnmanagedCallersOnly]` to `scalar_function_hook_bridge_impl` for WebAssembly support

### ISSUE THREAD

**Issue by jeromelaban** [ericsink/SQLitePCL.raw#423]
When running on WebAssembly, callbacks needs to be explicitly [known at compile time](https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs#L72) so that code can be generated to replace dynamic stubs that the runtimes with JIT can add.

The .NET runtime adds support for this with .NET 5 by means of `UnmanagedCallersOnly` (see [this for an example](https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/System.Private.CoreLib/src/System/Globalization/CalendarData.Icu.cs#L431)).

This [`scalar_function_hook_bridge_impl`](https://github.com/ericsink/SQLitePCL.raw/blob/1b2e50535cf3c3e4811197b72b7dc694715227f6/src/providers/provider.tt#L837) callback is used by `sqlite3_create_function`, at least.

For now, `SQLitePCL.SQLite3Provider_sqlite3` is built with `netstandard2.0`, which does not provide  `UnmanagedCallersOnlyAttribute` as it is available starting from `net5`.

For information, `sqlite3_create_function` is used by [EF Core here](https://github.com/dotnet/efcore/blob/ac2bb48b10ecf1289b568a94b7a35e8075c6d787/src/EFCore.Sqlite.Core/Storage/Internal/SqliteRelationalConnection.cs#L152-L155).

**Comment by ericsink** [comment]
At first glance, we need `UnmanagedCallersOnly` in exactly the same places that we use the `MonoPInvokeCallback` attribute.

**Comment by jeromelaban** [comment]
For [Uno's support](https://github.com/unoplatform/Uno.Wasm.Bootstrap/blob/e855ae4f4179a0e6224aacb184f99f2cd9087870/src/Uno.Wasm.Tuner/PInvokeTableGenerator.net5.cs#L88) as well as [.NET own tooling](https://github.com/dotnet/runtime/blob/37e9d4b1b491f6fd28a7d10df5dcaf49adcf71e9/src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs#L75), `MonoPInvokeCallback` is among the lookups done and the `SQLitePCLRaw.provider.sqlite3` marks callbacks with it.

The trick here is to ensure that the IL Linker (trimming) does not remove the internal `MonoPInvokeCallback` defined in `SQLitePCLRaw.core`. Here's an example of [linker file](https://github.com/unoplatform/Uno.SQLitePCLRaw.Wasm/blob/master/src/SQLitePCLRaw.provider.wasm/LinkerDefinition.Wasm.xml).

The fix there may still be to add `UnmanagedCallersOnly` to the methods, but could also be to make `SQLitePCLRaw.core` linker aware.

**Comment by ericsink** [comment]
@bricelam IIRC, you might be working on some pull requests for me involved Wasm support, although I don't know the timing of that effort.  I'm tagging you here to let you know that there may be some overlap in what I'm currently doing.  For example, as indicated in this issue, I need to support use of the UnmanagedCallersOnly attribute as a substitute for the old MonoPInvokeCallback attribute.  But I'm pretty sure I need to do this for net6 xamarin support (which is the thing I'm focusing on), not just for Wasm.  So anyway, I thought I should give you a heads-up.

**Comment by ericsink** [comment]
I think everything here in this issue got dealt with during 2.1.0, which is now released.

**Comment by jeromelaban** [comment]
Thanks for the update!
