### ISSUE TITLE
Document how to use the included dylib on mac, etc.

### ISSUE THREAD

**Issue by bordoley** [ericsink/SQLitePCL.raw#43]
At the risk of losing all geek credibility, I was wondering if you had instructions on how to use the included sqlite dylib included in the recent nuget from a project in xam studio.

**Comment by bordoley** [comment]
For reference, I'm trying to get my tests for SQLitePCL pretty working on mac in xam studio so I can avoid needing to use VS to run tests. The version of sqlite shipped with OS X is ancient, and i'm pretty dependent upon many of the newer APIs, so its also a practical concern for me in terms of ensuring support for the other mobile OSes where I'm fairly certain shipping an in app sqlite lib will be a requirement.  The relevant project file is here: https://github.com/bordoley/SQLitePCL.pretty/blob/master/SQLitePCL.pretty.tests/SQLitePCL.pretty.tests.Mac.csproj

**Comment by ericsink** [comment]
I don't have anything that deserves to be called "instructions", nor do I
have time at the moment to write any, but here's a hint:

The environment variable you need to set is  DYLD_LIBRARY_PATH

--
E

**Comment by ericsink** [comment]
Did you get past this issue?

**Comment by bordoley** [comment]
Not yet. I got side tracked on other projects :P Most the examples I've seen have involved setting the library path on built executables (for instance: http://stackoverflow.com/questions/14536843/including-custom-dll-and-dylib-in-monomac-app) vs. using it from within the xam studio unit test runner. I'm assuming I'd have to set that environment variable on the xam studio itself which is running the unit tests?

**Comment by nberardi** [comment]
It should be rather easy.

1. Create C# Unified API Xamarin.Mac Application project
2. Add dynamic library to Native References of Unified API project
3. Build Unified API project

Make sure you are referencing your code correctly.
```csharp
        [DllImport ("libsimpleDylib")]
        public static extern int do_simple_work(int a, int b);
```

Add a reference to your `app.config`
```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
   <dllmap dll="libsimpleDylib" target="libsimpleDylib.dylib" />
</configuration>
```

That is all that should be needed.  However there is a bug with the Xamarin.Mac 2.0 where it doesn't copy the dylib.

There is however a workaround, add a post build command of the following:
```
cp lib/libsimpleDylib.dylib ${TargetDir}/UnifiedAPIWithDylib.app/Contents/MonoBundle/
```
