### ISSUE TITLE
net6.0 targeting issue

### ISSUE THREAD

**Issue by ericsink** [ericsink/SQLitePCL.raw#437]
3>C:\Users\Robel\source\repos\BibleApp.Maui\BibleApp.Maui\BibleApp.Maui.csproj : warning NU1703: 'SQLitePCLRaw.bundle_e_sqlite3 2.0.4' was resolved as a dependency of 'BibleApp.Maui', but the dependency is using 'Xamarin.iOS' while 'BibleApp.Maui' is using 'net6.0-maccatalyst13.5' as its TargetFramework. There might be compatibility issues when MacCatalyst projects depend on Xamarin.iOS projects.
3>C:\Users\Robel\source\repos\BibleApp.Maui\BibleApp.Maui\BibleApp.Maui.csproj : warning NU1703: 'SQLitePCLRaw.bundle_green 2.0.3' was resolved as a dependency of 'BibleApp.Maui', but the dependency is using 'Xamarin.iOS' while 'BibleApp.Maui' is using 'net6.0-maccatalyst13.5' as its TargetFramework. There might be compatibility issues when MacCatalyst projects depend on Xamarin.iOS projects.
3>C:\Users\Robel\source\repos\BibleApp.Maui\BibleApp.Maui\BibleApp.Maui.csproj : warning NU1703: 'SQLitePCLRaw.core 2.0.4' was resolved as a dependency of 'BibleApp.Maui', but the dependency is using 'Xamarin.iOS' while 'BibleApp.Maui' is using 'net6.0-maccatalyst13.5' as its TargetFramework. There might be compatibility issues when MacCatalyst projects depend on Xamarin.iOS projects.
3>C:\Users\Robel\source\repos\BibleApp.Maui\BibleApp.Maui\BibleApp.Maui.csproj : warning NU1703: 'SQLitePCLRaw.lib.e_sqlite3.ios 2.0.4' was resolved as a dependency of 'BibleApp.Maui', but the dependency is using 'Xamarin.iOS' while 'BibleApp.Maui' is using 'net6.0-maccatalyst13.5' as its TargetFramework. There might be compatibility issues when MacCatalyst projects depend on Xamarin.iOS projects.
3>C:\Users\Robel\source\repos\BibleApp.Maui\BibleApp.Maui\BibleApp.Maui.csproj : warning NU1703: 'SQLitePCLRaw.provider.dynamic_cdecl 2.0.3' was resolved as a dependency of 'BibleApp.Maui', but the dependency is using 'Xamarin.iOS' while 'BibleApp.Maui' is using 'net6.0-maccatalyst13.5' as its TargetFramework. There might be compatibility issues when MacCatalyst projects depend on Xamarin.iOS projects.
3>C:\Users\Robel\source\repos\BibleApp.Maui\BibleApp.Maui\BibleApp.Maui.csproj : warning NU1703: 'SQLitePCLRaw.provider.internal 2.0.4' was resolved as a dependency of 'BibleApp.Maui', but the dependency is using 'Xamarin.iOS' while 'BibleApp.Maui' is using 'net6.0-maccatalyst13.5' as its TargetFramework. There might be compatibility issues when MacCatalyst projects depend on Xamarin.iOS projects.

__Originally posted by @nextcodelab in https://github.com/praeclarum/sqlite-net/issues/1056__

**Comment by shanoaice** [comment]
Still having a similar issue when targeting net6.0 on Windows:
```
Could not detect any platforms from 'net6.0-windows10' in 'C:\Users\Shanoa\.nuget\packages\sqlitepclraw.provider.e_sqlite3\2.0.7\lib\net6.0-windows10\SQLitePCLRaw.provider.e_sqlite3.dll', please tell the package authors
```

**Comment by ericsink** [comment]
The report by @shanoaice might be related, as it also involves net6.0-workload style TFMs, which are a likely source of trouble for the current SQLitePCLRaw release.  But I do note that the report above involves maccatalyst and iOS things, whereas the second one is net6.0-windows, which is a bit more surprising as a source of problems.  More attention on this area is needed.

**Comment by shanoaice** [comment]
@ericsink I find it quite interesting that after inspecting the NuGet package `SQLitePCLRaw.provider.e_sqlite3`, I do see an assembly under the folder `lib/net6.0-windows10` which resembles an assembly targeting net6.0-windows10, though I did not see the corresponding library in `SQLitePCLRaw.lib.e_sqlite3`:
![图片](https://user-images.githubusercontent.com/25174488/145660073-d203ed3a-626c-47fb-ac0a-5fa057d0bda7.png)
![图片](https://user-images.githubusercontent.com/25174488/145660089-fd4e790f-063c-4ceb-a1c4-c3853a4287df.png)

**Comment by ericsink** [comment]
Version 2.1.0 is now on nuget and should address net6.0-workload targeting issues.
