### ISSUE TITLE
2.1

### ISSUE THREAD

**Issue by ericsink** [ericsink/SQLitePCL.raw#441]
I have pushed 2.0.5 up to nuget, and now I plan to turn my attention to the next release, which I hope will be soon.  The ci/cd stuff makes my dev workflow much easier, thanks again to @filipnavara for making that happen.

The next one will probably be called 2.1.0.  The main reason for the bump of the minor version is that I want to do a few things that are a bit more net6.0-centric.  For example, I plan to switch the xamarin builds to use the new net6.0 workloads and tfms.

**Comment by ericsink** [comment]
@bricelam One item I wanted to raise to your attention:  I tried running a couple of the SQLite test suites in your repo against 2.1.0-pre20220207221914.

`Microsoft.Data.Sqlite.Tests.csproj` works

`EFCore.Sqlite.FunctionalTests.csproj` has one failure: 

```
[xUnit.net 00:00:07.49]     Microsoft.EntityFrameworkCore.Scaffolding.SqliteDatabaseModelFactoryTest.Column_storetype_is_set [FAIL]
  Failed Microsoft.EntityFrameworkCore.Scaffolding.SqliteDatabaseModelFactoryTest.Column_storetype_is_set [32 ms]
  Error Message:
   Assert.Equal() Failure
          ↓ (pos 0)
Expected: integer
Actual:   INTEGER
          ↑ (pos 0)
```

I saw something similar in my own test suite, and I think this is caused by a change in SQLite itself.  It looks like when a column is declared as type `int` or `integer`, the functions `sqlite3_column_metadata` and `sqlite3_column_decltype` now return the column type as `INTEGER`.

**Comment by bricelam** [comment]
Sounds OK to me. I'll fix the failures when we upgrade.

**Comment by ericsink** [comment]
2.1.0 is now released.
