### ISSUE TITLE
Adding snapshot api support in 2.0.5 breaks sqlcipher official builds on Xamarin.iOS

### ISSUE THREAD

**Issue by RandLennox** [ericsink/SQLitePCL.raw#452]
The snapshot support added in release 2.0.5 (#333) does not work with the officially supported builds from zetetic's current release (4.4.3).  The new symbols that have been added fail during the linking process.

This might be a problem with the "official, supported" zetetic sqlcipher library (it may not have included the snapshot symbols in it's sqlite build), but I can't really be sure if it's zetetic's problem or an SQLitePCLRaw problem.

Reverting back to 2.0.4 is the current workaround.

**Comment by sjlombardo** [comment]
@RandLennox yes, this is likely because  Zetetic packages aren't currently compiled with SQLITE_ENABLE_SNAPSHOT. We will adjust this in the next release of the official SQLCipher release (which should be forthcoming in the near future). Thank you for reporting this issue!

**Comment by ericsink** [comment]
Closing as "external".  Thanks!
