### ISSUE TITLE
Support for Alpine Linux Arm

### ISSUE THREAD

**Issue by danzel** [ericsink/SQLitePCL.raw#453]
Currently libraries are shipped for musl-x64 and linux-arm, but not musl-arm (or arm64).
Would be nice to have them to support alpine deployments on RPI devices. Thanks!

Related #192 #214

**Comment by danzel** [comment]
I've started on this and should have some PRs next week 🙏

**Comment by danzel** [comment]
Two PRs sent 💪

**Comment by ericsink** [comment]
I think these changes are available in prerelease 2.1.0-pre20220427180151, now on nuget.

**Comment by danzel** [comment]
Thanks!
We've moved off musl now so I'm not in a position to test.
