### ISSUE TITLE
2.07 and AnyCPU

### ISSUE THREAD

**Issue by gnimor** [ericsink/SQLitePCL.raw#460]
I have an SDK style project with target framework 472. I have read all the information in #444 and #446 but it seems for me that when I have set the platform target in my executable to "AnyCPU" the "e_sqlite3.dll" library is not copied to the output folder but with x86 or x64 it is.

My architecture is something like this:

MyApplication (AnyCPU) -----> Lib A (referencing Microsoft.Data.Sqlite and SQLitePCLRaw.bundle_e_sqlite3)

**Comment by gnimor** [comment]
Sorry for the long delay - I have attached a project where you can see the behavior.

The MyLib is using the Microsoft.Data.Sqlite and SQLitePCLRaw.bundle_e_sqlite3 package. The MyApp is just using the MyLib

MyApp (AnyCPU) -----> MyLib (referencing Microsoft.Data.Sqlite and SQLitePCLRaw.bundle_e_sqlite3)

after compiling the MyApp, the output folder does not contain the e_sqlite3.dll

[SQLITE.zip](https://github.com/ericsink/SQLitePCL.raw/files/7563789/SQLITE.zip)

**Comment by bricelam** [comment]
Possibly related to #252

**Comment by ericsink** [comment]
<fanfare/>

I am pleased to announce that #252 may finally have its long-awaited and well-deserved win.

**Comment by gnimor** [comment]
@ericsink When do you think is this version available via Nuget?

**Comment by ericsink** [comment]
Version 2.1.0 includes this fix and is now available on nuget.
