### ISSUE TITLE
Restore package is broken with last version of visual studio preview (.NET 6 iOS)

### ISSUE THREAD

**Issue by jona-1993** [ericsink/SQLitePCL.raw#467]
Hello,

I updated Visual studio 2022 preview to "17.1.0 Preview 3.0" and I can't restore my nuget packages.
 This package is broken (each versions):
`<PackageReference Include="SQLitePCLRaw.lib.e_sqlcipher.ios" Version="2.0.8-pre20220111224339" />`
 
It need the target "net6.0-ios". 

Error NU1202 Package SQLitePCLRaw.lib.e_sqlcipher.ios 2.0.8-pre20220111224339 is not compatible with net6.0-ios15.2 (.NETCoreApp,Version=v6.0). Package SQLitePCLRaw.lib.e_sqlcipher.ios 2.0.8-pre20220111224339 supports: xamarinios10 (Xamarin.iOS,Version=v1.0)

**Comment by ericsink** [comment]
I haven't added support for the new net6 xamarin TFMs.  It is definitely time for me to get that done.

**Comment by jweighell** [comment]
Would this cause the issue I'm having trying to use SQLite on iOS in a MAUI app?

[0:] An error occurred: 'e_sqlite3'. Callstack: ' at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
at SQLitePCL.Batteries_V2.Init()

**Comment by ericsink** [comment]
@jweighell That problem looks different.  The one at the top happens during package restore.  Yours is a failure at runtime.  Perhaps you could open a new issue?

**Comment by ericsink** [comment]
Preview release 2.1.0-pre20220207221914 has been pushed up to nuget.org.  It contains attempted fixes for this issue.  Testing feedback would be appreciated.

**Comment by jona-1993** [comment]
It's OK now, thank you ;)
