### ISSUE TITLE
[Question] How does this library relates to Microsoft.Data.SQLite

### ISSUE THREAD

**Issue by mstyura** [ericsink/SQLitePCL.raw#47]
@ericsink you have described a lot of `SQLite` .NET wrappers in readme, which makes much more clearer why there are so many libraries here, thank you very much for that.
Could you please mention [Microsoft.Data.SQLite](https://github.com/aspnet/Microsoft.Data.Sqlite) in readme and describe it's place in the ecosystem of whole bunch of other `SQLite` libs?

Thanks in advance.

**Comment by nberardi** [comment]
It is the same as Mono.Data.SQLite. https://github.com/ericsink/SQLitePCL.raw#how-does-this-compare-to-monodatasqlite Both are based off of ADO.NET

**Comment by ericsink** [comment]
Added to the readme.
