### ISSUE TITLE
MacCatalyst support

### ISSUE THREAD

**Issue by ericsink** [ericsink/SQLitePCL.raw#471]
the app works on iOS but crashes on maccatalyst

_Originally posted by @VladislavAntonyuk in https://github.com/ericsink/SQLitePCL.raw/issues/468#issuecomment-1032136588_

**Comment by edoust** [comment]
Are there any news on this, or is there any workaround? 
I can't get EntityFramework to run on net6.0-maccatalyst, it does run on net6.0-macos (xamarin20)

**Comment by ericsink** [comment]
No progress on this yet.  I need to figure out how to compile the C code for maccatalyst.

For example, the command line for iphone starts out like this:

```
xcrun --sdk iphoneos clang -O -miphoneos-version-min=6.0 -arch arm64 
```
And for macos:

```
xcrun --sdk macosx clang -dynamiclib -O -arch x86_64 
```

I assume it's similar to these, but I haven't spent any time yet looking for the answer.

**Comment by edoust** [comment]
Is there a documentation on how you did it for ios (end to end)? If not can you tell me on which code/ repo exactly you ran the above mentioned command?

Would like to have a quick look myself, since I need SQLite in maccatalyst

**Comment by ericsink** [comment]
There are no docs, but my build scripts for the native SQLite libraries are over in the ericsink/cb repo.

**Comment by VladislavAntonyuk** [comment]
it seems to be working fine now:
![image](https://user-images.githubusercontent.com/33021114/157937064-bb62d15a-550f-4344-9146-6e5c3daa6eb5.png)
you can try KanbanBoard and Sqlite samples from https://github.com/VladislavAntonyuk/MauiSamples

**Comment by ericsink** [comment]
@VladislavAntonyuk I haven't looked closely at your samples yet, but just to be clear for anybody else seeing this -- there is currently nothing in SQLitePCLRaw and nothing in the `e_sqlite3` build scripts that is specifically for maccatalyst support.  If anything works with `net6.0-maccatalyst`, it is an accident, and I don't know why it works.  I recently did a bunch of stuff to get the other net6.0-workloads going in the 2.1-prerelease versions, but nothing for maccatalyst.

I do plan to give this issue some real attention as soon as I can.

**Comment by VladislavAntonyuk** [comment]
@ericsink seems like Apple did a great job to make iOS code work on macOS with maccatalyst, But definitely waiting for your final release with official maccatyst support. Thank you!

**Comment by ericsink** [comment]
> seems like Apple did a great job to make iOS code work on macOS with maccatalyst

Maybe so, but I thought I saw somewhere that things should be specifically compiled for maccatalyst.  I need to confirm whether that's true.  If something seems to work when the docs and specs say it should not, then I wonder why.

And if something works when run from Visual Studio but not from the CLI, then it doesn't work.

:-)

**Comment by VladislavAntonyuk** [comment]
I didn't investigate it, but probably VS restores packages differently and packs SQLite iOS lib in MacCatalyst. it's the only 1 idea that comes to my mind so far.

**Comment by edoust** [comment]
@VladislavAntonyuk For me building in VS does not work at all, what version of VS are you using? Are you on an x86 or ARM machine?

**Comment by VladislavAntonyuk** [comment]
VS for mac 2022. Intel

**Comment by edoust** [comment]
I always get the error `clang++ exited with code 1` in `Xamarin.Shared.Sdk.targets`, that error is reproducible on two machines that are freshly installed, one with an M1 and one with an Intel processor

Both my machines have VS2022 (latest), Xamarin.Mac (latest) and the latest maui-maccatalyst workload installed

Do you have any special configuration on your system that might be related to this?

**Comment by VladislavAntonyuk** [comment]
Check XCode version.
Check MAUI version. Try install it again sudo dotnet workload install maui.
Clean bin/obj
First run the build with dotnet cli
It should build the app and restore packages 
Then open VS, select your mac to run the app and click Restore nuget packages on solution
Run build from VS. 
the app may ask for the access to the storage

**Comment by edoust** [comment]
@VladislavAntonyuk Can you please share your diagnostic build log (especially the `xcrun xlang` command from the `LinkNativeCode` target)? I found that in VS build this call fails, so I am interested to know against what `sqlite` lib you are linking

This is the error message I get: `ld: in [...]/obj/Debug/net6.0-maccatalyst/maccatalyst-x64/linker-cache/e_sqlite3.a(sqlite3.o), building for Mac Catalyst, but linking in object file built for iOS Simulator, file '[...]/obj/Debug/net6.0-maccatalyst/maccatalyst-x64/linker-cache/e_sqlite3.a' for architecture x86_64` 

For RID `maccatalyst-arm64` it says the lib was built for `iOS` not `iOS Simulator`

@ericsink Thanks for hinting at the cb repo, I could [slightly modify your script](https://github.com/edoust/cb/commit/a07c0564439115af516ee4a4a9ac67467c3bfeb1) to build a MacCatalyst compatible version of `e_sqlite.a`. Currently I can manually copy that file to the `linker-cache` folder, but I need this to work for CLI (agent) builds as well

Which repo is the base for the NuGet that will contain the maccatalyst support once you publish it? I would like to fork it and create a private NuGet for my CLI (agent) build, since I need EF Core to work on maccatalyst as soon as possible

**Comment by VladislavAntonyuk** [comment]
[BuildLogs.txt](https://github.com/ericsink/SQLitePCL.raw/files/8239454/BuildLogs.txt)

**Comment by edoust** [comment]
Thanks you, but this log does not contain the `clang` commands since it was not a full rebuild, so those targets were skipped. Can you please do a full rebuild after having deleted `bin` and `obj` folders and only building the target framework `maccatalyst`?

Also, please share the `e_sqlite.a` file that is located in `obj/Debug/net6.0-maccatalyst/maccatalyst-x64/linker-cache`. I would like to check whether you get a library built for `maccatalyst` already, and if so where that file originally came from

**Comment by VladislavAntonyuk** [comment]
1. Delete obj/bin
3. Run VS and restore packages and build app. Output: [BuildLogs.txt](https://github.com/ericsink/SQLitePCL.raw/files/8239614/BuildLogs.txt)
4. Run dotnet build -t:Run -f net6.0-ios
5. Run dotnet build -t:Run -f net6.0-maccatalyst
output:
[BuildLogs.txt](https://github.com/ericsink/SQLitePCL.raw/files/8239758/BuildLogs.txt)
6. Back to VS and run the app.

**Comment by edoust** [comment]
Thanks for sharing the log files. From my understanding in order to be able to use the (iOS-)OS provided SQLite implementation, it would require some reference to it, for example by importing the SQLite header file into a referenced (native) library and actually using its methods. I would assume that `SQLitePCLRaw.provider.dynamic_cdecl` is a passthrough that relays all calls to `e_sqlite3` to the OS-provided version of SQLite (??)

But then I still don't get how this would work with MacCatalyst, since as far as I know MacCatalyst is not just emulating an iOS environment (like `x86` env may be emulated on `ARM`) but it requires a dedicated build for `maccatalyst`

- Do you get a running `.app` file in the end? If so, can you copy that to some other folder and start by double-clicking it?
- Can you please try what happens if you set only `macatalyst` as target framework and then clean? Does it build & run then?

On my end I got the app working using the CLI by doing the following steps:

1. Create a `maccatalyst` build of SQLite using the scripts provided by @ericsink 
2. Referencing the generated `libe_sqlite3.dylib` with a `<NativeReference Include="/.../libe_sqlite3.dylib" Kind="Dynamic" />`
3. Build using CLI `dotnet build -t:restore,build KanbanBoard.csproj -f net6.0-maccatalyst`

The resulting `.app` packages work for both the `maccatalyst-x64` and `maccatalyst-arm64` RIDs, also both contain the `libe_sqlite.dylib` file (~2MB) inside the package

**Comment by VladislavAntonyuk** [comment]
as @ericsink mentioned this lib so far works only with net6.0-ios. https://github.com/ericsink/SQLitePCL.raw/blob/9d5a8b6651f5feb31605c7e978aa0f42ad21f6a8/src/SQLitePCLRaw.bundle_e_sqlite3/SQLitePCLRaw.bundle_e_sqlite3.csproj#L4

there is no net6.0-maccatalyst and net6.0-mac target frameworks

**Comment by edoust** [comment]
For Catalyst it should do a fallback to `netstandard2.0`. I was just wondering about your logs not showing a native compilation/linking process, so I just don't see how you would get a runnable (deployable) macOS `.app` package out of it

For me it is working now using a privately published NuGet so I will use that approach going forward

**Comment by edoust** [comment]
@ericsink 

Could you already have a look into rebuilding the NuGet packages?
Do you think integrating `maccatalyst` requires code changes, or should this be done by integrating the `dylib` files into the `lib` project and then compiling the bundle project with `maccatalyst` support?

**Comment by ericsink** [comment]
@edoust I think what you said is sufficient. I've made those changes and pushed them up. However, the CI builds are currently failing for other reasons. It looks like something in the net6.0-ios SDK broke with this week's preview release. I am investigating.

**Comment by ericsink** [comment]
Looks like the problem is xamarin/xamarin-macios/issues/14434

**Comment by ericsink** [comment]
Version 2.1.0-pre20220318192836 has been pushed up to nuget.  It contains progress on maccatalyst support.

I tried a very basic test and it seems to work.  

One caveat:  I placed the native binaries under `net6.0-maccatalyst15.2`, so it is necessary to target at least that version in order to get the dylib into the build.  If I just set TargetFramework to `net6.0-maccatalyst` (without specifying the version), or if I specify a version below 15.2, the resulting app crashes because it cannot find the dylib.  I suspect I don't need to specify a minimum version that high, so another fix is probably needed here.

**Comment by VladislavAntonyuk** [comment]
it works fine. I set TargetFramework to net6.0-maccatalyst  and min version to 15.2

**Comment by edoust** [comment]
For me it does not work automatically, I need to add a NativeReference explicitly, or else the libe_sqlite.dylib is not put in the app package (I can only use test using the CLI, since VS2022 for mac preview 7 does not support .NET 6 Xamarin projects at the moment)

**Comment by VladislavAntonyuk** [comment]
@edoust could you try this sample https://github.com/VladislavAntonyuk/MauiSamples/blob/main/KanbanBoard/KanbanBoard.csproj#L36?

**Comment by edoust** [comment]
Your project is working for `net6.0-maccatalyst15.2`, without the `libe_sqlite.dylib` being present in the app package. I narrowed it down to this reference being present, the other ones are not required.
`<PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.0-pre20220318192836" />`

I will re-test my project that with the bundle green reference as soon as I can. Since I installed VS for Mac 2022 preview 7, I can't run .NET6 Xamarin projects anymore, so I am currently blocked (others are too), does VS preview 7 work for you?

**Comment by VladislavAntonyuk** [comment]
Thank you, I will remove unused packages.
VS4Mac doesn't work with MAUI. At least with this release

**Comment by edoust** [comment]
@ericsink 
Do you have any idea why bundle green would work whereas bundle e_sqlite would not?

**Comment by VladislavAntonyuk** [comment]
They removed this feature from this preview. Probably because of a lot of breaking changes with the latest MAUI. But I know it works in private preview. So probably with the next release they should enable MAUI support again.

**Comment by ericsink** [comment]
@edoust bundle_green is identical to bundle_e_sqlite3 except that on iOS it uses the system-provided SQLite library instead of e_sqlite3.  Now that we have maccatalyst support, I made it work the same way for bundle_green.

**Comment by bstrother1** [comment]
So is Sqlite working with MacCatalyst now? If so what configurations are required? I'm not seeing any new releases/prereleases since this ticket was created and its still open. Thanks!

**Comment by ericsink** [comment]
I think the latest pre-release works with MacCatalyst.  Let me know if you have trouble with it.

I plan to make a non-pre release very soon.

**Comment by edoust** [comment]
For me it does not work, I don't know why, none of the preview bundles do. As a workaround I created a custom NuGet file that contains an explicit `NativeReference`, and I reference that in addition to the official preview packages

I am using the binaries that you checked into the `cb` repo in my [custom NuGet](https://github.com/ericsink/SQLitePCL.raw/files/8515396/nuget-as-zip.zip)

**Comment by ericsink** [comment]
OK I need to check this again.  I'll see if I can create a working sample.

**Comment by ericsink** [comment]
Confirmed: I can repro the broken behavior you described.  I am working on a fix...

**Comment by ericsink** [comment]
Prerelease 2.1.0-pre20220427180151 is now on nuget, and contains a fix that works for me.

**Comment by VladislavAntonyuk** [comment]
Why does it require 15.2 as a minimum version?

**Comment by ericsink** [comment]
I don't remember why I did that. What **should** it be?

**Comment by VladislavAntonyuk** [comment]
I think it should be the same as for .NET MAUI.
14.2 for iOS and 14 for MacCatalyst

**Comment by ericsink** [comment]
@VladislavAntonyuk Can you link to the source of those version numbers?

I remember why I chose 15.2 -- when I build a project specifying just `net6.0-maccatalyst` as the TFM, under the hood, the SDK seems to interpret that as `net6.0-maccatalyst15.2`.  I know I've seen something that specifies the behavior of a `net6.0-whatever` TFM which doesn't specify a version, but I can't remember where.

**Comment by coolbluewater** [comment]
@ericsink, when do you think a nuget that supports Mac Catalyst (prerelease or otherwise) will be available?
Many thanks for this library!

**Comment by ericsink** [comment]
@coolbluewater Have you tried Prerelease 2.1.0-pre20220427180151 mentioned above?  I *think* it works with maccatalyst, except of course with the caveat about the minimum supported platform versions as mentioned by @VladislavAntonyuk subsequently.

With .NET MAUI in RC2 now, I need to get the release done soon -- I've just been waiting for any last minute fixes to a couple of other issues.

**Comment by coolbluewater** [comment]
@ericsink I was already on that version. I changed the `<SupportedOSPlatformVersion>` on the two projects that are using SQLitePCLRaw (but not on the other projects - is that needed). Unfortunately, I still get this exception:

```
System.DllNotFoundException: sqlite3
   at SQLitePCL.SQLite3Provider_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
   at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
   at SQLitePCL.Batteries_V2.Init()
```

**Comment by ericsink** [comment]
@coolbluewater You've got something else going wrong.  What package references do you have?

**Comment by coolbluewater** [comment]
@ericsink: 
In a library csproj:
```
    <PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.0-pre20220427180151" />
```
And also in the executable's caproj:
```
    <PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.0-pre20220427180151" />
```

**Comment by ericsink** [comment]
The attached sample works for me using either  bundle_green and bundle_e_sqlite3.  Does your project configuration differ in some way?

[mc.tar.gz](https://github.com/ericsink/SQLitePCL.raw/files/8626855/mc.tar.gz)

**Comment by coolbluewater** [comment]
I get the same exception with the sample you attached.

**Comment by ericsink** [comment]
@coolbluewater One difference is you said you're using the IDE and I'm using the command line.  Does it work for you from the command line?  (`cd` into that directory and type `dotnet run`)

**Comment by coolbluewater** [comment]
@ericsink - yes, that worked. (A red screen appears with "Hello, Catalyst 3.37.0".)

**Comment by coolbluewater** [comment]
@ericsink Are you able to reproduce the crash via the IDE?

**Comment by ericsink** [comment]
Okay, so that's progress.

I don't have the latest VS for Mac installed right now, but as soon as I can, I will install it and try to reproduce what you are seeing.

**Comment by coolbluewater** [comment]
Awesome-o. Thanks.

**Comment by coolbluewater** [comment]
Incidentally, your project uses a TFM of .net6.0-maccatalyst15.2. I don't believe there is such a TFM - did you make this one up? The official list is at https://docs.microsoft.com/en-us/dotnet/standard/frameworks.

**Comment by edoust** [comment]
@ericsink Just wanted to let you know the latest update is working for me on `net6.0-maccatalyst15.2`, did  not test other versions

**Comment by ericsink** [comment]
@coolbluewater In the page you linked, check out the section on "OS Version in TFMs":

https://docs.microsoft.com/en-us/dotnet/standard/frameworks#os-version-in-tfms

**Comment by coolbluewater** [comment]
@ericsink - Ah, I see. Thanks!

**Comment by edoust** [comment]
You need to install the workload from the preview feed

**Comment by coolbluewater** [comment]
@edoust - Ok, will do. Also, what version of Xcode do you have?

**Comment by edoust** [comment]
I got `13.3.1` and I am compiling with RID `maccatalyst-arm64`, I did not test with `maccatalyst-x64`

**Comment by coolbluewater** [comment]
Thanks. I had installed Xcode 13.3.0 and had to downgrade to 13.2.1 because of a bug in Xcode. Will try to update to Xcode 13.3.1. I am running on x64, so fingers crossed.

**Comment by coolbluewater** [comment]
@edoust, what command line did you use to install the maui preview workload? I used this one from the dotnet/maui wiki:

`sudo dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/rc.2.json --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json`

However this gives an error that the android sdk manifest is not found:

`Workload installation failed: Failed to install manifest microsoft.net.sdk.android version 32.0.300-rc.2.27: microsoft.net.sdk.android.manifest-6.0.200::32.0.300-rc.2.27 is not found in NuGet feeds https://aka.ms/dotnet6/nuget/index.json;https://api.nuget.org/v3/index.json"..`

I couldn't find an open issue regarding this, and wondered if you ran into something similar.

**Comment by edoust** [comment]
I use `sudo dotnet install workload maccatalyst` since I only compile for Catalyst using the Uno framework... 

I use this custom [nuget.config](https://github.com/ericsink/SQLitePCL.raw/files/8636227/nuget.txt)
(rename to `nuget.config`) and then execute the command in the context of that nuget config file

**Comment by coolbluewater** [comment]
Thanks - what is the source of that nuget config? Perhaps I'll find more info there about installing the maui preview...

**Comment by edoust** [comment]
The nuget file is not MAUI related it just contains the global feeds for [dotnet](https://github.com/dotnet/installer) and xamarin... Looks like if you specify the rc.2 json you also need more feeds, see [here](https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md)...

Also it seems like an rc.4 rollback file is available [here](https://maui.blob.core.windows.net/metadata/rollbacks/rc.4.json)

**Comment by VladislavAntonyuk** [comment]
use this guide to install it https://github.com/dotnet/maui/wiki/macOS-Install

**Comment by coolbluewater** [comment]
@edoust @VladislavAntonyuk Thanks guys, but I'm having no luck with installing either rc2 or rc4. Have you actually succeeded installing either maui rc2 or rc4? Specifically, the install halts at the first item (the android sdk) and says that it cannot find the mentioned version. 

I've tried this to install rc2:

`dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/6.0.300/rc.2.json --source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-a21b9a2d/nuget/v3/index.json --source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-572aeedc/nuget/v3/index.json --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json --source https://api.nuget.org/v3/index.json`

And then I tried replacing the rollback file with the url given by @edoust for rc4:

`sudo dotnet workload install maui --from-rollback-file https://maui.blob.core.windows.net/metadata/rollbacks/rc.4.json --source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-a21b9a2d/nuget/v3/index.json --source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-572aeedc/nuget/v3/index.json --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json --source https://api.nuget.org/v3/index.json`

But neither work - it looks like the rollback file and the feeds must be mutually compatible, i.e. the feeds need to have items with the versions mentioned in the rollback file. Any ideas?

**Comment by VladislavAntonyuk** [comment]
I use rc2, because it is the latest released version.
I know about upcoming rc3 very soon.

try to uninstall all workloads and install MAUI again

**Comment by coolbluewater** [comment]
@VladislavAntonyuk - could you please list the command line for installing maui rc2?

**Comment by edoust** [comment]
@coolbluewater 
I just tested and using this nuget config it works
````xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="dotnet6" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json" />
    <add key="xamarin" value="https://pkgs.dev.azure.com/azure-public/vside/_packaging/xamarin-impl/nuget/v3/index.json" />
    <add key="public"  value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json" />
    <add key="xx" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-a21b9a2d/nuget/v3/index.json"/>
    <add key="xy" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-572aeedc/nuget/v3/index.json" />
    <add key="xz" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json" />
  </packageSources>
</configuration>
````

Then in the same directory of the nuget config execute the command `sudo dotnet workload install maui --from-rollback-file https://maui.blob.core.windows.net/metadata/rollbacks/rc.4.json` or whichever rollback file you choose

**Comment by coolbluewater** [comment]
@VladislavAntonyuk - that goes in a file named `nuget.config`, correct?
I ran the command you listed and unfortunately get the same error as I previously got:

```
Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Updated advertising manifest microsoft.net.sdk.android.
Updated advertising manifest microsoft.net.sdk.tvos.
Updated advertising manifest microsoft.net.sdk.maui.
Updated advertising manifest microsoft.net.sdk.ios.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Updated advertising manifest microsoft.net.workload.mono.toolchain.
Updated advertising manifest microsoft.net.sdk.macos.
Updated advertising manifest microsoft.net.workload.emscripten.
Installing workload manifest microsoft.net.sdk.android version 32.0.300-rc.3.45…
Workload installation failed. Rolling back installed packs...
Installing workload manifest microsoft.net.sdk.android version 31.0.200-preview.14.106…
Installation rollback failed: Failed to install manifest microsoft.net.sdk.android version 31.0.200-preview.14.106: The transaction has aborted..
Workload installation failed: Failed to install manifest microsoft.net.sdk.android version 32.0.300-rc.3.45: microsoft.net.sdk.android.manifest-6.0.200::32.0.300-rc.3.45 is not found in NuGet feeds https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json;https://pkgs.dev.azure.com/azure-public/vside/_packaging/xamarin-impl/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-a21b9a2d/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-572aeedc/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json"..
```

**Comment by edoust** [comment]
Do you have dotnet 6.0.300 installed? can you check by running `dotnet --info`?

**Comment by VladislavAntonyuk** [comment]
You can take a look how we install dotnet and Maui workload https://github.com/CommunityToolkit/Maui/blob/main/azure-pipelines.yml

**Comment by coolbluewater** [comment]
@VladislavAntonyuk - thanks! I had moved back and forth between runtimes and was on a different version. After installing 6.0.300 I was able to install maui rc4 using the above steps.

**Comment by coolbluewater** [comment]
@ericsink I built my app for maccatalyst15.2 (I think!), but still no sqlite love. Are you able to reproduce the failure?

**Comment by ericsink** [comment]
@coolbluewater Are you talking about above, where it works on the command line but not in the IDE?  If so, no, I haven't found time to install VS for Mac and try it yet.

**Comment by VladislavAntonyuk** [comment]
I can just add that VS4Mac does not fully support MAUI. It will be added in 17.1.

**Comment by coolbluewater** [comment]
@VladislavAntonyuk - Yes, that's correct. Do we know whether sqlite works using Visual Studio for Windows, which fully supports maui?

**Comment by VladislavAntonyuk** [comment]
Just checked, it works on Windows. 
To be honest it works on VS4Mac as well. You only need to restore packages using cli.

**Comment by coolbluewater** [comment]
@VladislavAntonyuk - thanks! Which packages? Any special instructions to restore? VsMac keeps restoring packages a lot. Do you see the same behavior?

**Comment by VladislavAntonyuk** [comment]
I first run dotnet restore. Than open VS and run build. In that case VS don't restore packages again. Seems like VS treats iOS and Mac catalyst as the same target framework during package restore.

**Comment by coolbluewater** [comment]
@VladislavAntonyuk thanks! Do you still need to change the os version for the maccatalyst target?

**Comment by VladislavAntonyuk** [comment]
yes, 15.2 is the minimum supported version

**Comment by ericsink** [comment]
Version 2.1.0 is on nuget.  Any further maccatalyst-specific problems, please open a new issue.

**Comment by edoust** [comment]
I am still having the exact same issue with `v2.1.0`... :(

**Comment by ericsink** [comment]
I believe the latest status of this was that it works fine on the command line but doesn't work with Visual Studio for Mac. @edoust Is that true for you?

If so, that means your problem is possibly related to #489

**Comment by edoust** [comment]
No, I am doing a CLI build with this command - it does not change the problem whether I do it in VS or using dotnet

`dotnet build %(SolutionFile) --framework net6.0-maccatalyst15.4`

Will keep an eye on it, for now I am still using your preview package alongside the custom nuget that contains your native lib

**Comment by ericsink** [comment]
@edoust If you can construct a minimal repro project, please open a new issue and post it there.

**Comment by edoust** [comment]
Yes, will do it these days
