### ISSUE TITLE
Sqlcipher native library loading broken for .NET 6 Mac OS

### ISSUE THREAD

**Issue by jona-1993** [ericsink/SQLitePCL.raw#473]
Hello,

I can't run my .NET 6 project for Mac. I have this error:

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: */libe_sqlcipher.dylib
Referenced from: /Users/USER/Desktop/*/MedinectCoreMacOS.app/Contents/MacOS/MedinectCoreMacOS
Reason: tried: '*/libe_sqlcipher.dylib' (no such file), '/usr/local/lib/libe_sqlcipher.dylib' (no such file), '/usr/lib/libe_sqlcipher.dylib' (no such file)
(terminated at launch; ignore backtrace)

Application Specific Information:
Library not loaded: ./bin/e_sqlcipher/mac/x86_64/libe_sqlcipher.dylib
Referenced from: /Users/jona1993/Desktop/MedinectCore/MedinectCoreMacOS/bin/Debug/net6.0-macos/osx-x64/MedinectCoreMacOS.app/Contents/MacOS/MedinectCoreMacOS
Reason: tried: './bin/e_sqlcipher/mac/x86_64/libe_sqlcipher.dylib' (no such file), '/usr/local/lib/libe_sqlcipher.dylib' (no such file), '/usr/lib/libe_sqlcipher.dylib' (no such file)

In my cproj:

```
<PackageReference Include="EFCore.BulkExtensions" Version="3.4.0" />
<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.22" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="3.1.22" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="3.1.22" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="3.1.22" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="3.1.22" />
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.22" />
<PackageReference Include="MSBuild.Sdk.Extras" Version="3.0.44">
<PrivateAssets>all</PrivateAssets>
<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
<PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.0-pre20220207221914" />
<PackageReference Include="SQLitePCLRaw.core" Version="2.1.0-pre20220207221914" />
<PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher" Version="2.1.0-pre20220207221914" />
```

libe_sqlcipher.dylib exists in:
- /Users/jona1993/Desktop/MedinectCore/MedinectCoreMacOS/bin/Debug/net6.0-macos/osx-x64/libe_sqlcipher.dylib 
- /Users/jona1993/Desktop/MedinectCore/MedinectCoreMacOS/bin/Debug/net6.0-macos/osx-x64/MedinectCoreMacOS.app/Contents/MonoBundle/libe_sqlcipher.dylib

**Comment by ericsink** [comment]
One problem I see is that you should never have two SQLitePCLRaw bundles.  If you remove the `PackageReference` for `bundle_green`, does the problem persist?

**Comment by ericsink** [comment]
OK.  I just constructed a minimal sample that works.  We need to figure out how my sample is different from what you're doing.

My sample is basically just:

dotnet workload install macos
dotnet new macos
dotnet add package sqlitepclraw.bundle_e_sqlcipher
change the version number of that PackageReference to 2.1.0-pre20220207221914
add SQLitePCL.Batteries.Init() to AppDelegate.DidFinishLaunching()
(I actually took it a bit further, creating a sqlite file with a table in it, but the above would be sufficient)

Can you provide a buildable sample that demonstrates the problem and post it here as an attachment?  The more minimal it is, the more helpful it is.

**Comment by jona-1993** [comment]
Same issue with your test:

```
-------------------------------------------------------------------

You may only use the Microsoft .NET Core Debugger (vsdbg) with

Visual Studio Code, Visual Studio or Visual Studio for Mac software

to help you develop and test your applications.

-------------------------------------------------------------------

dyld[8657]: Library not loaded: ./bin/e_sqlcipher/mac/x86_64/libe_sqlcipher.dylib

  Referenced from: /Users/jona1993/Desktop/testMACNET6/bin/Debug/net6.0-macos/osx-x64/testMACNET6.app/Contents/MacOS/testMACNET6

  Reason: tried: './bin/e_sqlcipher/mac/x86_64/libe_sqlcipher.dylib' (no such file), '/usr/local/lib/libe_sqlcipher.dylib' (no such file), '/usr/lib/libe_sqlcipher.dylib' (no such file)

The program '[8657] testMACNET6' has exited with code 1 (0x1).

The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
```

[testMACNET6.zip](https://github.com/ericsink/SQLitePCL.raw/files/8122662/testMACNET6.zip)

**Comment by ericsink** [comment]
@jona-1993 I tried your test project and it works for me.

More specifically, I downloaded your test project, unzipped it, removed the `bin` and `obj` directories, and typed `dotnet run`.  I am not using Visual Studio or Rider.

I am curious if this works for you from the command line instead of the IDE.

**Comment by jona-1993** [comment]
No, it doesn't works.
I tested:
dotnet clean
dotnet build
dotnet run

Same error..

**Comment by jona-1993** [comment]
It works now. I don't now how I fixed that..
An update maybe?
