### ISSUE TITLE
Error using double or float values with WebAssembly

### ISSUE THREAD

**Issue by mark-cb** [ericsink/SQLitePCL.raw#480]
Seeing a bug with the latest preview and also see the same bug in Steve Sandersons Blaze Orbital sample when using double/float in entity classes. Works fine with decimals! Tried with EF Core and SQLite-net Simple repro here:

https://github.com/mark-cb/BlazorSQLiteWasm

Seems that the issue is not purely related to the preview version.

Decimals work fine.

Error:
/__w/1/s/src/mono/mono/mini/aot-runtime-wasm.c:113 /__w/1/s/src/mono/mono/mini/aot-runtime-wasm.c:113
Uncaught ExitStatus

**Comment by ericsink** [comment]
@bricelam Has this problem caught your eye anywhere yet?  I'm having trouble thinking of an idea that doesn't sound dumb (like a compiler bug in emscripten).

I looked at the compiler flags for emscripten but I don't see anything obviously wrong.

My next step in the investigation would be to take the wasm file, write a little code in C to call some basic SQLite functions, compile the whole thing to wasm, and try running it under wasmtime.  Just to verify that the sqlite.wasm file is legit.

**Comment by bricelam** [comment]
Sounds like an issue with interop in the .NET Wasm runtime. @mark-cb can you file an issue on [dotnet/runtime](https://github.com/dotnet/runtime) so they can investigate?

**Comment by mark-cb** [comment]
Issue reported with sorbet runtime here: https://github.com/dotnet/runtime/issues/67970

**Comment by ericsink** [comment]
AFAICT, this was resolved by a change in dotnet/runtime.
