### ISSUE TITLE
How do I tell SQLitePCL where e_sqlite3 is?

### ISSUE THREAD

**Issue by Ryan2065** [ericsink/SQLitePCL.raw#484]
I'm working on a project where I run Entity Framework Core in PowerShell.

Because of this, all dll loads happen at runtime in a non-normal way. In general this isn't a huge deal, but for this library (well EntityFramework Core Sqlite), it cannot find e_sqlite3.

I've hooked up an assembly load context into ```AssemblyLoadContext.Default.Resolving``` and don't see this dll try to be loaded. I've also set a resolving method to ```AppDomain.CurrentDomain.AssemblyResolve``` but don't see e_sqlite3 come in there.

I can't just copy the .dll to base folder because this may run on Linux, Windows, or OSX.  I know exactly where the right dll is programmatically (in base folder\runtimes\<specificruntime>\native), I just need a way to tell SQLitePCL where it is.

How can I do that?

**Comment by ericsink** [comment]
You might look at `NativeLibrary.SetDllImportResolver()`.  I think it would allow you to intercept `DllImport` and specify where the native library is.
