### ISSUE TITLE
System.Exception : Library e_sqlite3 not found

### ISSUE THREAD

**Issue by pengweiqhca** [ericsink/SQLitePCL.raw#485]
Can't load e_sqlite3 on .NETFramework when use `dotnet test`, because dll be cached, Location != `CodeBase` and Location != `Output Location`
[`assy.Location`](https://github.com/ericsink/SQLitePCL.raw/blob/master/src/common/nativelibrary_for_netstandard2.cs#L356) also include `CodeBase`

**Comment by ericsink** [comment]
Try setting `"shadowCopy": false` in `xunit.runner.json`.

**Comment by pengweiqhca** [comment]
Thanks, solved.
