### ISSUE TITLE
Add a way to configure root path on windows

### ISSUE THREAD

**Issue by CheloXL** [ericsink/SQLitePCL.raw#50]
I would like to have an option where I can configure from where the library will load/search the interop .dlls. 

Right now, you are using AppDomain.CurrentDomain.BaseDirectory, but on AppDomains created dynamically, that path returns null.

**Comment by ericsink** [comment]
For now I just want to acknowledge that I've seen this, but I'm departing for a trip.  I will look at this issue approximately two weeks from now when I return from my travels.

**Comment by CheloXL** [comment]
Excellent, no problem!

**Comment by ericsink** [comment]
So do you have a specific idea for how you want this override to work?

**Comment by CheloXL** [comment]
Not really, but I suppose that with a static call. This would mean that you can't initialize the library in the static ctor (at least do not load the .dll). Of couse, once loaded, you can't change that path... it's a one-time configuration.

**Comment by ericsink** [comment]
I'll experiment with an idea or two.  I want to make sure that any change causes no breakage to existing behavior.

**Comment by ericsink** [comment]
Wondering if it might be sufficient to simply remove this line:

    throw new Exception("sqlite3.dll was not loaded.");

In other words, if the attempt to pre-load the DLL fails, just go on and allow the pinvoke mechanism to do what it usually does.  If sqlite3.dll is in the path, it should get found.

**Comment by CheloXL** [comment]
Mmm.. that may work. I'm not quite sure about what .net does when finding for .dlls that are not managed. I'm using the event AssemblyResolve to load all my managed assemblies, but sqlite3 doesn't fire an event (since it is unmanaged).

**Comment by ericsink** [comment]
I've pushed the change I described.

**Comment by ericsink** [comment]
0.8.1-pre2 contains this fix.  Let me know how it works for your situation?  Thanks.

**Comment by CheloXL** [comment]
It seems to be working!... the only issue is that I have to drop the correct implementation (x86/x64) into the root folder. But at least that works, and I can run the detection code and copy the correct file there...

**Comment by ericsink** [comment]
0.8.1 has been pushed to nuget.  Closing this issue.

**Comment by AArnott** [comment]
For posterity, the change in question is commit b0c69dc64b67571322bb3869a6d68624e2380b97
