### ISSUE TITLE
Unity Support, on M1 Mac (DllNotFoundException: e_sqlite3 assembly:<unknown assembly> type:<unknown type> member:(null))

### ISSUE THREAD

**Issue by ecsplendid** [ericsink/SQLitePCL.raw#501]
Hey folks

I get this error. Unity is a pain. I want to use the sqlite library https://github.com/praeclarum/sqlite-net -- in our code I noticed that it was using the code from this library from 12 years ago, although now after all this pain I am starting to see why. We want to update to the latest version of the library because we're getting all sorts of threading crashes. Before it was presumably loading in the sqllite lib, installed on my main system. So I updated to the latest version of sqlite-net, and that was what led me to need to install this library. 

I have used the "NuGet plugin" for Unity, installed a combination of packages until I could get it building -- 

![image](https://user-images.githubusercontent.com/6911390/181236858-cde50ee2-0506-414d-9d31-31f0b4357412.png)

Which is to say;

- SQLitePCLRaw.provider.e_sqlite3.2.1.0
- SQLitePCLRaw.core.2.1.0
- SQLitePCLRaw.bundle_e_sqlite3.2.1.0

```
DllNotFoundException: e_sqlite3 assembly:<unknown assembly> type:<unknown type> member:(null)
SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number () (at <7158634a0cea490799582053c6fc6ea6>:0)
SQLitePCL.raw.SetProvider (SQLitePCL.ISQLite3Provider imp) (at <00c3759168224530a91b0fc2aa365b59>:0)
SQLitePCL.Batteries_V2.Init () (at <8af1e3e41bee433e83bc9d8d616eb39c>:0)
SQLite.SQLiteConnection..cctor () (at <01c96d411fe34bd5940c99a56515582b>:0)
Rethrow as TypeInitializationException: The type initializer for 'SQLite.SQLiteConnection' threw an exception.
DataService..ctor (System.String DatabaseName) (at Assets/Scripts/DataHandler.cs:34)
Database..ctor () (at Assets/Scripts/Database.cs:7)
Logger..ctor (System.String tag_) (at Assets/Scripts/Logger.cs:10)
AudioProcessor.Awake () (at Assets/Scripts/AudioProcessor.cs:61)
```

When I look in the nuget folders which were downloaded, I don't see a .dylib which presumably my mac needs. The Unity nuget manager only downloads the .net standard 2 folder, if I download with another package manager, I can see such a file on the osx bundle

![image](https://user-images.githubusercontent.com/6911390/181238167-a9e61ac2-76e0-4507-af56-8f20cc84a060.png)

If I install with the unity package manager, the dylib is excluded

![image](https://user-images.githubusercontent.com/6911390/181238396-24cab07e-f4fc-471f-831a-906006cd5b01.png)

If I copy the runtimes and build folders back in, it doesn't stop the dll not found error. 

Perhaps I need to copy the `libe_sqlite3.dylib` file somewhere, but I have no idea where... 

@ericsink we would pay you for an hour of consultancy to help us troubleshoot, interested?

Best 
Tim

**Comment by ericsink** [comment]
(let's hold off on the paid consulting idea for the moment)

I'm pretty sure this library doesn't work with Unity.  I would like to figure things out and make that happen, but I don't have any  experience with Unity.

Can anyone here summarize the issues?  At first glance, this looks like a target framework problem.

**Comment by bricelam** [comment]
IIRC, NuGetForUnity doesn't handle the `runtimes` directory of packages. You need to manually add it to your project (next to the `lib` directory), then configure the **Platform settings** for each native e_sqlite3 library. Here's a screenshot of a demo I did a few years ago:

![image](https://user-images.githubusercontent.com/1226749/181583839-4de70a00-557a-4060-a1af-14670da5d4d0.png)

**Comment by ecsplendid** [comment]
Thanks so much for the help, that was very useful!

I tried this, and I now get a message saying that the .dylib is an x64, not an apple silicone. I guess this PCL library doesn't bundle the assembly for M1 anyway? But this is very useful thanks so much

**Comment by ericsink** [comment]
SQLitePCLRaw does include a dylib for M1.

In the nuget package `SQLitePCLRaw.lib.e_sqlite3`, it should be at the path `runtimes/osx-arm64/native/libe_sqlite3.dylib`.

**Comment by ecsplendid** [comment]
Ah - thanks for the nudge. This might be another weird Unity NuGet behaviour. It guesses which platform you are on, and deletes the other assemblies. 

I tried using the nuget command line to download your package- 

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/6911390/181902835-5b05007a-e8e1-4c70-a98f-33d2f23ad99a.png">

Then copied the correct assembly in-

```
osx-x64
        │   └── native
        │       └── libe_sqlite3.dylib

```

And... it works!

<img width="985" alt="image" src="https://user-images.githubusercontent.com/6911390/181902802-457e3b26-f5ce-43da-b5b5-7547517af731.png">

Thank you both so much
