### ISSUE TITLE
no support for set_authorizer

### ISSUE THREAD

**Issue by pm100** [ericsink/SQLitePCL.raw#51]
I wonder why its not there and not mentioned. I could add it but I am scared off by the dire warning about trying to build it myself

**Comment by bordoley** [comment]
I have a pr out for that: https://github.com/ericsink/SQLitePCL.raw/pull/35

**Comment by bordoley** [comment]
It might need to be updated with the changes Eric made to fix callback functions a couple months back.

**Comment by ericsink** [comment]
I'll take a look and try to get that PR incorporated as part of the current wave of changes I'm working on.

**Comment by bordoley** [comment]
@ericsink saw you merged my PR. I just did a cursory look at it. Are you going to update it to store the the authorizer_hook per database before release?

**Comment by ericsink** [comment]
Yes, I will.

--
E

**Comment by ericsink** [comment]
I have pushed 0.8.1-pre1 to nuget.  It contains this fix.  Any testing on that build would be appreciated.

**Comment by bordoley** [comment]
I'll try to update SQLite.pretty to support this feature and add some tests
over the weekend. Been pretty busy lately though :/

**Comment by ericsink** [comment]
0.8.1 has been pushed to nuget.  The test case provided in the PR does pass.  Closing this issue.
