### ISSUE TITLE
Blazor WASM AOT not working with version 2.1.1

### ISSUE THREAD

**Issue by peerem** [ericsink/SQLitePCL.raw#514]
With version 2.1.1 Blazor WebAssembly AOT compiling failed:

```
Precompiling failed for ...\obj\Release\net6.0\linked\SQLitePCLRaw.provider.e_sqlcipher.dll.
Mono Ahead of Time compiler - compiling assembly ...\obj\Release\net6.0\linked\SQLitePCLRaw.provider.e_sqlcipher.dll
* Assertion at D:\a\_work\1\s\src\mono\mono\metadata\custom-attrs.c:599, condition `out_obj' not met
```

**Comment by ericsink** [comment]
Does this problem happen with e_sqlite3 as well, or only with e_sqlcipher?

Did this problem happen with 2.1.0 ?

Does this problem happen with 2.1.2-pre20220913165057 ?

**Comment by peerem** [comment]
The problem also exists with this version.

**Comment by ericsink** [comment]
@peerem What is "this version"?

**Comment by peerem** [comment]
The 2.1.2-pre... from today.

**Comment by ericsink** [comment]
Did this problem happen with 2.1.0 ?

**Comment by ericsink** [comment]
Closing due to lack of information.  If this problem is still being seen with 2.1.2, please open a new issue and include all relevant details.

**Comment by peerem** [comment]
Sorry i was on vacation.

Yes, AOT works with version 2.1.0.
