### ISSUE TITLE
[v2.1.1] Compile error in .NET6 iOS AOT builds

### ISSUE THREAD

**Issue by tipa** [ericsink/SQLitePCL.raw#516]
Both the version 2.1.1 and the 2.1.2-preview of `SQLitePCLRaw.bundle_green` cause compile errors in a .NET iOS app.
Example project: [test.zip](https://github.com/ericsink/SQLitePCL.raw/files/9569849/test.zip)

Simply navigate to the folder and run `dotnet publish -c Release`

`/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.4.447/targets/Xamarin.Shared.Sdk.targets(1000,3): error : Failed to AOT compile SQLitePCLRaw.provider.sqlite3.dll, the AOT compiler exited with code 134 [/Users/.../test.csproj]
`

Downgrading to 2.1.0 resolves the problem

**Comment by ericsink** [comment]
I'm away from my Mac.  I'm curious.  Can you try using bundle_e_sqlite3 instead of bundle_green?  Does it show the same problem?

**Comment by tipa** [comment]
Changing it to `SQLitePCLRaw.bundle_e_sqlite3` still errors out, but with a slightly different error:

`/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.4.447/targets/Xamarin.Shared.Sdk.targets(1000,3): error : Failed to AOT compile SQLitePCLRaw.provider.internal.dll, the AOT compiler exited with code 134 [/Users/.../test.csproj]
`

**Comment by ericsink** [comment]
OK. Thanks. I'll take a closer look as soon as I get a chance.

**Comment by ericsink** [comment]
Confirming:  I can reproduce this.  It happens for 2.1.1, but not for 2.1.0.  Unfortunately, the error message is exceedingly unhelpful.

@filipnavara The only change between 2.1.0 and 2.1.1 that looks remotely relevant here is your changes for the calling convention of unmanaged function pointers, in #507 -- any idea how that could be causing the AOT failure seen here?  Are you able to do AOT iOS builds with your code change?

**Comment by filipnavara** [comment]
> any idea how that could be causing the AOT failure seen here? Are you able to do AOT iOS builds with your code change?

It could be a Mono bug. We should raise the issue on dotnet/runtime repo with a small self-contained repro. I won't be able to look into it until next week.

**Comment by ericsink** [comment]
I condensed the repro down to not need SQLitePCLRaw.  It's basically a single function with an `UnmanagedCallersOnly` attribute that fails when `CallConvs` is provided.  I posted that repro in a bug report to dotnet/runtime and linked to this issue as shown above.

**Comment by ericsink** [comment]
I believe this is fixed in 2.1.2-pre20220916165053.

**Comment by freever** [comment]
I can confirm this is fixed for me. I have a .NET Maui app for which the iOS builds started breaking once I upgraded SQLitePCLRaw to 2.1.1. Builds are working again with 2.1.2-pre20220916165053.

**Comment by ericsink** [comment]
Fixed in 2.1.2, which is now on nuget
