### ISSUE TITLE
Suggestion: Use double checking on locks

### ISSUE THREAD

**Issue by CheloXL** [ericsink/SQLitePCL.raw#52]
You have several locks before accessing dictionaries. That's a lot of contention. I would replace that in all methods by a double checking (one check outside the lock, another inside).

Like for example:

```C#
internal static info getOrCreateFor(IntPtr db)
{
	info i;
	if (_hooks_by_db.TryGetValue(db, out i))
	{
		return i;
	}

	lock (_hooks_by_db)
	{
		if (_hooks_by_db.TryGetValue(db, out i))
		{
			return i;
		}

		return _hooks_by_db[db] = new info();
	}
}
```

**Comment by bordoley** [comment]
Whats causing contention? Are you using multiple databases concurrently? Or are you trying to access the same database from multiple threads?

**Comment by ericsink** [comment]
What triggered your suggestion to do double checking?  Are you experiencing lock contention problems?  Or are you merely concerned about the possibility of same?

**Comment by CheloXL** [comment]
Yes, I'm using the same database from multiple threads. Doing a profiling shown me that there were contention on this class. I usually do not use locks unless they are really necessary (but I'm on 4.5, so I can use the concurrent collections, and usually use ReadWriteLockSlim for any other thing that requires that the execution path where the write is done doesn´t executes twice).

**Comment by ericsink** [comment]
(1)  Are you using the same database connection (the sqlite3* handle) from multiple threads?  Or do you mean you are using the same database file from multiple threads but each thread gets its own connection?

(2)  Which of the hook functions are you using?  I'm pretty sure the only place we use the lock is when actually setting the hook function, which should be an infrequent operation, unless you are changing the hook a lot or opening-and-closing the connection a lot.  I do also notice that removeFor() asks for a lock whether any hooks ever got used for that connection or not.

The double-check worries me a little.  I just want to fully understand the problem before I implement it.

**Comment by CheloXL** [comment]
Both. It's an application I took over and while I would not do that, it is what it is right now...

Since the app opens/closes the connection several times in a row, the locking is evident there. I'm trying to refactor all that mess. Why are you worried about the double-check? I'm using that on several projects and never had an issue. Of course that if you want to do the same with a field and not a dictionary you should also have to use Volatile.Write() to actually update the value (it's better to use that instead of decorating the field with volatile, as that slows down the reads).

**Comment by ericsink** [comment]
The double-check just doesn't look clean, and I'm trying to think through the issue of whether there might be a race condition.

The dictionary key is an IntPtr that comes from a plain C alloc.  It is likely that the pointer values will get reused, especially when opening/closing connections frequently.  Attempting the dictionary lookup outside the lock opens the possibility of getting the hook info object from a previous connection, doesn't it?

**Comment by bordoley** [comment]
Another option to consider is to lift the implementation of System.Collections.Concurrent dictionary from corefx and use that instead:

https://github.com/dotnet/corefx/blob/master/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs

Its very well tested, as its part of the core .NET framework, and required surprisingly few changes to compile as a PCL. I had to change the error messages, since they used internal string resources and hard code the default concurrency level.

**Comment by CheloXL** [comment]
Mmm.. Didn't think about that. I though IntPtr were unique, but you are correct. If they are reused, there is a possibility of getting an old hook info...

**Comment by ericsink** [comment]
ConcurrentDictionary uses Monitor.Enter/Exit, which [I think] is the same thing the C# lock statement uses, so I wouldn't expect that to be an improvement.  But I haven't actually tried or profiled or benchmarked.

**Comment by bordoley** [comment]
The improvement would be for concurrent access to multiple database connections. It uses lock striping to avoid contention across keys, but there will alway be contention for the same key.

**Comment by ericsink** [comment]
Hmmm. Ok maybe...

**Comment by ericsink** [comment]
Grabbed the ConcurrentDictionary code to try it out.  It actually does go rather smoothly until the net40 build fails due to lack of Volatile.Write().  :-(

**Comment by bordoley** [comment]
fallback to locking dictionary for .net4 :/

**Comment by bordoley** [comment]
OK this would be pretty hacky but the reference source has an implementation of Volatile.Write() I think you can use for .Net4

https://github.com/Microsoft/referencesource/blob/74706335e3b8c806f44fa0683dc1e18d3ed747c2/mscorlib/system/threading/volatile.cs#L263

**Comment by bordoley** [comment]
Another option, is to use the system provided implementation of System.Collections.Concurrent.ConcurrentDictionary on all platforms that provide it natively (.net4, .net45, android, ios) and fallback to the pcl version for those that don't (i think only the windows phone variants).

**Comment by ericsink** [comment]
I've pushed a change.  It uses the system implementation of ConcurrentDictionary on everything except wp80 and wp81_sl, where it uses the current "lock around a regular dictionary" approach.

**Comment by bordoley** [comment]
Rad!

**Comment by bordoley** [comment]
src/cs/util.cs#75

ConcurrentDictionary offers the method GetOrAdd (https://msdn.microsoft.com/en-us/library/ee378677(v=vs.110).aspx). The ConcurrentDictionary implementation should use this method instead since its transactional (it locks the key) and avoid races.

**Comment by ericsink** [comment]
Good point.  Fixing this now...

**Comment by ericsink** [comment]
0.8.1-pre2 on nuget contains this change.

**Comment by CheloXL** [comment]
Much, but much better now... Contention almost is non-existant now. Thanks!

**Comment by bordoley** [comment]
@CheloXL out of curiosity how many concurrent db connections are you using?

**Comment by CheloXL** [comment]
It really depends on the number of processes running on the target machine, but on heavy operations, 16 or more. And again, that's because the design of the app is so bad that it is opening/closing connections for whatever they wanted to do with the DB.

**Comment by CheloXL** [comment]
One example I have at hand (and that was easy to refactor): The original programmer(s) threw some queries (and of course, opening/closing the db while doing so) inside a Parallel.ForEach (don't ask me why).

**Comment by bordoley** [comment]
Cool. I was mostly curious, as I'm considering writing some tests for my
SQLite library that cover the concurrency cases.

**Comment by ericsink** [comment]
0.8.1 has been pushed to nuget.  Closing this issue.
