### ISSUE TITLE
SQLitePCLRaw.bundle_e_sqlcipher version > 2.1.0 ```non-deterministic``` error when inserting into a database table

### ISSUE THREAD

**Issue by iplusMario** [ericsink/SQLitePCL.raw#520]
I get the following ```non-deterministic``` error when inserting into a database table when using ```HasComputedColumnSql("DATETIME()", true)```.

Example:
```
modelBuilder.Entity<Model>()
                    .Property(k => k.ChangeDate)
                    .HasComputedColumnSql("DATETIME()", true);
```

Version:
EFCore: 6
EntityFramewrokCore: 6.0.8 and 6.0.9
EntityFramewrokCore.SqLite.Core: 6.0.8 and 6.0.9
SQLitePCLRaw.bundle_e_sqlcipher version: 2.1.1 and 2.1.2

**Comment by iplusMario** [comment]
> What is the actual error message?
> 
> Did this happen with versions before 2.1.1, or does it look like a regression?
> 
> Is this specific to Entity Framework?
> 
> Does it happen with e_sqlite3, or only with e_sqlcipher?

I only tried with e_sqlchiper.
With version 2.1.0 insert doesn't throw errors.

**Comment by ericsink** [comment]
Can you attach a minimal repro sample project?

**Comment by iplusMario** [comment]
> Can you attach a minimal repro sample project?

[SQLitePCLRaw.zip](https://github.com/ericsink/SQLitePCL.raw/files/9634879/SQLitePCLRaw.zip)

There are three projects within the solution:
- SQLitePCLRaw.Common (library for EFCore setup)
- SQLitePCLRaw.V2.1.0 (Console app using SQLitePCLRaw.bundle_e_sqlcipher version: 2.1.0)
- SQLitePCLRaw.V2.1.2 (Console app using SQLitePCLRaw.bundle_e_sqlcipher version: 2.1.2)

**Comment by iplusMario** [comment]
@ericsink Thanks for the detailed reply. 

> To confirm, if you change your test to say DATETIME('now'), the error occurs with SQLitePCLRaw 2.1.0 as well.

Yes I first tried using ```DateTime('now')``` and got a ```non-deterministic``` error. Then I read somwhere that ```DateTime()``` is a deterministic function and replaced ```DateTime('now')``` with ```DateTime()```.
