### ISSUE TITLE
status of 3.8.11.1 in SQLitePCL.raw

### ISSUE THREAD

**Issue by ps30** [ericsink/SQLitePCL.raw#55]
Great package and we are using it with praeclarum/sqlite-net.  Question for Eric: I know there are a few important issues going on, but will you have time to upgrade the SQLitePCL.raw package to support the SQLite 3.8.11.1 binary and push to Nuget?

And... Does anyone know if the praeclarum/sqlite-net project is still moving?  There have not been any updates since January..  Just curious if anyone has any insight.  Both are great packages and we really are happy with how it all just works so well with .Net 4.5.2 on the desktop under Win8 64bit WPF.

**Comment by ericsink** [comment]
Yeah, I should be able to get that done early next week.

I believe the SQLite-net package is simply mature enough that it doesn't need to change very often.

**Comment by ericsink** [comment]
SQLitePCL.raw 0.8.2 is now in nuget.  The only change since 0.8.1 is that it contains SQLite 3.8.11.1.
