### ISSUE TITLE
Add support for linux-musl-s390x target

### ISSUE THREAD

**Issue by uweigand** [ericsink/SQLitePCL.raw#571]
A while ago we added support for the linux-s390x target (https://github.com/ericsink/SQLitePCL.raw/issues/426).   At that time, we did not yet have support for .NET on Alpine on our architecture, but in the meantime this is available as well.  And it turns out there is also interest in using SQLitePCL.raw on that OS - but this is currently not working, see e.g. https://github.com/dotnet/efcore/issues/32209.

It seems the binaries built against glibc crash when run on Alpine (which uses the musl libc).  I see that SQLitePCL.raw contains binaries built against musl for many Linux platforms.  When adding a similar build on s390x, the crashes go away in local testing.  I'm opening this issue to request adding that support to the upstream build, and will post PRs against this repo as well as `cb` shortly.

**Comment by ericsink** [comment]
This was included in 2.1.7, which has been pushed up to nuget.
