### ISSUE TITLE
Compile SQLite.Interop with security flags

### ISSUE THREAD

**Issue by jeremy-bridges** [ericsink/SQLitePCL.raw#577]
Our PEN testers recently found that the SQLite.Interop.dll was not compiled with ControlFlowGuard enabled. Can we get this changed in the next iteration of the nuget packages? Thanks in advance!

https://learn.microsoft.com/en-us/windows/win32/secbp/control-flow-guard

**Comment by ericsink** [comment]
I'm pretty sure this project does not include a DLL with that name.

**Comment by sjlombardo** [comment]
@jeremy-bridges - you should report this issue on the [SQLite forum](https://sqlite.org/forum/forum). You're talking about [System.Data.SQLite](https://system.data.sqlite.org) which is maintained by the SQLite development team.
