### ISSUE TITLE
SQLite 3.45

### ISSUE THREAD

**Issue by ericsink** [ericsink/SQLitePCL.raw#580]
The 3.45 release of SQLite is imminent.  Approximately a week after its release I plan to upgrade the `e_sqlite3` builds for the current main branch.  The branch with Xamarin classic removed has made good progress but isn't ready yet.

@utelle If you have an updated sqlite3mc I will do that too.

**Comment by utelle** [comment]
> The 3.45 release of SQLite is imminent. Approximately a week after its release I plan to upgrade the `e_sqlite3` builds for the current main branch. The branch with Xamarin classic removed has made good progress but isn't ready yet.
> 
> @utelle If you have an updated sqlite3mc I will do that too.

Since the release of _SQLitePCLraw 2.1.7_ I have released a new _sqlite3mc_ version, _1.8.1_, which is based on _SQLite 3.44.2_ and includes a new additional cipher scheme, _Ascon-128_.

I intend to update _sqlite3mc_ shortly after the release of _SQLite 3.45.0_. At the moment the exact release date of _SQLite 3.45.0_ is not yet known, but usually I manage to do the update within 2 or 3 days after the _SQLite_ release.

**Comment by utelle** [comment]
> I intend to update _sqlite3mc_ shortly after the release of _SQLite 3.45.0_. At the moment the exact release date of _SQLite 3.45.0_ is not yet known, but usually I manage to do the update within 2 or 3 days after the _SQLite_ release.


Today I released [SQLite3 Multiple Ciphers 1.8.2](https://github.com/utelle/SQLite3MultipleCiphers/releases/tag/v1.8.2) based on **SQLite 3.45.0**.

Additionally, I tested to create all binaries for _SQLitePCLraw_ in [my fork of your cb repository](https://github.com/utelle/SQLite3MultipleCiphers-cb/tree/sqlite3mc) - all binaries were created.

Finally, a paragraph needs to be added to the [bundle README file](https://github.com/ericsink/SQLitePCL.raw/blob/master/src/SQLitePCLRaw.bundle_e_sqlite3mc/README.md) - see [**Ascon** item](https://github.com/utelle/SQLite3MultipleCiphers-NuGet/blob/main/README.md#encryption) in list of ciphers.

Let me know, how you would like to do the update of **sqlite3mc** in **SQLitePCLraw**.

**Comment by lable** [comment]
Is the adaptation of sqlite3.45 complete? I want to try the jsonb field

**Comment by ericsink** [comment]
Sigh, not yet.  I've got the native builds done, but the SQLitePCLRaw build itself has started failing due to some sort of android error.  I'll get this fixed as soon as I can.

**Comment by utelle** [comment]
I just discovered that _SQLite **3.45.1**_ will be released in a few days (see [here](https://www.sqlite.org/draft/releaselog/3_45_1.html)).

**Comment by utelle** [comment]
> I just discovered that _SQLite **3.45.1**_ will be released in a few days (see [here](https://www.sqlite.org/draft/releaselog/3_45_1.html)).

_SQLite 3.45.1_ was released yesterday (_January 30, 2024_).

Today I prepared a new [SQLite3 Multiple Ciphers 1.8.3](https://github.com/utelle/SQLite3MultipleCiphers/releases/tag/v1.8.3) release based on **SQLite 3.45.1**.

Again, I tested to create binaries for _SQLitePCLraw_ in [my fork of your cb repository](https://github.com/utelle/SQLite3MultipleCiphers-cb/tree/sqlite3mc) - all binaries were created successfully.

**Comment by ericsink** [comment]
@utelle Thanks!

I've gotta figure out that Android build problem I've been stuck on.  Grrr.

**Comment by utelle** [comment]
> I've gotta figure out that Android build problem I've been stuck on. Grrr.

Not sure whether it can help you with solving the Android build problem, but I tested my binaries also with the [SQLite3MultipleCiphers-NuGet](https://github.com/utelle/SQLite3MultipleCiphers-NuGet) repository I had set up with the help of @bricelam. However, it does not include _Xamarin_ support, so probably no useful hints.

**Comment by ericsink** [comment]
The Android build problem turned out to be:  The GH actions runners dropped support for the older version of the Android SDK I was using.  The fix was to modify my GH workflow file to install that SDK specifically.

**Comment by ericsink** [comment]
Version 2.1.8 has been pushed up to nuget.  The builds for e_sqlite3 and e_sqlite3mc were updated to SQLite 3.45.1.

**Comment by lable** [comment]
Thank's 👍！
