### ISSUE TITLE
SQLCipher update

### ISSUE THREAD

**Issue by rgroenewoudt** [ericsink/SQLitePCL.raw#583]
Today a new version of SQLCipher has released which updates it's SQLite to 3.44.2.
https://github.com/sqlcipher/sqlcipher/releases/tag/v4.5.6

Could we have an update of SQLitePCL.Raw's e_sqlcipher? :)

**Comment by ericsink** [comment]
Maybe at some point.  Not today.

But Zetetic sells SQLCipher builds which integrate with SQLitePCLRaw.  I'm sure they would be happy to help you.

More info:

https://github.com/ericsink/SQLitePCL.raw/wiki/Expectation-setting-for-e_sqlcipher
