### ISSUE TITLE
Profile 78?  

### ISSUE THREAD

**Issue by habermeier** [ericsink/SQLitePCL.raw#6]
I'm trying to add the SQLitePCL.raw to my own PCL that targets Profile 78 -- but I get the below error when trying to add it (with Xamarin Studio 4.3):

Adding SQLitePCL.raw_needy...
Adding 'SQLitePCL.raw_needy 0.5.0' to client.Core.
Could not install package 'SQLitePCL.raw_needy 0.5.0'. You are trying to install this package into a project that targets 'portable-net45+win+wp80+MonoAndroid10+MonoTouch10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

It was my understanding from the readme that Profile 78 should be supported.  Am I missing something?  I'm using mvvmcross, which appears to want Profile 78.  I'm fairly new to Xamarin, and C# for that matter, so it could well be that I'm doing something silly on my end.

![image](https://cloud.githubusercontent.com/assets/1214689/4213147/a8b987de-38af-11e4-9b86-450cfe7ee200.png)

**Comment by habermeier** [comment]
@ericsink Hey there -- it's been a while.  I had the original implementation working for a while now (thanks), but now I'm looking to update to the latest code, and would like to avoid going through the adjustments by hand again if I can avoid it.

So far I've put SQLitePCL.raw_basic and SQLitePCL.ugly into my own core PCL library, and stuck SQLitePCL.raw_needy into my Xmarin.iOS project.  It seemed to compile without me adding my own sqlite3.a file (which was unexpected).  When I check the library version it reports 3.7.13 -- which is the version that the iOS simulator comes with.  My build of libsqlite3.a is 3.8.6 with FTS enabled.

When I added my own libsqlite3.a to the client project I added an include.cs file that contains this:
```
using MonoTouch.ObjCRuntime;

[assembly: LinkWith(
	"libsqlite3.a", 
	LinkTarget = LinkTarget.Simulator | LinkTarget.ArmV7 | LinkTarget.ArmV7s | LinkTarget.Arm64, 
	ForceLoad=true
)
]
```

And added the libsqlite3.a file into the ios client project and set its build action as an embedded resource.  It still compiles and runs, but it's not using my own version of libsqlite3.a -- it's ignoring it.  Using SQLitePCL.raw_basic on the client / ios project side doesn't change anything either.

From the looks of it, you turned on FTS option in the library someplace in your wrapper (I see it turned on for iOS and Android), but I'm unclear in which nuget package that comes activated in.

```
android/sqlcipher/jni/Android.mk:13:LOCAL_CFLAGS := -O -DSQLITE_HAS_CODEC -DNDEBUG -DSQLITE_DEFAULT_FOREIGN_KEYS=1 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_COLUMN_METADATA
android/sqlite3/jni/Android.mk:6:LOCAL_CFLAGS := -O -DNDEBUG -DSQLITE_DEFAULT_FOREIGN_KEYS=1 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_COLUMN_METADATA
apple/build-sqlite.sh:51:Z_CFLAGS="-O -DNDEBUG -DSQLITE_DEFAULT_FOREIGN_KEYS=1 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_COLUMN_METADATA"
```

... which you must have done for a reason.  I'm just not sure how to tap your specific libraries.  Didn't see any updates in the documentation or description text on nuget.  Am I barking up the wrong tree?  Do I need to rebuild my own bait-and-switch thing again (I'm asking because I just burned through a good number of hours without success).

**Comment by ericsink** [comment]
(For now I'll just duck the questions about how to get your own sqlite build working again and explain how to use the FTS-enabled sqlite build which is now included in SQLitePCLraw.)

The latest code (and version 0.7.2-pre1 of the nuget package) supports the csproj property idea described above.

Basically, in your csproj file, you need to add the following property:

<UseSQLiteFrom>packaged_sqlite3</UseSQLiteFrom>

Put this in the PropertyGroup at the top of the file, the same one that contains things like AssemblyName and ProjectGuid.

This only works for Android and iOS Unified, not for iOS classic, which you probably shouldn't be using anymore anyway.

I hope this makes sense.

The _needy package is deprecated and will eventually be removed.  I'm no longer building it.
