### ISSUE TITLE
Ask for the "PrivacyInfo.xcprivacy" required by Apple

### ISSUE THREAD

**Issue by baihao** [ericsink/SQLitePCL.raw#600]
Hi team,

 Is there a plan to include the PrivacyInfo.xcprivacy manifest as required by Apple? ref: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

Thanks,
Hao

**Comment by ericsink** [comment]
It would seem wrong to me for a library to (try to) provide that.  That file makes certain assertions about the app, so the develop of the app needs to take responsibility for it.
