### ISSUE TITLE
Android: Support 16 KB devices

### ISSUE THREAD

**Issue by utelle** [ericsink/SQLitePCL.raw#603]
A user of _SQLite3 Multiple Ciphers_ (@tranb3r) opened an [issue](https://github.com/utelle/SQLite3MultipleCiphers/issues/172) which is - most likely - related to _SQLitePCL.raw_:

> When building an android app with .net9-pre7 (for android 15), I get this warning: `C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\35.0.0-preview.7.41\tools\Xamarin.Android.Common.targets(2099,3): warning XA0141: NuGet package '<unknown>' version '<unknown>' contains a shared library **'libe_sqlite3mc.so'** which is not correctly aligned. See https://developer.android.com/guide/practices/page-sizes for more details`
> 
> Could you please rebuild the lib for it work on 16kB devices, as explained in the linked page?

Maybe the compile and build process in [ericsink/cb](https://github.com/ericsink/cb) needs to be adjusted to support this use case.

**Comment by tranb3r** [comment]
Indeed I'm using SQLitePCLRaw.bundle_e_sqlite3mc

**Comment by ericsink** [comment]
Hopefully this was fixed in 2.1.10, which was released today.
