### ISSUE TITLE
Which version of sqlite is bundled with PCL?

### ISSUE THREAD

**Issue by danielo-unity3d** [ericsink/SQLitePCL.raw#608]
Hi. 
I'm just curious how we can figure out which version of Sqlite is used for any given version of the `Microsoft.Data.Sqlite` (between say 7.0.1 and 8.0.8)?

These live in [dotnet/efcore](https://github.com/dotnet/efcore), and depend in turn on this repository.
Lets suppose we want to know the versions of SqLite, between versions 2.1.4 and 2.1.6, and perhaps beyond.

The actual SqLite sources are in a yet another repository ([ericsink/cb](https://github.com/ericsink/cb)), but which branch or tag was selected in that repo for each of the releases of the PCL?

The latest version of SqlLite (in the `cb` repository) appears to be 3.46.0, but I guess that only applies to the latest version of the PCL? (now 2.1.8?)

Also, the `cb` repo appears to contain different versions of SqlLite simultaneously, depending on which subdirectory (I'm not sure which one we end up using):
- `sqlite` and `sqlite3mc`: 3.46.0
- `sqlcipher`: 3.39.2
- `sqlcipher3`: 3.20.1

Any background that explains this is very welcome.
Thanks in advance

**Comment by ericsink** [comment]
I try to specify the version of the underlying native code in the releases page:

https://github.com/ericsink/SQLitePCL.raw/releases

Each build of SQLitePCLRaw uses whatever is most recent in the `cb` repo, and unfortunately I don't use tags for that.

As you noticed, the `cb` repo builds 3 forms, all of which end up with an `e_` prefix.

e_sqlite3 is plain SQLite, built from the amalgamation downloaded from sqlite.org

e_sqlite3mc is SQLite3 Multiple Ciphers, built from an amalgamation I obtain from its maintainer.

e_sqlcipher is an unofficial and unsupported build of the open source version of SQLCipher, from Zetetic.  For that one I have to build the amalgamation myself, and link in a crypto library.  I deliberately update this less often than the other two, and plan to remove it entirely at some point.

The choice of which of these kinds of builds you get is determined by which nuget package(s) you include.

**Comment by danielo-unity3d** [comment]
That works. Thank you
