### ISSUE TITLE
Xamarin.iOS: Bait assembly incorrectly loaded

### ISSUE THREAD

**Issue by corliss** [ericsink/SQLitePCL.raw#61]
I've opened the same issue in the [sqlite-net project](https://github.com/praeclarum/sqlite-net/issues/402), but it is more likely a SQLitePCL.raw issue.

> My iOS project worked fine with sqlite-net / SQLitePCL.raw previously.

> However, with recent builds, the bait PCL assembly is loading instead of the platform-specific one.
I'm not sure when the regression first occurred. I'm using SQLitePCL.raw v0.8.4 with the latest sqlite-net code.

> The exception occurs with both Visual Studio 2015 and Xamarin Studio.

> My project is completely broken right now, so appreciate any pointers. How exactly does the loading process work?

**Comment by corliss** [comment]
I found that the `lib\Xamarin.iOS10` directory of the older `SQLitePCL.raw_basic.0.7.1` package contains this file:

    50,176 SQLitePCL.raw.dll

But the same directory for the `SQLitePCL.raw.0.8.4` package is empty.

I surmise that because of this, the bait and switch fails and nuget ends up loading the API assembly.

I'm surprised that nobody else has run into this yet.

**Comment by ericsink** [comment]
On the surface, this looks like a duplicate of issue #48.  

Anyway, lib\Xamarin.iOS10 is intentionally empty.  As of version 0.8.0, the reference is inserted using a .targets file.  So whatever is going wrong in your situation, the content of that lib directory compared with 0.7.1 is probably not the right diagnosis.

That said, I don't think I have enough info to figure this out.  More details?

**Comment by corliss** [comment]
What additional details might be useful here? 

I can see that the dll in the .app directory is the 33k bait assembly. This assembly also appears in the debugger Application Output Window during startup, as a loaded assembly. 

So I guess the thing to figure is how the bait assembly ended up in the app folder. Do you happen to know exactly how NuGet and the C# build process work to determine this? 

Also, I'm using the latest Xamarin, with Mono 4.2.1 and Xamarin.iOS 9.2.1.51.
I notice that your configuration in #48 uses an older version, Mono 4.0 and Xamarin.iOS 8.10. Have you tried upgrading?

**Comment by corliss** [comment]
From the build log, the dll resolves to 

    SQLitePCL.raw.0.8.2/lib/portable-net45+netcore45+wpa81+wp8+MonoAndroid10+MonoTouch10+Xamarin.iOS10/SQLitePCL.raw.dll

which is a bait assembly.

**Comment by ericsink** [comment]
I do need to upgrade my Xamarin install to make sure nothing broke with Xamarin 4.  I'll be kind of surprised if that turns out to be the problem, but it might be.

What is the structure of the projects in your solution, and which of those projects have the sqlite-net and/or the SQLitePCL.raw packages added?

Your symptom reminds of cases where people have a library, and they add the SQLitePCL.raw package to the lib project, but not to their actual iOS app project.  So the bait ends up being the only thing in play.

**Comment by corliss** [comment]
> Your symptom reminds of cases where people have a library, and they add the SQLitePCL.raw package to the lib project, but not to their actual iOS app project. So the bait ends up being the only thing in play.

That's what it turned out to be! I had re-created the main app project for Xamarin 4, and hadn't added SQLitePCL.raw to it.

That solves the issue, but is a bit worrisome. Is there no way around this? NuGet packages, once added, should ideally not require to be re-added elsewhere to work correctly. There are no build errors or warnings either. Can we do better?
