### ISSUE TITLE
Update to SQLCipher 4.6.1 release that uses SQLite 3.46.1

### ISSUE THREAD

**Issue by ps30** [ericsink/SQLitePCL.raw#610]
Hi @ericsink - Please update e_sqlcipher to latest community release. 

The current 2.1.10 release in SQlitePCL.raw_provider.e_sqlcipher is using SQLite 3.39.2

Zetetic has released the community version on August 20 that has support for SQLite 3.46.1

[](https://www.zetetic.net/blog/2024/08/20/sqlcipher-4.6.1-release/)

Thanks for a great library!

**Comment by ericsink** [comment]
https://github.com/ericsink/SQLitePCL.raw/wiki/Expectation-setting-for-e_sqlcipher
