### ISSUE TITLE
.NET 3.5 support

### ISSUE THREAD

**Issue by borrrden** [ericsink/SQLitePCL.raw#62]
This is a feature request for .NET 3.5 support so that Couchbase Lite can use this library without compiling it ourselves.  There is very minimal work that needs to be done for source changes (they are all included in the first commit of my SQLCipher PR).  The majority of the work comes from generating a .NET 3.5 target for raw and ugly.  Please let me know if this is a possibility.

**Comment by ericsink** [comment]
Indeed.

Unless I find a good reason not to, I would like to do this.

BTW, so sorry I have been dragging my feet on merging your sqlcipher PR.  I am gearing up for a round of work on SQLitePCL.raw here, and I hope to get my work queue largely cleared out.  :-)

**Comment by ericsink** [comment]
Version 0.8.5-pre3 is in nuget and contains support for net35.  Did I get it right?  :-)

**Comment by ericsink** [comment]
0.8.5, with net35 support, has been pushed up to nuget.  closing this issue.  feel free to reopen or log a new one if something isn't working right.
