### ISSUE TITLE
Cannot have AnyCPU Win8/UWP class libs 

### ISSUE THREAD

**Issue by onovotny** [ericsink/SQLitePCL.raw#65]
I'm trying to use SQLitePCL.raw in a Win8.1 class library but because of the generated targets, I cannot have my class library as AnyCPU:

```
<?xml version="1.0" encoding="utf-8"?>
<!--Automatically generated-->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <SDKReference Include="Microsoft.VCLibs, Version=12.0" />
  </ItemGroup>
  <Target Name="InjectReference_9c3053de-7f64-49f0-b4f3-7d7f750b02d0" BeforeTargets="ResolveAssemblyReferences" Condition=" '$(UseSQLiteFrom.ToLower())' != 'elsewhere' ">
    <ItemGroup Condition=" '$(Platform.ToLower())' == 'arm' ">
      <Content Include="$(MSBuildThisFileDirectory)..\..\build\native\sqlite3_dynamic\v120\arm\sqlite3.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>
    <ItemGroup Condition=" '$(Platform.ToLower())' == 'x64' ">
      <Content Include="$(MSBuildThisFileDirectory)..\..\build\native\sqlite3_dynamic\v120\x64\sqlite3.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>
    <ItemGroup Condition=" '$(Platform.ToLower())' == 'x86' ">
      <Content Include="$(MSBuildThisFileDirectory)..\..\build\native\sqlite3_dynamic\v120\x86\sqlite3.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>
  </Target>
</Project>
```
The issue is that it adds the ` <SDKReference Include="Microsoft.VCLibs, Version=12.0" />` and that ref requires me to choose a platform. What would work is a variable that lets me disable that SDKReference include in that case. The SDKReference will get added to the app when the package is added there, so in the end it works out.

**Comment by ericsink** [comment]
I wonder if I could add Condition=" '$(Platform.ToLower())' stuff to the ItemGroup around that SDKReference.

I agree that I either need to add a variable to disable this or just remove it.  It was added quite recently as an attempt to minimize problems for people who forget to add the C++ runtime to their build.

**Comment by ericsink** [comment]
I've confirmed and reproduced the problem.

Putting Platform Condition attributes on that ItemGroup does eliminate the error.  Unless you can think of a reason that is not a good resolution, I will probably take that approach for a fix.

**Comment by onovotny** [comment]
sounds good to me

**Comment by ericsink** [comment]
0.8.6 pushed to nuget
