### ISSUE TITLE
SetPassword

### ISSUE THREAD

**Issue by nanddonet** [ericsink/SQLitePCL.raw#68]
I would like to encrypt a DB using this library accessing the ChangePassword() as here http://web.archive.org/web/20071016123701/http://sqlite.phxsoftware.com/forums/t/130.aspx in a Universal App Platform. Does this library support this scenario?

Regards and thanks.

**Comment by ericsink** [comment]
Short answer: No.

Longer answer: SQLitePCL.raw is a much lower-level API than that. If you were to provide a SQLite build with encryption and hook it up to SQLitePCL.raw and provide an implementation of the ADO.NET API built on top of SQLitePCL.raw, then, after all that extra effort, the answer would change to "yes".
