### ISSUE TITLE
Unable to load DLL 'sqlite3' in .NET 4.5 project

### ISSUE THREAD

**Issue by robinei** [ericsink/SQLitePCL.raw#69]
`x86/sqlite3.dll` and `x64/sqlite3.dll` are generated in my `bin/Debug` folder.

If I copy `bin/Debug/x64/sqlite3.dll` to `bin/Debug/sqlite3.dll` it works.

This is using version 0.8.6.

**Comment by ericsink** [comment]
Is your build configuration "Any CPU" ?

**Comment by robinei** [comment]
It was. I use `x64` as active solution target, and tried to switch all projects built for that target to `x64`, but it still happens.
