### ISSUE TITLE
MethodAccessException for Concurrent.ConcurrentDictionary.ctor

### ISSUE THREAD

**Issue by robinei** [ericsink/SQLitePCL.raw#70]
I get the following exception when attempting to run 0.8.6 on a Windows Phone 8.1 (winrt) project.

`{"Attempt by method 'SQLitePCL.sqlite3..ctor(IntPtr)' to access method 'System.Collections.Concurrent.ConcurrentDictionary'2<System.IntPtr,System.__Canon>..ctor()' failed."}`

**Comment by ericsink** [comment]
It's possible that's a bug.  I'll look into it.

**Comment by ericsink** [comment]
Stale issue.
