### ISSUE TITLE
How do I use my own copy of sqlite3.dll

### ISSUE THREAD

**Issue by sisterray** [ericsink/SQLitePCL.raw#71]
I have purchased the Sqlite Encryption Extensions which allows me to build a version of the sqlite3.dll which encrypts the contents of the database.

I wan to use this sqlite.dll to replace the version of sqlite used by iOS and Android.

How do I go about doing this?

* Update - Looking through the code, I see static libraries esqlite.a for iOS. Do I just have to build the sqlite3 library as a static library, and overwrite this file,  and the application will use this version of sqlite rather than the one installed on iOS? I assume it is a similar process for Android?

**Comment by ericsink** [comment]
What's your timeframe on this?

I've been nearing completion on a new release (version 0.9.0).  

The answer to your question now is very different from the answer to your question after 0.9.0 is released.

**Comment by sisterray** [comment]
Hi Erik, my timescales would be within the next month, however I am using MvvmCross, and I hope to be moving to v4 soon. Looking at the new SQLite plugin for v4, it does not seem to use SQlitePCL.Raw any more. So I think I don't have this need anymore. Am I correct in this assumption?

Although it looks like the library now used in the plugin, SQLite.NET-PCL, only uses DllImport to use the SQLite library deployed with iOS and Android.

**Comment by ericsink** [comment]
Hmmm.  I didn't realize the MvvmCross plugin was ever using SQLitePCL.raw.  Somewhere I got the impression they were doing something different.

Anyway, looking now at their v4 plugin, yeah it looks like they're using the oystein.krog fork of praeclarum's sqlite-net.

So yeah, you're heading in a different direction.

**Comment by sisterray** [comment]
Yeah, I think they used a library which used SQLitePCL.Raw. 
Thanks for answering my question Eric. I read you article on sqlite corruption which explains the best way to link to a custom version of sqlite, it helped me a lot.

**Comment by pragnagopa** [comment]
I am looking for the right approach to use sqlite with [SEE](https://www.sqlite.org/see/doc/trunk/www/index.wiki) in xamarin.iOS. I have a static library built from the SEE sources. How do I use this to the application instead of the system library?

**Comment by ericsink** [comment]
I need to make this case easier.  But for now, here's how to do it:

1.  Compile (csc or mcs) gen_build.cs

2.  Run gen_build.exe to create the bld directory

3.  cd bld (the directory created by gen_build.exe)

4.  cd plugin.sqlite3.ios_unified

5.  Modify the csproj file in that directory.  Look at the ManifestResourceWithNoCulture line.

**Comment by ericsink** [comment]
The 1.0 release contains better support for using a custom SQLite build.  Still a little tricky, but better.  See the "custom_sqlite3" provider.  For iOS, see the SQLitePCLRaw.provider.internal.

**Comment by plamenkoyovchev** [comment]
Guys, how can I use newer dll version of SQLite from my Xamarin.iOS project ?
