### ISSUE TITLE
SQLitePCL.raw not being included in TFSBuild

### ISSUE THREAD

**Issue by StacyHenwood** [ericsink/SQLitePCL.raw#72]
We have a strange issue that I hope you can help me with.

We have a Xamarin project that uses SQLitePCL (and by virtue, SQLitePCL.raw). One of the builds is for WinPhone (8.0) and we are experiencing build issues with this version. 

When we build the ARM/Release version on a developer machine, it all works fine. SQLite works, and the app works as intended.

When we build the ARM/Release version using TFSBuild, the SQLitePCL.raw.dll is not included, and the app crashes on startup as the DLL is not included in the XAP file. It is literally the same code, taken from the same branch in TFS.

We cannot work out what is different between the developer machines and the build server that makes it behave differently. All the same installs are present (SDK's etc), and the build is successful, but when we looks in the logs, SQLitePCL.raw.dll is not being packaged up. 

I know from many google searches that there may be some shenanigans with Microsoft.Bcl.Build but its not apparent if this is the problem or its something else. 

We are using SQLitePCL nuget package v1.1.1 (https://github.com/praeclarum/sqlite-net) and this is targeting SQLitePCL.raw 0.8.6 (https://github.com/ericsink/SQLitePCL.raw)

If you could give me any pointers as to what might be causing this issue, it would be appreciated.

I can provide snippets from build logs if this would help.

**Comment by ericsink** [comment]
I'm afraid I don't know anything about TFS Build. 😕

The SQLitePCL.raw build process often relies on an msbuild targets file. First guess would be to try to verify if its getting run at all. You should find it in the nuget package, in the build directory, in wp80 (from memory, hopefully correct). 

Suggestion: Make a backup of the file and modify it to do something you can see in your build log.

**Comment by StacyHenwood** [comment]
Thanks for the pointers. 

Interestingly, the dll is output for the PCL project (same solution), as we have Copy Local set to true. We are unable to do this for the Winphone80 version as the reference does not show in the UI. The logs show that for the PCL the files (SQLitePCL.raw and sqlite3.dll) are copied in the _CopyFilesMarkedCopyLocal: section.

I'm continuing to hunt...

**Comment by StacyHenwood** [comment]
Ok, so, I solved it.

I had 2 builds configured for this release : ARM\Debug and ARM\Release.

I discovered, purely by accident, that it was always the 1st build that failed.

So, now I build ARM/Debug, ARM/Debug, ARM/Release and both releases are compiled correctly.

Don't ask me why, because I don't know. I just hope that this helps someone else...
