### ISSUE TITLE
.Net 4.6.1 support & verison

### ISSUE THREAD

**Issue by ps30** [ericsink/SQLitePCL.raw#75]
Eric,
I may have overlooked this, but does SQLitePCL.raw currently support .Net 4.6.1 64 bit on Windows 10 desktop?  I thought the current version (not -pre) only supported up to .Net 4.5.2 on the desktop.  We would like to upgrade our WPF application to 4.6.1 and I wanted to check with you first.

And... will the v0.9.0 release ship with the latest SQLite 3.12.2 build?  Several bugs fixed in the latest.

Thanks for the great work!

**Comment by ericsink** [comment]
I'm pretty sure 0.8.6 supports net461 and Windows 10 desktop.  But not 100% sure.  :-)

0.9.0 should probably be released late this week or next week.  And its accompanying sqlite builds will be 3.12.2 or *maybe* 3.13, which is nearing release.

**Comment by ps30** [comment]
OK I will close this issue after I have tested under 4.6.1 desktop or another user provides feedback that they have it working.  Thx.
