### ISSUE TITLE
RTree not correctly enabled for Android

### ISSUE THREAD

**Issue by pcclark4** [ericsink/SQLitePCL.raw#76]
I noticed in one of your latest commits you enabled RTree by un-commenting the line in gen_build.cs. Unfortunately this won't do anything for Android because the Android.mk file needs to be updated and ndk-build needs to be called again to rebuild the .so's which are referenced in the project. 

-DSQLITE_ENABLE_RTREE should be added to the LOCAL_CFLAGS variable in Android.mk and the .so's should be recompiled by calling ndk-build while in the jni directory. This will correctly enable RTree for the Android module.

**Comment by ericsink** [comment]
Darn.  I knew I was forgetting something. 

Nice catch. Will fix.

**Comment by pcclark4** [comment]
Awesome, thanks! And yeah, it is a bit of a pain to have to recompile those things every time you change a compile flag or upgrade SQLite versions.

**Comment by ericsink** [comment]
Fixed
