### ISSUE TITLE
DllNotFound Access violation on upgrade

### ISSUE THREAD

**Issue by ps30** [ericsink/SQLitePCL.raw#77]
Our Windows desktop C# 4.5.2 WPF x64 app works great with SQLitePCL.raw 0.8.6 so I thought I would test the latest with a simple in place upgrade to 0.9.0-pre8.  After running Nuget to update to the latest pre-release we now get System.DllNotFoundException and the Access violation. Attaching screen shots.  I am thinking maybe the location of files have moved in the 0.9.0 release and there will be some new docs telling us where to find the dll but I wanted to share this "breaking" update issue, as you cannot do an in place update now and keep things working.  We are compiling with .Net 4.5.2 and CPU is set to x64.

![capture1](https://cloud.githubusercontent.com/assets/12287002/15265810/1c2da422-1944-11e6-85bc-537bc33fd191.PNG)
![capture2](https://cloud.githubusercontent.com/assets/12287002/15265811/1c3231a4-1944-11e6-98ac-a853a050ea9d.PNG)

**Comment by ericsink** [comment]
The major thing left for 0.9.0 is writing an explanation of the case I think you are seeing. 

You need to add SQLite itself. In 0.8.6 it was included in the main nupkg for some platforms (like Windows x64). In 0.9.0, the main nupkg contains no native code. 

Some people use the SQLite vsix from the visual studio gallery.

Or you can add two more nuget packages that are provided as part of SQLitePCL.raw. 

SQLitePCL.plugin.sqlite3.net45

And

SQLitePCL.native.sqlite3.v110_xp

And to tell it to use the plugin, you need to call SQLitePlugin.Init() somewhere. 

I typed this from memory on my phone, so I hope it's right. Like I said, I'll be writing this up properly as part of the release.

**Comment by ps30** [comment]
That is what I thinking. I just needed to wait for the docs :)  I thought it was good to post the issue so that those that see an update and just do it will know that there is a breaking change in the new version. I will close this issue.

One last thing you mention adding in SQLitePCL.plugin.sqlite3.net45 - on another post I have been asking about net461 support - will there be a SQLitePCL.plugin.sqlite3.net46 needed?

**Comment by ericsink** [comment]
I'm pretty sure all the net45 builds are fully compatible with net461.
