### ISSUE TITLE
SQLitePCL.raw and msvcr110.dll

### ISSUE THREAD

**Issue by alexiej** [ericsink/SQLitePCL.raw#78]
Hi,

I want to avoid install vc++ redistributable on every client machine. But when I try to copy compiled program to another computer I've got error. 

The program can't start because MSVCR110.dll is missing from your computer. Try reinstalling the program to fix thix problem.
Exception thrown: 'System.DllNotFoundException' in SQLitePCL.raw.dll

I cannot copy MSVCR110.dll because some computers are Vista and MSVCR110.dll from Windows 7 doesn't work.
Is it possible to exclude this requirments from your library ?

Best regards,
alexiej

Version Used: Latest Stable: 1,1,
,NET Framework used: 4.5.1
Visual Studio 2015

**Comment by ericsink** [comment]
Version 0.9.0 (to be released soon) addresses this problem by allowing/requiring you to specify exactly which native code implementation of SQLite you want to use and providing SQLitePCL.native.sqlite3.v110_xp, which is the one you want.  The README (front page of this github repo) is currently being updated with more info along these lines.

**Comment by ericsink** [comment]
Closing this issue because 0.9.x has been released.
