### ISSUE TITLE
SQLitePCL.native.sqlite3.v110_xp.0.9.0 seems to look for esqlite3 in the wrong package directory

### ISSUE THREAD

**Issue by PureWeen** [ericsink/SQLitePCL.raw#79]
Just installed the 0.9.0 stuff and then installed the native/plugin tools for a .net 4.5.2 unit test project and started getting this error

__Severity	Code	Description	Project	File	Line	Source	Suppression State
Error		Could not copy the file "\packages\build\native\sqlite3\v110_xp\x64\esqlite3.dll" because it was not found.__	

I checked the targets file and it's

`<Content Include="$(MSBuildThisFileDirectory)..\..\build\native\sqlite3\v110_xp\x86\esqlite3.dll">`

If I change it to
`<Content Include="$(MSBuildThisFileDirectory)..\build\native\sqlite3\v110_xp\x86\esqlite3.dll">`
or
`<Content Include="$(MSBuildThisFileDirectory)native\sqlite3\v110_xp\x86\esqlite3.dll">`

Then it all works super

I'm running this from an MSunit test which maybe changes the dynamics of things

**Comment by ericsink** [comment]
That's a legit bug that somebody else also found last night.  I've pushed the fix to github, but not yet to nuget.  A 0.9.1 with that fix is in the next day or so.

**Comment by ericsink** [comment]
0.9.1 is on nuget.
