### ISSUE TITLE
Return early from TryLoadFromArchDirectory()

### ISSUE THREAD

**Issue by borrrden** [ericsink/SQLitePCL.raw#81]
It occurs to me that if I am trying to distribute a multiplatform app (for example, OS X and Windows) then I will need to include the sqlite3.dll files.  However, both platforms will attempt to load the native binaries if they are there.  Could this be modified to return early if the runtime platform ID is not Windows?

The line in question is -> `var ptr = LoadLibraryEx(dllPath, IntPtr.Zero, LOAD_WITH_ALTERED_SEARCH_PATH);` which will be reached if the native DLLs are present.  This will fail on non-Windows platform with `DllNotFoundException`

Right now this is only affecting our testing framework but I can see it possibly affecting other things in the future.

**EDIT** Actually this is the sqlcipher version not sqlite3 (because I don't need to load a custom provider for sqlite3 on OS X and I don't believe the default provider tries to autoload anything, but I need to register both of them for sqlcipher)

**Comment by ericsink** [comment]
Confused.  I think that code is only compiled in for the Windows build, so it shouldn't happen at all on OSX.  kernel32 and LoadLibraryEx don't even exist on non-Windows platforms.

**Comment by borrrden** [comment]
It is a part of the .NET 4.5 plugin, which is not specific to a platform.  kernel32 not existing is exactly the problem.  .NET does not check until a P/Invoke function is attempted to be executed.  That's where you get the DllNotFoundException.  

Remember .NET 4.5 != Windows :)

**Comment by ericsink** [comment]
"Remember .NET 4.5 != Windows"

I think I'll pretend like this was the first time you had to remind me of that.  :-)

(NuGet v3 is almost here.  Really.)

OK fine.  So the problem is that this highly-Windows-specific fragment of code wants to be skipped when not on Windows?  That seems reasonable.

**Comment by ericsink** [comment]
0.9.3 is on nuget and should fix this
