### ISSUE TITLE
Build iOS native code for compat with older iOS versions

### ISSUE THREAD

**Issue by ericsink** [ericsink/SQLitePCL.raw#82]
See bordoley/SQLitePCL.pretty#35 problem posted by @alexpetin

**Comment by nathanielcook** [comment]
Hi Eric. Is this one fixed in 0.9.4? We're targeting iOS 8.0 and are getting the same linker warning as mentioned in the other thread. For reference I'll copy the warning here:

MTOUCH: Warning MT5203: Native linking warning: warning: object file (/path/to/obj/iPhoneSimulator/Debug/mtouch-cache/esqlite3.a(sqlite3.c.o)) was built for newer iOS version (9.2) than being linked (8.0) (MT5203)

**Comment by ericsink** [comment]
I do plan for this to be fixed in 0.9.4, but it is not yet.  I've gotta look up the syntax, because I've forgotten how to tell xcrun that I want to build for compat with older iOS.  The file in the repo is /apple/build-sqlite.sh.  If by chance you know how to make the change, let me know.  :-)

**Comment by nathanielcook** [comment]
hmm, I'm not an expert on this by any means, but it looks like it could be as easy as `-mios-version-min=8.0`.

**Comment by ericsink** [comment]
Yeah, I tried that.  Didn't work.  I'll try it again and see if I screwed it up somehow.

**Comment by nathanielcook** [comment]
Looks like there's another one out there called `-miphoneos-version-min`. Not sure if that would make a difference or not.

**Comment by nathanielcook** [comment]
I'm wondering also if `-isysroot` (path to the iOS SDK that you need to use?) needs to be specified explicitly. I've seen a few posts online about that, but nothing definitive.

**Comment by nathanielcook** [comment]
Nevermind on that last tip. `xcodebuild -showsdks` shows that only the latest SDKs are installed. So I guess one has to build using the latest SDK, but targeting an older iOS verison. That makes sense.

**Comment by nathanielcook** [comment]
Ok, I'll stop bombarding this thread, but I just found out that one can actually extract older iOS SDKs from the old XCode version installs. Didn't know that before. The process to do that is described [here](http://stackoverflow.com/a/13525384/89590). (If you have XCode 7.3 you may also need to edit the `MinimumSDKVersion` property of `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Info.plist` as described [here](https://forums.developer.apple.com/thread/43381).) So if you did want to try specifying `-isysroot` then you might need to do that to have the older SDKs available.

**Comment by ericsink** [comment]
In my experience, building something with an old SDK simply trades one problem for another.  IIRC, Apple sometimes rejects apps built with an SDK that is too old.

**Comment by ericsink** [comment]
The e_sqlite3 binaries for iOS in the 1.0 release are built for compatibility back to iOS 6.
