### ISSUE TITLE
No Xamarin.WatchOS support

### ISSUE THREAD

**Issue by dalexsoto** [ericsink/SQLitePCL.raw#98]
It seems there is no support for Xamarin.WatchOS, I have added the bits in this PR https://github.com/ericsink/SQLitePCL.raw/pull/96 let me know if you need any changes 😄

**Comment by ericsink** [comment]
So I do my builds on Windows with Visual Studio.  This works fine for iOS, but the WatchOS build fails due to a lack of the Xamarin.WatchOS.CSharp.targets file.

Any idea if this SHOULD work?

**Comment by dalexsoto** [comment]
mmm... well that is surprising let me find out, will get back to you asap

**Comment by dalexsoto** [comment]
@ericsink This will require the Xamarin version that is currently in beta channel, the one that has support for the new iOS 10 bits which should hit stable sometime this week according to Xamarin's release blog https://releases.xamarin.com/beta-preview-4-cycle-8/

**Comment by ericsink** [comment]
Ah, very good.  Thanks.

**Comment by dalexsoto** [comment]
@ericsink It seems we will need to wait a little longer https://bugzilla.xamarin.com/show_bug.cgi?id=44199 

Currently you can't build watchOS library projects in VS just in Xamarin Studio so until the above 🐛 is fixed we'll need to have the watchOS support out 😞 but thanks for having a look at it 😄 will let you know ASAP I hear more about it

**Comment by ghuntley** [comment]
@ericsink nugget of knowledge which might be useful to you - With Cycle 8 (in STABLE) it is now possible to compile Xamarin.Mac MSIL assemblies in Visual Studio. Similar behaviour to Xamarin.iOS compilation when your attached Mac is detached/turned off.

**Comment by renzska** [comment]
@ericsink Any chance you would have time to look at this again to see if it's now possible? I'm looking at using Akavache in my Xamarin.WatchOS App.

https://github.com/akavache/Akavache/issues/391

Thanks,

John

**Comment by ericsink** [comment]
(public reminder to self to review this again)

**Comment by motoko89** [comment]
@ericsink Merry Christmas, is there any update or workaround for this?

**Comment by ericsink** [comment]
I've been digging into this problem a bit more, but it looks like I've got some more learning curve to climb before I can make real progress.  Unfortunately, I have no experience developing for watchOS.  But I still do hope to get this done.

**Comment by motoko89** [comment]
@ericsink I have no experience with C but I worked with WatchOS (Swift) and currently with Xamarin. Let me know if that is of any use in this case. Btw, FMDB is the native library that works with SQLite on WatchOS. I tried to create binding library but apparently I can only create Xamarin iOS binding, not Xamarin.WatchOS

**Comment by ericsink** [comment]
Closing old/stale issue.
